### DISCUSSION TITLE
Hexo theme and css *still* not working with github custom domain

### DISCUSSION THREAD

**Discussion by leodenglovescode** [hexojs/hexo#4935] [Question / Answer] [answered]
My theme was working when I uploaded the code to Github, but after I used my custom domain (server.leosblog.xyz), the website loaded nothing except the text, but when not using the custom domain, only the Github one, works without a flaw! Can anyone help me again?

also here's my edited config.yml
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Leo's Blog!
subtitle: Welcome to Leo's Blog!
description: My hexo blog running on a Raspberry Pi!<br>Check out the "Writing" Section for more!
keywords:
author: Leodeng
language: en
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://server.leosblog.xyz
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solar

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git 
  repo: git@github.com:leodenglovescode/leosblog.git
  branch: main
```
here's a screenshot
<img width="914" alt="Screen Shot 2022-04-08 at 10 00 07 PM" src="https://user-images.githubusercontent.com/71826908/162451332-6d102ee5-ccb4-47bb-ba6f-b3bb0498ac2d.png">
