### DISCUSSION TITLE
After push，appear a new branch?how do I do that

### DISCUSSION THREAD

**Discussion by GC-ZF** [hexojs/hexo#4988] [Question / Answer] [answered]
Uploaded to the main,Is the expected result(这样是正确的)
```
deploy:
    type: git
    repository: https://github.com/xxx/xxxx.github.io.git	
    branch: main
```
But If I switch lines(I want to deploy multiple Git at the same time),for example(但是如果换一行，我想同时上传多个git)
```
deploy:
    type: git
    repository:
      github: https://github.com/xxx/xxxx.github.io.git
      xxxxxx:git@xxx.xxx.xxx.xxx
    branch: main
```
The github will appear a new branch "gh-pages"(仓库出现新的分支)
![image](https://user-images.githubusercontent.com/94956933/171801705-03bfc38e-e7e6-40b9-bc34-70c81aef3a7e.png)

I found that if switch line， the repository appear new branch，Whether "branch: main" or "gh-pages",(我测试发现，无论branch的值是main还是master，只要我换行就会出现这样的错误)
```
deploy:
    type: git
    repository:
      github: https://github.com/xxx/xxxx.github.io.git	
    branch: main
```

```
deploy:
    type: git
    repository:
      github: https://github.com/xxx/xxxx.github.io.git	
    branch: master
```

So how do I do that？These are the test repository
https://github.com/GC-ZF/T_hexo
https://github.com/GC-ZF/Test_hexo

**Comment by renbaoshuo** [comment, marked as answer]
您应该这样写：

```yaml
deploy:
  type: git
  repository:
    github:
      url: https://github.com/xxx/xxxx.github.io.git
      branch: main
    gitsb:
      url: git@git.sb/example/example.git
      branch: main
```
