### DISCUSSION TITLE
Github workflows blank white

### DISCUSSION THREAD

**Discussion by allasca** [hexojs/hexo#5060] [Question / Answer] [answered]
when I did hexo server local its work.
when using hexo clean && hexo deploy ([hexo-deployer-git](https://github.com/hexojs/hexo-deployer-git)) its work.
blank white when using workflows. workflows copied from the doc [https://hexo.io/docs/github-pages.html](https://hexo.io/docs/github-pages.html)
my git [https://github.com/allasca/allasca.github.io](https://github.com/allasca/allasca.github.io)

```
name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```

**Comment by yoshinorin** [comment]
@allasca 
Not sure but I assume you have to add submodule option for `actions/checkout`.

> https://github.com/actions/checkout#usage

**Comment by allasca** [comment, marked as answer]
@yoshinorin 
any idea for this? checkout@v2 submodule support was removed [https://github.com/actions/checkout/releases/tag/v2.0.0](https://github.com/actions/checkout/releases/tag/v2.0.0)

**Reply by yoshinorin** [reply]
@allasca 
I don't know what is mean of `Removed input submodules` in https://github.com/actions/checkout/releases/tag/v2.0.0.
But, as [GitHub Docs](https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-travis-ci-to-github-actions#checking-out-submodules) you can use submodule with `actions/checkout@v3`.

So, I assume you can use submodule with `actions/checkout@v3` like followings.

```yaml
- uses: actions/checkout@v3
  with:
    submodules: recursive
    # or submodules: true
```

---

P.S:

I have never use submodule with GHActions. So, I don't know you need more options etc...

**Reply by allasca** [reply]
not working.
```
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.G_TOKEN }}
          submodules: recursive
```
result
```
Error: fatal: remote error: upload-pack: not our ref 1b6cf4911a5862e9a770ba99dbaa8f7317c363bc
Error: fatal: Fetched in submodule path 'themes/next', but it did not contain 1b6cf4911a5862e9a770ba99dbaa8f7317c363bc. Direct fetching of that commit failed.
Error: The process '/usr/bin/git' failed with exit code 128
```
