### DISCUSSION TITLE
How to default the URL to not display the default `lang` in the permalink?

### DISCUSSION THREAD

**Discussion by lorezyra** [hexojs/hexo#5075] [Question / Answer] [answered]
I'm building a multilingual website (mostly Asian languages). However, the default language is English. How can I configure HEXO to not require the default lang (`config.permalink_defaults.lang`) in the URI, but have it for all the other languages I've built localized files?

My `config.permalink` is set to `:title/`. If I set to `:lang/:title/`, the default lang is always in the URL. How can I get HEXO to remove that?

For example:
- English (default): `https://Blog.RichieBartlett.com/Money/how-to-make-money-online/`
- Japanese: `https://Blog.RichieBartlett.com/ja/Money/how-to-make-money-online/`
- Vietnamese: `https://Blog.RichieBartlett.com/vi/Money/how-to-make-money-online/`
- Arabic: `https://Blog.RichieBartlett.com/ar/Money/how-to-make-money-online/`

## My `_config.yml` (partial)
```yml
## ...


## ISO 639-1 Code
language:
  - en #English
  - ja #Japanese
  - ar #Arabic
  - zh-TW # Traditional Chinese
  - zh-CN # Simplified Chinese

## IANA time zone
timezone: 'Asia/Tokyo'

## URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://lorezyra.github.io/project'
url: https://blog.RichieBartlett.com
root: /
## https://hexo.io/docs/permalinks
permalink: :lang/:title/
permalink_defaults:
  lang: en

## ...

```
