### DISCUSSION TITLE
exclude_languages does not work in code blocks

### DISCUSSION THREAD

**Discussion by D-Sketon** [hexojs/hexo#5085] [Question / Answer]
I tried to use code block and backquote code block at the same time, but `exclude_languages` only works for code blocks.
For example, my config.yml:
```yml
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  exclude_languages:
    - java
```
my post:
```md
    ```java
    public class Lab2 {
        public static void main(String[] args) {
        }
    }
    
    ```
    {% codeblock lang:java %}
    public class Lab2 {
        public static void main(String[] args) {
        }
    }
    {% endcodeblock %}
```
But not both are excluded: 
![image](https://user-images.githubusercontent.com/49871906/196875883-c8e13eb4-b968-4b8f-9cc3-b74788fd809d.png)
