### DISCUSSION TITLE
Hexo theme and css not loading on github pages

### DISCUSSION THREAD

**Discussion by leodenglovescode** [hexojs/hexo#5100] [Question / Answer] [answered]
Hello! My new hexo blog has been deployed on github pages, without any custom domains, but after the deploy when I go to my github.io webpage, it only shows text? what do I do? Thx

config.yml:
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ezCite
subtitle: '- The UlTiMaTe Citation Generator'
description: 'Made by Leodeng & Allen Wang with Time and misery'
keywords:
author: ezCite
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Pages, set url as 'https://username.github.io/project'
url: https://leodenglovescode.github.io/ecw
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: terminal

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: git@github.com:leodenglovescode/ecw.git
  branch: master
```

LOCAL SERVER:
<img width="1432" alt="Screen Shot 2022-11-09 at 12 57 53 PM" src="https://user-images.githubusercontent.com/71826908/200742546-cf2629f4-addf-4d1f-92c9-e3587019104c.png">

DEPLOYED WEBSITE: leodenglovescode.github.io/ecw
<img width="1439" alt="Screen Shot 2022-11-09 at 12 58 33 PM" src="https://user-images.githubusercontent.com/71826908/200742573-89a122de-e69f-448c-9227-30a551e4632d.png">
