### DISCUSSION TITLE
项目部署到服务器上后，css文件能加载到，但是样式没有应用到html中

### DISCUSSION THREAD

**Discussion by renjiancheng** [hexojs/hexo#5106] [Question / Answer] [answered]
本地效果：
<img width="1411" alt="image" src="https://user-images.githubusercontent.com/59160257/201855181-b549a2b2-08c7-423b-a164-4c093ec2f35b.png">
部署后：
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/59160257/201855764-20d5a9e2-eb0e-436f-9ad9-aba865ee581d.png">
<img width="1453" alt="image" src="https://user-images.githubusercontent.com/59160257/201855936-2a04e931-d98a-4e36-b31a-ace1f926efb6.png">
从浏览器控制台来看，部署后所有的资源都已经加载到了，但是css的样式还是没有应用到。我尝试了清除缓存，配置站点配置文件的url和root选项，但是都没有效果，请问是哪里出问题了哎？下面是我的配置文件和hexo版本信息：
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Blogs
subtitle: '寄蜉蝣于天地，渺沧海之一粟。'
description: '一名程序员和音乐爱好者'
keywords:
author: JC
language: zh-Hans
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.zardfans.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: ****
  branch: master
```
```text
$ hexo -v
INFO  Validating config
hexo: 5.4.2
hexo-cli: 4.3.0
os: darwin 22.1.0 13.0.1

node: 16.17.0
v8: 9.4.146.26-node.22
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.7
openssl: 1.1.1q+quic
cldr: 41.0
icu: 71.1
tz: 2022a
unicode: 14.0
ngtcp2: 0.1.0-DEV
nghttp3: 0.1.0-DEV
```
