### DISCUSSION TITLE
`<span>` still exist after excluding languages in code highlighting

### DISCUSSION THREAD

**Discussion by D-Sketon** [hexojs/hexo#5111] [Question / Answer]
I try to exclude java in highlight like this:
```yaml
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
  exclude_languages:
    - java 
```
But I find that `<span>` tags still exist
![image](https://user-images.githubusercontent.com/49871906/202956397-cd94fd77-7842-4d8e-b91e-4e0991964174.png)

Or is there something wrong with my understanding of `exclude_languages`?
