### DISCUSSION TITLE
Image can't be displayed correctly

### DISCUSSION THREAD

**Discussion by serend1p1ty** [hexojs/hexo#5323] [Question / Answer]
I am new to HEXO. My blog has a strange problem now: Images can't be displayed correctly, and the reason I have found is the images have incorrect path.
According to the results I have found in Google, I got a solution:

1. Set `post_asset_folder = true`

2. Download a plugin using `npm install https://github.com/CodeFalling/hexo-asset-image --save`

3. Using relative path in markdown like this `![]（test.png）`

But the problem of incorrect image path still haven't be solved, because I found there is a prefix in every image path. Just like this.
![fkmd98uf7np yjx oda kf2](https://user-images.githubusercontent.com/39628662/50353535-8020d200-0583-11e9-9b5a-ad0d12c907de.png)
What a strange prefix `yoursite.com`! Can anyone help me? I will be very grateful.
Here is my configuration of HEXO.
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```
```
deploy:
  type: git
  repository: git@github.com:GooCoder/GooCoder.github.io.git
  branch: master
```

**Comment by serend1p1ty** [comment]
Can anyone help me? I really need your help.

**Comment by serend1p1ty** [comment]
Thanks for your kindness.

**Comment by aghontpi** [comment]
i have problem with the image as well,
image is being generate with the '/' infront of it. thus file not found error is thrown.

```html
 <img src="/blog/2018/11/26/xxxx-xxx/tT.gif">

But it should be

 <img src="blog/2018/11/26/xxxx-xxx/tT.gif">
```

configs:

```yaml
url: url/blog/
note here,  only the url is 'url/blog', but the folder structure is just root.
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
```

```yaml
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
```
