### DISCUSSION TITLE
Cannot generate properly on GitHub Actions. 本地成功而在 GA 上 generate 不能得到正确的 public 目录。

### DISCUSSION THREAD

**Discussion by inaku-Gyan** [hexojs/hexo#5512] [Question / Answer] [answered]
It works well on my own PC:
When I run `hexo clean` and `hexo g`, it generates the dir public/ properly, which contains all the dirs and files that should be there. And I can use Git to push it into my repo and GitHub Pages builds the site, everything works good.

我自己在电脑上执行 `hexo clean` 和 `hexo g` 后就能够生成正确的 public 目录及底下的所有需要的文件和目录。然后我把 public 目录 push 到仓库里，GitHub Pages 就能够正常地构建网站，网站内容一切正常。

正确的 public 目录大概长成这样： The proper `public/` looks like:
![image](https://github.com/hexojs/hexo/assets/63503085/08cb5465-d115-4a01-805e-5c95b1fe7684)

But when I try to use GitHub Actions to do this automatically, it goes wrong. In the workflow, the directory public/ generated by `hexo clean` and `hexo g` only contains    2024/07/...   archives/...    and   index.html       , and the index.html in it are empty (0kb). So the site published by GitHub Pages is also empty.

但当我用 GitHub Actions 来自动完成上述操作时，workflow 中的 `hexo clean` 和 `hexo g` 生成的 public 目录里面文件就会不全，就只会生成 2024/07/... 和 archives/... 和一个空的 index.html，archives 目录底下也还有几级目录和几个 index.html，也都是空的（0kb）。

the improper one is as this:
![image](https://github.com/hexojs/hexo/assets/63503085/1be9596f-72ee-4e8f-b015-8a96df7594cf)

Part of my workflow file deploy.yml is as follow:
workflow 的部分代码如下：
```yaml
runs-on: ubuntu-latest  # 指定该程序运行所在的虚拟机

steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块检查

      - name: 2. Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 用于指定使用的 Node.js 版本。建议使用与自己电脑中相同的版本，以避免可能的 IWOM 问题。

      - name: 3. Install Dependencies
        run: npm install

      - name: 4. Install Hexo
        run: |
          npm install hexo-cli -g

      - name: 5. Clean and Generate Static Files
        run: |
          hexo clean
          hexo generate
          cd public
          echo public/
          tree -L 5
          cd ..
```

其中的 `node-version` 12、14、16、18、我都试过了都没有效果。
I tried 12, 14, 16, 18 as `node-version`, but none of them work.

PLZ help
