### DISCUSSION TITLE
hexo g 突然报错，无法生成，无法上传github.io

### DISCUSSION THREAD

**Discussion by Zgh20060114** [hexojs/hexo#5549] [Question / Answer] [answered]
### Check List

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [ ] I have already searched existing issues and they are not help to me.
- [ ] I examined error or warning messages and it's difficult to solve.
- [ ] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [ ] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

input "hexo g" in Ubuntu20.04, It worked normally before

### Actual behavior

But now it will report an error：

```
zgh@zgh-Legion-Y7000P-IAH7:~/Blog/Zgh20060114.github.io$ hexo g
INFO  Validating config
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
Error: Unexpected character +
Please report this to https://github.com/markedjs/marked.
    at w (/home/zgh/Blog/Zgh20060114.github.io/node_modules/fenceparser/dist/index.cjs:1:1010)
    at lex (/home/zgh/Blog/Zgh20060114.github.io/node_modules/fenceparser/dist/index.cjs:1:1076)
    at parseFence (/home/zgh/Blog/Zgh20060114.github.io/node_modules/hexo-plugin-aurora/lib/highlighter/index.js:71:18)
    at renderer.code (/home/zgh/Blog/Zgh20060114.github.io/node_modules/hexo-plugin-aurora/lib/highlighter/index.js:126:19)
    at Parser.parse (/home/zgh/Blog/Zgh20060114.github.io/node_modules/marked/lib/marked.cjs:2158:34)
    at parse (/home/zgh/Blog/Zgh20060114.github.io/node_modules/marked/lib/marked.cjs:2088:19)
    at /home/zgh/Blog/Zgh20060114.github.io/node_modules/marked/lib/marked.cjs:2509:18
    at marked (/home/zgh/Blog/Zgh20060114.github.io/node_modules/marked/lib/marked.cjs:2524:48)
    at module.exports (/home/zgh/Blog/Zgh20060114.github.io/node_modules/hexo-renderer-marked/lib/renderer.js:250:20)
    at Hexo.tryCatcher (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/method.js:15:34)
    at /home/zgh/Blog/Zgh20060114.github.io/node_modules/hexo/lib/hexo/render.js:81:22
    at tryCatcher (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/home/zgh/Blog/Zgh20060114.github.io/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:478:21)
INFO  Thanks for using: hexo-plugin-aurora v1.8.4 & hexo-theme-aurora v2.5.3
INFO  Crafted by bennyxguo <三钻>
```

### How to reproduce?

input  hexo g

### Is the problem still there under `Safe mode`?

don't know

### Your Node.js & npm version

zgh@zgh-Legion-Y7000P-IAH7:~$ node -v
v20.10.0
zgh@zgh-Legion-Y7000P-IAH7:~$ npm -v
10.2.3

```
### Your Hexo and Plugin version

_No response_

### Your `package.json`

_No response_

### Your site's `_config.yml` (Optional)
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Zgh's
subtitle: ''
description: 'Zgh的个人站'
keywords:
author: John Doe
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://Zgh20060114.github.io
#permalink: :year/:month/:day/:title/
permalink: /post/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: aurora

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment

### Others

_No response_
```
