### DISCUSSION TITLE
Migrating post type to new type journal

### DISCUSSION THREAD

**Discussion by enkr1** [hexojs/hexo#5556] [Question / Answer]
I have been managing my journals by simply using `hexo new ...` commands to create posts, but I realized that my blog page is getting cluttered with these entries. To clean things up, I’ve decided to split my journals into a new page or section.

Here’s what I’ve done so far:

1. **Custom Scaffold for Journals**: I’ve set up a custom scaffold `journal.md` to structure my journal entries with predefined tags, categories, and comments, which looks like this:
    ```yaml
    ---
    title: "Journal: Week {{ week }}"
    date: {{ date }}
    tags:
      - journal
    categories:
      - "About Me"
      - "Journals"
      - {{ date | date('YYYY') }}
    comments: false
    ---
    ```

2. **Creating a Separate Directory**:  
   I’ve created a `source/_journals` folder and tried to configure my `_config.yml` to manage these entries separately:
    ```yaml
    journals_dir: source/_journals
    ```

3. **Bash Automation**:  
   I’ve written a simple Bash script that automates journal creation with a custom filename (`jYYMMDD.md` format) and injects the right content dynamically, including the journal title, date, and headers.

   **Script sample**:
   ```bash
   # Get the current date in the format yymmdd
   DATE=$(date +%y%m%d)
   FILENAME="source/_journals/j$DATE.md"
   # Create journal and insert the scaffold template
   ```

---

**Question**:  
Is there a better or more official way to handle journal creation with specific titles, headers, and categories in Hexo? My goal is to quickly generate a journal entry with the right structure in a separate folder, without cluttering my main blog posts. I would love to know if anyone has a more efficient way to manage this process through Hexo commands or an alternative approach to my bash solution.

Thanks in advance!
