### DISCUSSION TITLE
You should configure deployment settings in _config.yml first!  Available deployer plugins:   git

### DISCUSSION THREAD

**Discussion by xunlongdingxue** [hexojs/hexo#5615] [Question / Answer] [answered]
I have set up with the command  npm install hexo-deployer-git --save
and hexo clean  and hexo generate and hexo deploy and yml`s content 
is

```yaml
 theme: next
# Deployment
## Docs: https://hexo.io/docs/deployment.html

deploy:
type: git
repository: git@github.com:xunlongdingxue/xunlongdingxue.github.io.git 
```

but when deploy the teminal give the message
```bash
You should configure deployment settings in _config.yml first!  Available deployer plugins:   git
```
what should I do to solve the problem?
