### ISSUE TITLE
hexo deploy 提示 'github' does not appear to be a git repository

### ISSUE THREAD

**Issue by okoala** [hexojs/hexo#105]
### 下面是我的操作：

```
[root@localhost blog]# hexo version
hexo: 1.0.4
http_parser: 1.0
node: 0.8.21
v8: 3.11.10.25
ares: 1.7.5-DEV
uv: 0.8
zlib: 1.2.3
openssl: 1.0.0f

[root@localhost blog]# ssh -T git@github.com
Enter passphrase for key '/root/.ssh/id_rsa': 
Hi okoala! You've successfully authenticated, but GitHub does not provide shell access.

[root@localhost blog]# hexo deploy --generate
Loading.
Generated compeletely.
Site gnerated in 0.395s.
Clearing
Copying files from public folder.
[master 3ba2b85] Site updated: Mon Mar 04 2013 09:54:04 GMT+0800 (CST)
 6 files changed, 6 insertions(+), 6 deletions(-)
fatal: 'github' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
```
### 下面是deploy的配置：

```
# Deployment
## Docs: http://zespia.tw/hexo/docs/deploy.html
deploy:
  type: github
  repository: git@github.com:okoala/okoala.github.com.git
  branch: master
```

这如何解决呢？
