### ISSUE TITLE
Search form rendered incorrect in OS X Safari

### ISSUE THREAD

**Issue by kqkq** [hexojs/hexo#1050]
![a](https://cloud.githubusercontent.com/assets/4627169/6186524/5bd12130-b3b5-11e4-8ab5-0d0098facd23.jpg)

Safari had a problem to render a input which `type="search"`. 

Maybe we **can't** solve this issue by modify CSS. It's a problem in `search_form()` helper which assign the `input` type as `search`.

**Comment by tommy351** [comment]
This can be solved by modifying the CSS like this:

``` css
.search-form-input {
  -webkit-appearance: none;
}
```
