### ISSUE TITLE
hexo generate 生成的 xxx/archives/ 页面丢失很多文章连接

### ISSUE THREAD

**Issue by bubkoo** [hexojs/hexo#1211]
我将 hexo 升级到最新版之后出现了所述现象
hexo 的版本是 3.0.1
模板采用默认的 landscape 
我的归档页面原来有从 2013 年到 2015 年的完整文章连接，在结果只有最新的 10 个文章连接

**Comment by bubkoo** [comment]
在其他归档页面也有该问题，比如在 xxx/archives/2014/03/ 中本来有 15 篇文章，结果生成的还是只有 10 篇

**Comment by bubkoo** [comment]
视乎我明白了是什么情况，在 `_config.yml` 文件中配置了 `per_page: 10`，这里提出另一个问题，怎么样做到在归档页中不分页，而显示该归档下的全部文章？

**Comment by Xuanwo** [comment]
per_page: 0

**Comment by bubkoo** [comment]
首页需要分页的

**Comment by Xuanwo** [comment]
```
# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 0
category: 0
tag: 0
```

自己调一调看看吧= =，没研究过这个。

**Comment by bubkoo** [comment]
最新版本中没有这些配置项了，上面的这些配置项是用于主版本号 3 以下的吧

**Comment by Xuanwo** [comment]
额，那你摸索一下吧，把结果分享给社区呗~

**Comment by bubkoo** [comment]
看了 `hexo-generator-xxx` 的代码后，明白了，在配置中添加如下项就可以禁用对应归档页的分页：
```yaml
archive_generator:
  yearly: true
  monthly: true
  per_page: 0

category_generator:
  per_page: 0

tag_generator:
   per_page: 0
```

close #1211
