### ISSUE TITLE
pagination_dir is not respected

### ISSUE THREAD

**Issue by celsomiranda** [hexojs/hexo#1217]
Steps to reproduce:

Change `_config.yml` to:
``` yaml
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: 'pagina'
```

Paginator helper links to `pagina`, but both the generator and the server only render the original `page` and not `pagina`. Server gives 404.

If url manualy entered for `page` instead of  `pagina` all is well, so this bug must be somewhere in the routes or something.
