### ISSUE TITLE
Pagination issue: files and directories are generated but links are not

### ISSUE THREAD

**Issue by kqkq** [hexojs/hexo#1257]
I have a problem when update to hexo 3.0. The `archives/` page shows only 10 entries with **no links to next page**. I have found that the files are already generated in `public/archives`. There's 1/2/3... directories in `public/archives/page`, each one with an `index.html` in it. I had the same problem with category page.

I'm using theme `landscape`. I tried to update `landscape` to newest original version and add following code to `_config.yml` but did not help.

```
# Archive
## https://github.com/hexojs/hexo-generator-archive
archive_generator:
  per_page: 10
  yearly: true
  monthly: false
```
