### ISSUE TITLE
Disabling archive, category, tag pagination in 3.0

### ISSUE THREAD

**Issue by ideoplex** [hexojs/hexo#1334]
I'm trying to upgrade to from 2.8 to 3.0.

I could disable [archive](http://ideoplex.com/archives/2014/), [category](http://ideoplex.com/categories/technology/) and [tag](http://ideoplex.com/tags/java/) pagination by setting config.archive, config.category and config.tag to 1. Looks like this capability has been removed.

Did I miss something? If not, any hints on where I should start to add it back in?

Thanks

**Comment by Xuanwo** [comment]
```
per_page: 10
pagination_dir: page

archive_generator:
  yearly: true
  monthly: true
  per_page: 0

category_generator:
  per_page: 0

tag_generator:
   per_page: 0
```
