### ISSUE TITLE
怎么临时取消代码块的行号？

### ISSUE THREAD

**Issue by mwlgcmwlgc** [hexojs/hexo#1342]
在一篇文章中，代码块默认有行号，想要让某些代码块没有行号，要怎么做？
四个空格缩进的代码块可以是没有行号的，但是跟 使用 ``` 的代码块颜色是不一样的，我希望看起来都是相同的样式～～

**Comment by Xuanwo** [comment]
自己修改CSS

**Comment by leesei** [comment]
Highlight.js's config is applied to site-wise.
There is currently no way to use different option for a specify code block.

```
highlight:
  enable: true
  line_number: false
  tab_replace:
```
