### ISSUE TITLE
修改了 url 和 root 后,有些页面的链接出现了问题

### ISSUE THREAD

**Issue by tcstory** [hexojs/hexo#1377]
使用的主题是light, hexo版本如下所示

    ➜  Blog  hexo -v
    hexo: 3.1.1
    os: Linux 3.16.0-41-generic linux x64
    http_parser: 1.0
    node: 0.10.25
    v8: 3.14.5.9
    ares: 1.10.0
    uv: 0.10.23
    zlib: 1.2.8
    modules: 11
    openssl: 1.0.1f
    ➜  Blog  

出现的问题如图片所示

![1](https://cloud.githubusercontent.com/assets/5856466/8547085/0d6ca086-24ef-11e5-8074-51e3e09ff7b1.png)
点击"archives"和"about"后的反映如下
![2](https://cloud.githubusercontent.com/assets/5856466/8547084/0d69a0a2-24ef-11e5-92e9-3bad0367fd4e.png)
![3](https://cloud.githubusercontent.com/assets/5856466/8547086/0db48cf2-24ef-11e5-9330-c716fa6ec6d7.png)

下面是配置信息:

全局的_config.yml文件

```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 花瓣奶牛的博客
subtitle:
description:
author: tcstory
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://tcstory.github.io/MyBlog/
root: /MyBlog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: light

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/tcstory/MyBlog.git
```

这个是主题的_config.yml

```
menu:
  Home: /
  Archives: /archives
  About: /about

widgets:
- search
- category
- tag

excerpt_link: 阅读全文


addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics:
rss:

comment_provider: 
```
public文件如下

![4](https://cloud.githubusercontent.com/assets/5856466/8547162/aac613b2-24ef-11e5-8fbf-c4cc4a298401.png)
