### ISSUE TITLE
hexo3.1.1 category_map不生效？

### ISSUE THREAD

**Issue by NewbMiao** [hexojs/hexo#1549]
标签/分类的别名
在_config.yml里面配置

```
    category_map:
      工具集: tools
      技术集: technique
    tag_map:
      JavaScript: js
      css: css
      html5: html5
```

环境是mac系统
怎么解决啊

**Comment by Xuanwo** [comment]
根据yml格式要求的话，似乎应该这样：
```
category_map:
      - 工具集: tools
      - 技术集: technique
tag_map:
      - JavaScript: js
      - css: css
      - html5: html5
```
