### ISSUE TITLE
template render error: parseAggregate: expected colon after dict key

### ISSUE THREAD

**Issue by ocxsBlog** [hexojs/hexo#1605]
When I run `hexo g`, some errors happened, there are as follows.

```cpp
template render error: parseAggregate: expected colon after dict key
at Error.exports.TemplateError (e:\blog\Hexo\node_modules\hexo\node_modules\nunjucks\src\lib.js:51:19
·····
```

In my context, a equation using latex was written, here are shown for you.

> be shown as equation(3):
\begin{equation}
G(x,y) = Ae^{- \left( \frac{{\left(x-{\mu}_{x} \right)}^{2}}{2{{\sigma}_{x}}^{2}} + \frac{{\left(y-{\mu}_{y} \right)}^{2}}{2{{\sigma}_{y}}^{2}}	\right)} \tag{3}
\end{equation} 

If I deleted this ,no error happened.

But If 
> 如公式(2)所示: 
\begin{equation}
G(x) = Ae^{-x^2/2\sigma^2}	\tag{2}
\end{equation} 

was written in context, no error happened too.

And the case needed to be said is that I add 
```
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=default"></script>
```
in my context. Does it make something wrong ?
I cannot handle this problem, Help~
Thanks in advance~

More information is shown in image.
![image](https://cloud.githubusercontent.com/assets/15309027/11323817/6716cc84-9159-11e5-8524-da7ac7f56fa8.png)
![image](https://cloud.githubusercontent.com/assets/15309027/11323819/7d9dd15a-9159-11e5-87c6-05bdc5954e14.png)
![image](https://cloud.githubusercontent.com/assets/15309027/11323820/8290e738-9159-11e5-89bc-96891d456198.png)
![image](https://cloud.githubusercontent.com/assets/15309027/11323825/89d646dc-9159-11e5-8884-7d3f77f90502.png)
![image](https://cloud.githubusercontent.com/assets/15309027/11323826/9154a73c-9159-11e5-9ac6-e5624e5d19a6.png)

**Comment by Xuanwo** [comment]
@ocxsBlog I used mathjax before without problem. And can you paste your yml info of your post? (content beofre `---`)

**Comment by ocxsBlog** [comment]
@Xuanwo I'm sorry, I don't find "your yml info of your post"?  Do you mean my "`_config.yml`"? or "`_config.yml`" in themes? (I have two `_config.yml` files ,one in global `./`, one in themes `./themes/yilia/`)

here are yml for you.

global:
```yml
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ocxs's blog
subtitle: To be better
description:
author: ocxs
email: # ocxswork@163.com
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: site:ocxsBlog.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
max_open_file: 100	#
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: categorized 
# uncategorized
category_map:
tag_map:

# Archives 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: yilia

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:ocxsBlog/ocxsBlog.github.io.git
  branch: master
```

one in themes 

```yml
# Header
menu:
  主页: /
  所有文章: /archives
  # CV: /CV/cv.pdf
  # 关于: 
  # 随笔: /tags/随笔

# SubNav
subnav:
#  github: "#"
#  weibo: "#"
 # rss: "#"
 # zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.ico

#你的头像url
avatar: "/img/avatar.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
#friends:
#  奥巴马的博客: http://localhost:4000/
 # 卡卡的美丽传说: http://localhost:4000/
#  本泽马的博客: http://localhost:4000/
#  吉格斯的博客: http://localhost:4000/
#  习大大大不同: http://localhost:4000/
#  托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: Computer Vision.
```
