### ISSUE TITLE
如何支持多个作者同时写博客

### ISSUE THREAD

**Issue by yeziahehe** [hexojs/hexo#1640]
现在遇到的问题不能多个作者同时写博客，每个人端的文章只能把自己的本地的文章进行渲染，其他的就不行。

**Comment by Xuanwo** [comment]
https://github.com/hexojs/site with more than 85 author.

**Comment by yeziahehe** [comment]
请问这样是建两个repo吗？

**Comment by yeziahehe** [comment]
[探索工作流：Travis CI 自动化构建 Hexo (一) ](http://v2cc.github.io/2015/09/02/unbelievable-workflow-autodeploy-hexo-by-travis/)
找到了一些资料，正在搭建中。

**Comment by Xuanwo** [comment]
你可以参考下这篇文章， https://xuanwo.org/2015/02/07/Travis-CI-Hexo-Autodeploy/ ， 主要的工作流还是基于Git的。

**Comment by yeziahehe** [comment]
我按照博客的做法，最后并没有构建出版本，但是Travis CI中的request提示如下
![Uploading 屏幕快照 2015-12-10 下午2.38.43.png…]()

**Comment by yeziahehe** [comment]
<img width="955" alt="2015-12-10 2 57 12" src="https://cloud.githubusercontent.com/assets/8090437/11709021/f9a45b36-9f4e-11e5-918f-4bdffdc75583.png">
<img width="904" alt="2015-12-10 2 44 59" src="https://cloud.githubusercontent.com/assets/8090437/11709020/f99b5b58-9f4e-11e5-9f99-c0165436f8a7.png">

**Comment by Xuanwo** [comment]
`missing config`, you should put a `.travis.yml` in your blog branch, likes: https://github.com/Xuanwo/xuanwo.github.io/blob/blog/.travis.yml

**Comment by yeziahehe** [comment]
目前解决了，有个坑是，`.travis.yml` 中不能写中文，因为我有中文注释，也可能是就不能写注释。

**Comment by Xuanwo** [comment]
据我所知，应该是可以写注释的，中英文这个，应该没啥问题吧，都是UTF-8，编码意义上来说是一样的，不过不支持多行注释是真的。

**Comment by yeziahehe** [comment]
```
sudo travis login --auto
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/openssl/ssl.rb:232:in `post_connection_check': hostname "api.travis-ci.org" does not match the server certificate (Faraday::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:923:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1373:in `request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Library/Ruby/Gems/2.0.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `head'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:206:in `public_send'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:206:in `block in raw'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:273:in `block in instrumented'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:274:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:274:in `block in instrumented'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:275:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:275:in `instrumented'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:205:in `raw'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:330:in `check_ssl'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client/session.rb:40:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/client.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/api_command.rb:37:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/parser.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli/parser.rb:36:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/lib/travis/cli.rb:62:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/travis-1.8.0/bin/travis:18:in `<top (required)>'
	from /usr/local/bin/travis:23:in `load'
	from /usr/local/bin/travis:23:in `<main>'
```

**Comment by Xuanwo** [comment]
恩？这个看起来是SSL证书的问题啊。

**Comment by yeziahehe** [comment]
<img width="872" alt="2015-12-10 7 26 57" src="https://cloud.githubusercontent.com/assets/8090437/11715919/f3626ba0-9f80-11e5-958b-54d2e8dcd9bb.png">
想问个问题，为什么每次`hexo d -g`为什么每次都要输入账户名和密码？

**Comment by Xuanwo** [comment]
配置SSH之后就不用了

**Comment by yeziahehe** [comment]
_config.yml改下ssh的地址就行。
麻烦看下，为什么博客首页什么都没有。
https://github.com/Coryphaei/coryphaei.github.io

**Comment by Xuanwo** [comment]
https://github.com/Coryphaei/coryphaei.github.io/blob/master/index.html

因为index本来就什么都没有啊= =

**Comment by yeziahehe** [comment]
但是问题在于我是通过Travis CI去渲染的，渲染出来就是index.html就是空的

**Comment by Xuanwo** [comment]
现在访问没问题了， http://blog.coryphaei.com/

**Comment by yeziahehe** [comment]
因为我直接运行了hexo d -g
我现在又push了，估计又没了

**Comment by Xuanwo** [comment]
把你的`.travis.yml`脚本贴一下，我猜是有插件没有安装

**Comment by yeziahehe** [comment]
```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Coryphaei技术博客
subtitle:
description: Coryphaei技术分享博客。
author: coryphaei
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - README.md
  - CNAME

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:Coryphaei/coryphaei.github.io.git
  branch: master

# Duoshuo ShortName
duoshuo_shortname: coryphaei

# Baidu Analytics ID
baidu_analytics: 4c234300b38c9119f8b85e05d946803c

# Build Blog Time
since: 2015

# title, chinese available
links_title: Links
# links
links:
  Corypahei: https://github.com/Coryphaei
```
