### ISSUE TITLE
子目录链接不正确。incorrect link when put website in subdirectory

### ISSUE THREAD

**Issue by masquevil** [hexojs/hexo#1674]
将网站存放在子目录的时候，使用默认主题（landscape），左上角的“home”和“archives”链接会出错。

When I put hexo blog in a subdirectory ( /martin/blog/ ) , by using default theme (landscape), the link at the left top corner "home" and "archives" will be a mistake. It comes to be "/" and "/archives" when it should be "/martin/blog/" and "/martin/blog/archives"

**Comment by masquevil** [comment]
Solved.

Edit file `themes/landscape/_config.yml`, change this:

```
menu:
  Home: /
  Archives: /archives
rss: /atom.xml
```

Into this:

```
menu:
  Home: ./
  Archives: ./archives
rss: ./atom.xml
```
