### ISSUE TITLE
Pagination helper not using `config.root` for page 1

### ISSUE THREAD

**Issue by cgmartin** [hexojs/hexo#1694]
The pagination "page 1" URL link doesn't seem to work with the following configuration:

``` yml
# _config.yml
# URL
url: http://my.site/subdir
root: /subdir/
# Pagination
per_page: 5
pagination_dir: page
```

``` ejs
<!-- index.ejs -->
<%- paginator({ prev_text: 'Prev', next_text: 'Next' }) %>
```

The URL for page number "1" results in `href="/"`, which links to the root of `http://my.site/` (not the subdir). 

All other page links successfully include the configured root subdir (ie.`href="/subdir/page/2/"`).
