### ISSUE TITLE
markdown语法下锚点生成和页面内跳转的问题

### ISSUE THREAD

**Issue by Jeffrey95** [hexojs/hexo#1767]
```
hexo: 3.1.1
os: Windows_NT 10.0.10586 win32 x64
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
```

为什么我使用markdown语法
`[原因](#jump)`
生成的却是
`<a href = /#jump>原因</a>`
而不是
`<a href = #jump>原因</a>`?

应该怎么实现页面内跳转呢？

**Comment by leesei** [comment]
https://github.com/hexojs/hexo/issues/1741

你的`_config.yaml` 傳來看看
我自己的測沒有這問題 (`hexo init` 的site)

**Comment by Jeffrey95** [comment]
@leesei 我之前已经试过像[#1741](https://github.com/hexojs/hexo/issues/1741)中的方法，直接用html来写，可以实现。

你叫我传我文件，是指我的hexo根目录下的`_config.yml`吗？

**Comment by leesei** [comment]
是

你也可以clone 一下https://github.com/leesei/hexo-vanilla-site 試試

**Comment by leesei** [comment]
On 3.2beta the link is fine:
http://leesei.github.io/hexo-vanilla-site/2016/02/22/1741/

**Comment by Jeffrey95** [comment]
这是我的_config文件配置：

```
# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: HelloWorld 
subtitle: 什么都想学的好奇宝宝 
description: Now or Never 
author: 疯疯
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.qiujinfeng.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hexo-theme-yilia

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy: 
- type: git
  repository: git@github.com:Jeffrey95/Jeffrey95.github.io.git 
  branch: master 

- type: git
  repository: git@gitcafe.com:Jeffrey95/Jeffrey95.git
  branch: gitcafe-pages

# Extensions
Plugins:
- hexo-generator-sitemap

#sitemap
sitemap:
  path: sitemap.xml

baidusitemap:
    path: baidusitemap.xml

```

我觉得可能是我的hexo版本？hexo在npm上面的latest version是:`3.1.1`
请问下我怎么才可以保留现有的theme,posts等文件的基础上升级hexo版本到`3.2.0 beta2`呢？
