### ISSUE TITLE
deploy成功后,css失效了0-0

### ISSUE THREAD

**Issue by sunlanda** [hexojs/hexo#1783]
额,我又来提问了  ..
这次是deploy部署成功后,通过gh-pages访问io预览,发现css和js都未加载成功 (报错信息: not found)

之前手动改过这些文件的绝对路径,可以成功(个人感觉应该是相对路径出的问题),但是deploy后肯定覆盖了,自己google一堆实在解决不动了,issue求拯救   ~
(猜测是yml设置?或是命令行处理修改绝对路径)

请移步案发现场:( http://sunlanda.github.io/sunlanda-blog/ ) ->控制台

**Comment by zyxscientist** [comment]
有可能是你使用的主题需要别的渲染器(jade或者scss）？那么你就要去做一连串的下载。
如果需要检查是否是hexo本身的问题，那么你就多使用几个主题试试吧。

**Comment by leesei** [comment]
用`http://sunlanda.github.io/sunlanda-blog/` 的話要這樣配:
```yaml
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://sunlanda.github.io/
root: /sunlanda-blog/
```
