### ISSUE TITLE
Why there are only 10 blogs shown in one tag, but the blogs are actually more than 10 ...

### ISSUE THREAD

**Issue by icetime17** [hexojs/hexo#1804]
The same issue happens on the month tag.

**Comment by leesei** [comment]
Please be specific, post source and link to the site.

**Comment by leesei** [comment]
Your problem is not common, it works fine in my site:
http://leesei.github.io/tags/shell-tool/
http://leesei.github.io/categories/comp-lang/

**Comment by tiexo** [comment]
标签页显示的标签数量，和站点config文件中定义的，首页文章显示数量一致
这就导致了如果你标签页面下的数量超过了，只会显示一部分

这个现象在归档页，目录页都是如此
虽然不算bug，但是依然体验不够好。。。

**Comment by leesei** [comment]
@tiexo Thanks for the info.
After reviewing my config, the `comp-lang` page did show only 20 posts, the label showed 27.

The limit of 20 is set in config of `category_generator`:
```yaml
# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
## 1 to show titles only
archive: 1
category: 1
tag: 1

# hexo-generator-archive
archive_generator:
  per_page: 20
  yearly: true
  monthly: true

# hexo-generator-category
category_generator:
  per_page: 20

# hexo-generator-tag
tag_generator:
  per_page: 20
```
