### ISSUE TITLE
为什么我死活传不上去阿

### ISSUE THREAD

**Issue by huangbao** [hexojs/hexo#1808]
配置
deploy:  
type: git
repo: git@github.com:huangbao/huangbao.github.io.git
没有错阿，都检查好几次了

错误描述
You should configure deployment settings in _config.yml first!
Available deployer plugins:
  git
For more help, you can check the online docs: http://hexo.io/

**Comment by Xuanwo** [comment]
注意yml格式
```
deploy: 
    type: git
    repo: git@github.com:huangbao/huangbao.github.io.git
    branch: master
```
