### ISSUE TITLE
share link wrong with sub path

### ISSUE THREAD

**Issue by Jintin** [hexojs/hexo#1812]
Thanks for your great work, I'm Taiwanese too.

Please check out this sample.
https://jintin.github.io/blog/2016/02/28/monthly-github/

The share link and comment link is wrong (one more /blog/).

https://jintin.github.io/blog/blog/2016/02/28/monthly-github/#disqus_thread
https://Jintin.github.io/blog/blog/2016/02/28/monthly-github/

My config is

```
url: https://Jintin.github.io/blog/
root: /blog/
```

**Comment by tommy351** [comment]
It seems `post.permalink` return a wrong URL. I'll fix it later.

**Comment by leesei** [comment]
#1608 may be related

**Comment by ged1959** [comment]
Is this the same problem?

[http://ged1959.github.io/blog-hexo/](http://ged1959.github.io/blog-hexo/)

**Comment by leesei** [comment]
@ged1959 no, you have to set these two correctly

```yaml
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://ged1959.github.io/blog-hexo/
root: /blog-hexo/
```
