### ISSUE TITLE
Display all articles in archive

### ISSUE THREAD

**Issue by onmyway133** [hexojs/hexo#1890]
Hi, I just changed my blog http://www.fantageek.com/ from octorpress to hexo, and I really like it. Thanks a lot

But I'd like to display all my posts in the archive page http://www.fantageek.com/archives/, instead of group them by month. I can't seem to find that settings in the config file

Thanks

**Comment by Jamling** [comment]
The defaut <var>list_archives()</var> not support posts in arachive, you can modify <var>list_archives()</var> to support it. 
Another way: you can change your theme which displays articles in archive, here is an example: 
[hexo-theme-nova](https://github.com/Jamling/hexo-theme-nova), use <var>nova_list_archives()</var> to display articles in archive.

**Comment by Xuanwo** [comment]
```
archive_generator:
  yearly: true
  monthly: true
  per_page: 0

category_generator:
  per_page: 0

tag_generator:
   per_page: 0
```
