### ISSUE TITLE
hexo deploy之后提交到github后文件结构错误

### ISSUE THREAD

**Issue by diov** [hexojs/hexo#1987]
本地使用hexo g + hexo s之后可以访问
但是hexo d之后推到github之后并没有把public目录下的文件推上来
而是把本地的blog根目录下的文件都推上来了

仓库的地址是：https://github.com/nullopp/nullopp.github.io

**Comment by Xuanwo** [comment]
因为你这个blog根目录本身就使用git进行管理了，建议把blog目录用一个新的分支或者一个新的库进行管理。

**Comment by peierlong** [comment]
我遇到了同样的问题, 请问怎么解决的呢?

**Comment by NoahDragon** [comment]
@peierlong 在config file里设置deploy的branch。
```
deploy:
  type: git
  repo: <repository url>
  branch: [branch]
```
