### ISSUE TITLE
Processing error while set highlight to off

### ISSUE THREAD

**Issue by Xuanwo** [hexojs/hexo#2029]
while I set highlight like this:

```
highlight:
  enable: false
  line_number: false
  auto_detect: false
```

The build failed like: https://travis-ci.org/Xuanwo/xuanwo.github.io/builds/111965103 , which is the same like https://github.com/hexojs/hexo-generator-feed/issues/26 .
This looks like a BUG.

@pinggod @tommy351 @leesei @lzjqsdd
