### ISSUE TITLE
page.per_page is empty

### ISSUE THREAD

**Issue by mamboer** [hexojs/hexo#2040]
Hexo should provide a variable `per_page` for the `Home` index page according to the docs described here https://hexo.io/docs/variables.html.

But in my hexo site, `per_page` is empty while the other pager variables are fine.
## Environment Info

Node version(`node -v`)

```
v5.12.0
```

`_config.yml`

```
# generator-index
index_generator:
  per_page: 24
  order_by: -date

# tag generator
## https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 24

# Pagination
## Set per_page to 0 to disable pagination
per_page: 24
pagination_dir: page
...
```

Swig `Template`

```
<script>
App.pager = {
    current: {{page.current}},
    next: {{page.next}},
    total: {{page.total}},
    size: {{page.per_page}}
};
</script>
...
```
## BUG
- page.per_page is empty in home page.
