### ISSUE TITLE
分页显示不正常，显示__('next') »或« __('prev')，而不是上一页，下一页

### ISSUE THREAD

**Issue by hiquanta** [hexojs/hexo#2043]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v6.2.1
```

Your site `_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Ω
subtitle:
description:
author: Ω
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://hiquanta.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD:HH:mm
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

duoshuo_shortname: hiquanta

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  #elfwalk改为你的github用户名
  repository: git@github.com:hiquanta/hiquanta.github.io.git
  branch: master

...
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
hexo: 3.2.2
hexo-cli: 1.0.2
os: Windows_NT 6
http_parser: 2.7
node: 6.2.1
v8: 5.0.71.52
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug
