### ISSUE TITLE
manifest.json missing gcm_sender_id after hexo generate

### ISSUE THREAD

**Issue by baivong** [hexojs/hexo#2080]
## Environment Info

Node version(`node -v`)

```
v6.3.1
```

Your site `_config.yml`

```
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'manifest.json'

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD-MM-YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

### https://github.com/alexbruno/hexo-generator-json-content
jsonContent:
  meta: false
  keywords: false # (english, spanish, polish, german, french, italian, dutch, russian, portuguese, swedish)
  pages:
    title: true
    slug: true
    date: true
    updated: true
    comments: false
    path: true
    link: false
    permalink: false
    excerpt: true
    keywords: false # but only if root keywords option language was set
    text: false
    raw: false
    content: false
    thumbnail: true
  posts:
    title: true
    slug: true
    date: true
    updated: true
    comments: false
    path: true
    link: false
    permalink: false
    excerpt: true
    keywords: false # but only if root keywords option language was set
    text: false
    raw: false
    content: false
    categories: true
    tags: true
    thumbnail: true

# https://github.com/unhealthy/hexo-all-minifier
html_minifier:
  enable: false
css_minifier:
  enable: false
js_minifier:
  enable: false
  mangle: false
image_minifier:
  enable: false

## Themes: https://hexo.io/themes/
theme: hueman
```

Your theme `_config.yml`

```
# Plugins
plugins:
    fancybox: true # options: true, false
    scrollLoading: true # options: true, false
    google_analytics: UA-82062909-1 # enter the tracking ID for your Google Analytics
    baidu_analytics: # enter Baidu Analytics hash key
```

Plugin version(`npm ls --depth 0`)

```
hexo-site@0.0.0 H:\baivong.github.io
+-- hexo@3.2.2
+-- hexo-admin@2.1.0
+-- hexo-all-minifier@0.0.14
+-- hexo-browsersync@0.2.0
+-- hexo-deployer-git@0.2.0
+-- hexo-front-matter-excerpt@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.0
+-- hexo-generator-json-content@2.1.3
+-- hexo-generator-sitemap@1.1.2
+-- hexo-generator-tag@0.2.0
+-- hexo-pagination@0.1.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
+-- hexo-server@0.2.0
`-- hexo-toc@1.0.1
```

---
## For BUG

Original source

``` json
{
  "name": "Zzbaivong's blog",
  "short_name": "Zzbaivong",
  "start_url": "/",
  "gcm_sender_id": 73651230721,
  "display": "standalone",
  "icons": [{
    "src": "/android-chrome-192x192.png",
    "sizes": "192x192",
    "type": "image/png"
  }, {
    "src": "/android-chrome-512x512.png",
    "sizes": "512x512",
    "type": "image/png"
  }],
  "theme_color": "#ffffff"
}
```

After hexo generates

``` json
{"name":"Zzbaivong","icons":[{"src":"/android-chrome-192x192.png","sizes":"192x192","type":"image/png"},{"src":"/android-chrome-512x512.png","sizes":"512x512","type":"image/png"}],"theme_color":"#ffffff","display":"standalone"}
```

Why `gcm_sender_id`, `short_name`, `start_url`  have been removed?
