### ISSUE TITLE
Can't change the theme, always use landscape

### ISSUE THREAD

**Issue by Albert-Gao** [hexojs/hexo#2107]
## Environment Info

Node version(`node -v`)

```
v4.5.0
```

Your site `_config.yml`

```
theme: Hacker
```

Your theme `_config.yml`

```
menu:
  Home: /
  Archives: /archives

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: false
disqus_shortname: 

# google analytics
googleTrackId: 

```

Plugin version(`npm ls --depth 0`)

```
hexo-site@0.0.0 /Users/albertgao/hexo
├── hexo@3.2.2
├── hexo-browsersync@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-migrator-wordpress@0.1.2
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-jade@0.3.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0

```
## For BUG
- Now matter how I change the `theme` option in the _config.yml, it always use the landscape theme
- If I delete the `landscape` folder in the `theme` folder, I will get a blank page after generating
- I fixed this bug by changing the name of the theme folder to `landscape`, but it is lame, how to fix this?
