### ISSUE TITLE
Where is the global asset file paths for CSS & JS files?  I cannot let Hexo ignore the JS file, such as angular.js, which caused error

### ISSUE THREAD

**Issue by kenspirit** [hexojs/hexo#2118]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v6.4.0
```

Your site `_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Thinking in Crowd / 鹄思乱想
subtitle: Swan flying in the immense sky
description:
author: 鹄思乱想
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.thinkingincrowd.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Disqus
disqus_shortname: thinkingincrowd

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pacman

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  repo:
    github: git@github.com:kenspirit/kenspirit.github.io.git,master

```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 
├── hexo@3.2.2
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```

## For question

Where should my personal CSS and JS files be located?  Even if I place them in the css/ js/ folder under source/ , it's kept processed.  The angular.js file it processed kept complaining below error.  How can I config hexo to ignore those CSS and JS files?

FATAL (unknown path) [Line 3613, Column 27]
  expected variable end
