### ISSUE TITLE
after set post_asset_folder: true and root: /xxxx/，the image url was wrong

### ISSUE THREAD

**Issue by allenn** [hexojs/hexo#2123]
## Environment Info

Node version(`node -v`)

```
v6.4.0
```

site `_config.yml`

```
# Hexo Configuration
···
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Allen's Blog
subtitle:
description:
author: ""
email: ""
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://pages.xxx.com/xxx/blogs
root: /xxx/blogs/
permalink: articles/:year-:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape
#theme: yilia
# Deployment
## Docs: https://hexo.io/docs/deployment.html
```

Your theme `_config.yml`

```
# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
```

Plugin version(`npm ls --depth 0`)

```
D:\workspaces\hexo-blogs>npm ls --depth 0
hexo-site@0.0.0 D:\workspaces\hexo-blogs
+-- hexo@3.2.2
+-- hexo-deployer-git@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.0
+-- hexo-generator-sitemap@1.1.2
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.2.0
```
## For BUG

After set post_asset_folder: true and root: /xxxx/，the image url was wrong, ref images in post like this

```
{% asset_img export_cert_3.png vbooking.cer %}

# producted URL
<meta property="og:image" content="http://pages.xxx.com/xxx/blogs/xxx/blogs/articles/2016-08/resolve-java-app-ssl-error/export_cert_3.png">

```
