### ISSUE TITLE
hexo server not work

### ISSUE THREAD

**Issue by showzeng** [hexojs/hexo#2124]
## Environment Info

Node version(`node -v`)
```
v6.4.0
```

Your site `_config.yml`
```
# Site
title: showzeng's blog
subtitle: 
description: 
author: showzeng
language: en
timezone:

# URL
url: http://blog.showzeng.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md 
default_layout: post
titlecase: false 
external_link: true 
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: tranquilpeak

# Deployment
deploy:
  type: git
  repo: https://github.com/showzeng/showzeng.github.io
  branch: master
  message:

# duoshuo
duoshuo_shortname: showzeng

# algoliasearch plugins
plugins:
  - hexo-algoliasearch

# algolia config
algolia:
  appId: "*****"
  apiKey: "********"
  adminApiKey: "*********"
  chunkSize: 5000
  indexName: "showzeng's blog"
  fields:
    - title
    - date
    - permalink
    - thumbnailImageUrl
    - tags
    - categories
    - excerpt
    - excerpt:strip
```

Your theme `_config.yml`
```
# Image directory (default: images)
image_dir: assets/images

# Sidebar Configuration
sidebar:
    menu:
        home:
            title: global.home
            url: /
            icon: home
        categories:
            title: global.categories
            url: /all-categories
            icon: bookmark
        tags:
            title: global.tags
            url: /all-tags
            icon: tags
        archives:
            title: global.archives
            url: /all-archives
            icon: archive
        search:
            title: global.search
            url: /#search
            icon: search
            # `open-algolia-search` classes are used to open algolia search modal
            class: open-algolia-search
        about:
            title: global.about
            url: /#about
            icon: question
    author_links:
        github:
            title: global.github
            url: https://github.com/showzeng
            icon: github

# Header configuration
header:
    right_link:
        url: /#about
        icon:
        class:

# Author
author:
    email: kingstageshow@gmail.com
    location: China
    picture: "http://7xtt0k.com1.z0.glb.clouddn.com/avatar.png"

# Customization
sidebar_behavior: 1
clear_reading: true
thumbnail_image: true
thumbnail_image_position: right
auto_thumbnail_image: true
cover_image: cover.jpg
favicon: favicon-small.png
image_gallery: true
archive_pagination: true
category_pagination: true
tag_pagination: true

# Integrated services
duoshuo_shortname: showzeng
google_analytics_id: **-*****-***
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 /home/showzeng/blog
├── hexo@3.2.2
├── hexo-algolia@0.2.0
├── hexo-algoliasearch@0.2.1
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```

## For question
Before I configured  the algoliasearch, the command `hexo server` is all right. But after executing `hexo algolia`, using `hexo server` with getting this hint.

> showzeng@showzeng:~/blog$ hexo server

Usage: hexo `<command>`

Commands:
...
 
I don't know what's wrong with it. I tried  `npm uninstall hexo-server` then installed the hexo-server again with `npm install hexo-server --save`, even I rebuilded a file with `hexo init` and got the same problem.
