### ISSUE TITLE
能否hexo deploy 时指定git账户

### ISSUE THREAD

**Issue by imfenghuang** [hexojs/hexo#2125]
hexo deploy默认使用全局的git user.name user.email，那么请问能否hexo deploy 时带上临时指定的git账户  或者 在_config.yml指定git账户 使得push时与全局git账户区分开

**Comment by NoahDragon** [comment]
可以用脚本实现，在hexo deploy之前将全局user更改，deploy完成之后再将user改回。

**Comment by NoahDragon** [comment]
```
# You can use this:
deploy:
  type: git
  repo: <repository url>
  branch: [branch]
  message: [message]
  name: [git user]
  email: [git email]
  extend_dirs: [extend directory]
```
