### ISSUE TITLE
hexo s failed, generate error

### ISSUE THREAD

**Issue by netqyq** [hexojs/hexo#2160]
> before you submit your issue, please delete all the example code in template
## Environment Info

Node version(`node -v`)

```
hexo: 3.2.0
hexo-cli: 1.0.1
os: Darwin 14.1.1 darwin x64
http_parser: 2.6.0
node: 5.5.0
v8: 4.6.85.31
uv: 1.8.0
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 47
openssl: 1.0.2e
```

Your site `_config.yml`

```
# Hexo Configuration
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: CalmOps
subtitle:
description: yongqiang.qu blog
author: YongQiang Qu
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://calmops.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```

Your theme `_config.yml`

```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)

```
├── hexo@3.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```
## For BUG
- BUG description
  can not start server , 
- the way to reproduce
- log with hexo <command> --debug
  $hexo s
  INFO  Start processing
  FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
  Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL
    at Object.exports.prettifyError (/data/node/calmops/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/data/node/calmops/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/data/node/calmops/node_modules/nunjucks/src/environment.js:326:21)
    at /data/node/calmops/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/data/node/calmops/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd](/data/node/calmops/node_modules/hexo/lib/hexo/post.js:253:16)
    at /data/node/calmops/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)
  FATAL (unknown path)
  SyntaxError: Unexpected token ILLEGAL
  Template render error: (unknown path)
  SyntaxError: Unexpected token ILLEGAL
    at Object.exports.prettifyError (/data/node/calmops/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/data/node/calmops/node_modules/nunjucks/src/environment.js:468:27)
    at Obj.extend.renderString (/data/node/calmops/node_modules/nunjucks/src/environment.js:326:21)
    at /data/node/calmops/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/data/node/calmops/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd](/data/node/calmops/node_modules/hexo/lib/hexo/post.js:253:16)
    at /data/node/calmops/node_modules/hexo/lib/hexo/render.js:63:19
    at tryCatcher (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate](/data/node/calmops/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback](timers.js:383:17)
## the file cause the error

https://github.com/Chaniel/nginx-docs/blob/master/nginx-starter.md
## For question

just push question
## For feature request

just push feature request
