### ISSUE TITLE
No luck with checkboxes from GFM markdown

### ISSUE THREAD

**Issue by JLKM** [hexojs/hexo#2161]
Thank you for Static Site Generators, that are going to rock the world of web-publishing. Thank you even more for Hexo, which  is keeping Node.js as an important part of the game.

Almost every day I discover new, useful features in Hexo. But how come, it's impossible for me to render a checkbox/task list/todo list with GitHub Flavoured Markdown...

Plugins with no luck:

1.
- [ ] hexo-renderer-marked
setting in root _config.yml:
```
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
```
*No checkbox*

...Have also tried with smartLists: false - *still no checkbox*

2.
- [ ] hexo-renderer-markdown-it
setting in root _config.yml for GFM:
```
markdown: 'default'
```
*No checkbox*

3.
- [ ] hexo-renderer-kramed

*Same story*

A switch between landscape og hueman as theme means no change, either. Yelee, though, manage to show the checkboxes. But this is done with use of javascript after load.

I would really like to have the checkboxes once and for all in the html. It works right here on GitHub. What am I missing?

Thank you again - all contributors - for an amazing tool.
