### ISSUE TITLE
YAML Front matter comments stripped

### ISSUE THREAD

**Issue by timpulver** [hexojs/hexo#2162]
My `post.md` scaffold contains comments which make it clear how to use the variables and what kind of variable it is. When generating a new empty post via `hexo new post "Post Title"` all comments are stripped. Is there a way to keep the comments?

post.md scaffold:  

```
---
title: {{ title }}
date: {{ date }}
# Add more images if needed, e.g. filename: foo.jpg, caption: Some image description
images:
  - filename:
    caption:
  - filename:
    caption:
---
```

Running `hexo new post "Post Title"` strips all comments starting with `#`.
