### ISSUE TITLE
When using "{% pullquote %}" inside "{% blockquote %}", Hexo will create a extra <br /> between <p>

### ISSUE THREAD

**Issue by vamworks** [hexojs/hexo#2204]
> before you submit your issue, please delete all the example code in template
## Environment Info

Node version(`node -v`)

```
v6.6.0
```

Your site `_config.yml`

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: VamWorks
subtitle:
description:
author: Vam Zhang
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://vamworks.com
root: /
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# add caption for iamges
image_caption:
  enable: true #false to disable
  class_name: #if you wanna customize the style for the caption,you can assign a class name, default is 'image-caption'

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: aws-s3
  bucket: vamworks.com
  region: ap-northeast-2

```

Your theme `_config.yml`

```
# Hexo Configuration
# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

```

Plugin version(`npm ls --depth 0`)

```
hexo-site@0.0.0 /Zhang/Vam/Website/vamworks.github.io
├── hexo@3.2.2
├── hexo-deployer-aws-s3@0.1.1
├── hexo-deployer-ftpsync@0.1.1
├── hexo-deployer-git@0.2.0
├── UNMET DEPENDENCY hexo-deployer-s3@^0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-image-caption@0.1.1
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```
## For BUG
- BUG description: When using "{% pullquote %}" inside "{% blockquote %}", Hexo will create a extra <br /> between <p>.  It is normal when using "{% pullquote %}" directly.
