### ISSUE TITLE
Can't make skip_render to work

### ISSUE THREAD

**Issue by oncletom** [hexojs/hexo#2207]
## Environment Info

Node version(`node -v`)

```
v6.5.0
```

Your site `_config.yml`

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: ~
subtitle: ~
author: ~
language: en-GB
timezone: Europe/London

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://oncletom.io/talks
root: /talks/
permalink: :year/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: ""
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - "**/*/{slides,images}/*"

# Writing
new_post_name: :year/:title.md # File name of new posts
default_layout: talk
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: true
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ../node_modules/hexo-theme
layout: talks

nunjucks:
  autoescape: true
  throwOnUndefined: false
  watch: false


archive_generator:
  per_page: 0
  yearly: false
  monthly: false
  daily: false

```

Plugin version(`npm ls --depth 0`)

```
talks@1.1.0 /Users/thomaspa/Projects/talks
├── babel@6.5.2
├── babel-preset-es2015@6.16.0
├── babel-preset-stage-0@6.16.0
├── css.oncletom.io@2.5.0
├── gh-pages@0.11.0
├── hexo@3.2.2
├── hexo-cli@1.0.2
├── hexo-generator-index@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-less@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-server@0.2.0
└── hexo-theme-oncletom@1.1.0
```
## For question

I have a structure like this:

``` bash
source
└── _posts
    └── :year
        ├── :post-asset-folder
        │   ├── _outline.md
        │   ├── images
        │   │   └── **.png
        │   └── slides
        │       ├── slide01.md
        │       ├── slide02.md
        │       ├── slide03.md
        │       ├── slide04.md
        │       └── slide05.md
        └── :post.md
```

I can't manage to get all the `.md` files in the `./slides` to be excluded.
I have tried various combinations of `skip_render` setting but no luck so far :-(

Any idea or suggestion? Thanks :-)
