### ISSUE TITLE
Use NPM public registry in hexo

### ISSUE THREAD

**Issue by JadyLiu** [hexojs/hexo#2246]
> before you submit your issue, please delete all the example code in template

I export a javascript library from npm public registry, and added this library in source directory of root. 
Also, including in _config.yml, for example:
```
include: mylibrary/**
```

hexo --debug did not give any issues. 

The error message is below when trying to run hexo server:

`FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 29, Column 1]
  unexpected token: //
    at Object.exports.prettifyError (/Users/lius2/serverless-express-test/website/blog/node_modules/nunjucks/src/lib.js:34:15)
    at Obj.extend.render (/Users/lius2/serverless-express-test/website/blog/node_modules/nunjucks/src/environment.js:469:27)
    at Obj.extend.renderString (/Users/lius2/serverless-express-test/website/blog/node_modules/nunjucks/src/environment.js:327:21)
    at /Users/lius2/serverless-express-test/website/blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/promise.js:77:14)
    at Tag.render (/Users/lius2/serverless-express-test/website/blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/lius2/serverless-express-test/website/blog/node_modules/hexo/lib/hexo/post.js:253:16)
    at /Users/lius2/serverless-express-test/website/blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/Users/lius2/serverless-express-test/website/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
    at tryOnImmediate (timers.js:550:5)
    at processImmediate [as _immediateCallback] (timers.js:529:5)`

Please help 
Jady

## Environment Info

Node version(`node -v`)
```
v6.3.1
```

Your site `_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: My Blog
subtitle: blog
description: New Blog 
author: Jady Liu
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://atcloud.me
root: /
permalink: :year/:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

include: mylibrary/**

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  Page1: page1
tag_map:
  tag1

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```
