### ISSUE TITLE
deploy 成功，github 中文件也有更新，但是 *.githut.io 中文章列表并没有显示。

### ISSUE THREAD

**Issue by JChehe** [hexojs/hexo#2261]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v6.5.0
```

Your site `_config.yml`
```
deploy:
  type: git
  repo: git@github.com:JChehe/jchehe.github.io.git
  branch: master
  # message: [message]
...
```
