### ISSUE TITLE
Markdown option breaks:false is ignored from _config.yml

### ISSUE THREAD

**Issue by agirorn** [hexojs/hexo#2306]
## Environment Info

Node version(`node -v`)
```
v4.5.0
```

Your site `_config.yml`
```
# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
```

Your theme `_config.yml`
```
# Hexo Configuration
```

Plugin version(`npm ls --depth 0`)
```
├── hexo@3.2.2
├── hexo-browsersync@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
├── lodash@4.17.2
├── nodemon@1.11.0
└── yaml-cat@0.3.2
```

## For BUG

- Markdown option breaks:false is ignored from `_config.yml`
line one
Line two

Should be rendered as one line but is separated with a _br_ tag in the middle.
- Markdown option breaks:false works if it is added to the front matter of each markdown file.
