### ISSUE TITLE
hexo deploy 时指定git账户

### ISSUE THREAD

**Issue by zewenwang** [hexojs/hexo#2343]
前提: `~/.gitconfig`文件中设置的全局参数
```
[user]
	name = global_name
	email = global_email
```

然后在_config.yml中设置
```
deploy:
- type: git
  repo: github_repo
  branch: [branch]
  name: github_name
  email: github_email
- type: git
  repo: coding_repo
  branch: [branch]
  name: coding_name
  email: coding_email
```

执行hexo deploy提交后，查看github和coding，commit的作者是 global_name global_email
