### ISSUE TITLE
Template render error: (unknown path)

### ISSUE THREAD

**Issue by davewx** [hexojs/hexo#2384]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
?
```

Your site `_config.yml`
```
...
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: David Earl Johnson, MSW, LICSW
subtitle: 
description:
author: David Earl Johnson, MSW, LICSW
language: en
timezone: America/Chicago

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://davemsw.com ## not deployed
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: true # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```

Your theme `_config.yml`
```
# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

...
```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 C:\Users\Dave\work\hexo
+-- hexo@3.2.2
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-migrator-wordpress@0.1.2
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
`-- hexo-server@0.2.0

```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

## For question

Hexo newby, new install, error message in the subject line. One of the above items I don't know 
where to get. Full error message below:
```bash
 hexo generate
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 1, Column 294]
  expected variable end
    at Object.exports.prettifyError (C:\Users\Dave\work\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (C:\Users\Dave\work\hexo\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (C:\Users\Dave\work\hexo\node_modules\nunjucks\src\environment.js:327:21)
    at C:\Users\Dave\work\hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (C:\Users\Dave\work\hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\Users\Dave\work\hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\Users\Dave\work\hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
FATAL (unknown path) [Line 1, Column 294]
  expected variable end
Template render error: (unknown path) [Line 1, Column 294]
  expected variable end
    at Object.exports.prettifyError (C:\Users\Dave\work\hexo\node_modules\nunjucks\src\lib.js:34:15)
    at new_cls.render (C:\Users\Dave\work\hexo\node_modules\nunjucks\src\environment.js:469:27)
    at new_cls.renderString (C:\Users\Dave\work\hexo\node_modules\nunjucks\src\environment.js:327:21)
    at C:\Users\Dave\work\hexo\node_modules\hexo\lib\extend\tag.js:66:9
    at Promise._execute (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:481:18)
    at new Promise (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:77:14)
    at Tag.render (C:\Users\Dave\work\hexo\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (C:\Users\Dave\work\hexo\node_modules\hexo\lib\hexo\post.js:253:16)
    at C:\Users\Dave\work\hexo\node_modules\hexo\lib\hexo\render.js:65:19
    at tryCatcher (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\Dave\work\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```
