### ISSUE TITLE
hexo 没法部署到 coding 的仓库,报错信息如下

### ISSUE THREAD

**Issue by yusmile** [hexojs/hexo#2390]
同时部署到coding和github,github成功，出现这样提示
![](http://upload-images.jianshu.io/upload_images/4542536-c3ce9495629d7911.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
折腾了两天没法解决，请问高手怎么办呢？

**Comment by yusmile** [comment]
@NoahDragon  请问这个是什么错误，应该怎么解决呢？

**Comment by yusmile** [comment]
是不是部署公钥这里出错了呢？
>admin@admin-PC MINGW64 /d/hexo
$ ssh-keygen -t rsa -C "182036669@qq.com" -f ~/.ssh/coding_rsa
Generating public/private rsa key pair.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /c/Users/admin/.ssh/coding_rsa.
Your public key has been saved in /c/Users/admin/.ssh/coding_rsa.pub.
The key fingerprint is:
SHA256:Our+bMt5ZS3bIf7yCEfPswAPgagnJG7chfeKuRRSxyU 182036669@qq.com
The key's randomart image is:
+---[RSA 2048]----+
|     E .         |
|    o.o.         |
|. .o.=. .        |
|ooo.+ .  .       |
| =oo.  .S ..     |
|. .o+ .. ==oo    |
|   + .o .++=+.   |
|  . .+.o.o+o.o   |
|   ++o*o  .++    |
+----[SHA256]-----+

admin@admin-PC MINGW64 /d/hexo
$ ssh -T git@git.coding.net
The authenticity of host 'git.coding.net (59.56.27.71)' can't be established.
RSA key fingerprint is SHA256:jok3FH7q5LJ6qvE7iPNehBgXRw51ErE77S0Dn+Vg/Ik.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'git.coding.net,59.56.27.71' (RSA) to the list of known hosts.
Permission denied (publickey).

**Comment by NoahDragon** [comment]
是密钥的问题，ssh无法连接。

**Comment by yusmile** [comment]
@NoahDragon 最后统一用1个公钥，问题暂时解决了，谢谢前辈。但是还是不知道尝试双布置的设置哪里错误，

**Comment by NoahDragon** [comment]
可以如下配置Deployer来实现多部署：
```
deploy:
  - type: git
    repo: git@git.coding.net:AbnerChou/abnerchou.git
    branch: gh-pages
  - type: git
    repo: git@github.com:NoahDragon/noahdragon.git
    branch: gh-pages
```
