### ISSUE TITLE
上传新的文章出错

### ISSUE THREAD

**Issue by fly7632785** [hexojs/hexo#2415]
my theme site `_config.yml`
```
# Hexo Configuration
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/avatar_corner.png"
    high_res_favicon: "/img/avatar_corner.png"
    apple_touch_icon: "/img/avatar_corner.png"
    keywords: "jafir"

# Jump Links Settings
url:
    rss:
    daily_pic: "#"
    logo: "#"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan:
      - "Hi, welcome to Jafir's blog !"
      - "I will share something nice with you !"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
#    button_color: "#757575"
    button_color: "#FF4081"
    android_chrome_color: "#0097A7"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true

# Reading experience
# markdown available value:
#     Material | Github | Plain
reading:
    markdown: Github
    entry_excerpt: 80
    code_highlight: solarized-white

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar_corner.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    #upyun_logo: "/img/upyun_logo.png"
    random_thumbnail: "/img/random/material-"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: "522648467@qq.com"
    facebook:
    twitter:
    googleplus:
    weibo: 
    instagram: 
    tumblr: 
    github: "https://github.com/fly7632785"
    linkedin: 
    zhihu: 
    bilibili: 
    telegram: 

# SNS Share Switch
sns_share:
    twitter: false
    facebook: false
    googleplus: false
    weibo: true
    linkedin: false
    qq: true
    telegram: false

# Sidebar User Dropdown
dropdown:
    Email Me:
        link: "mailto:522648467@qq.com"
        icon: email
    Jianshu:
        link: "http://www.jianshu.com/u/d234d1569eed"
        icon: date_range
    Github:
        link: "https://github.com/fly7632785"
        icon: group_work

# Sidebar Categories Switch
sidebar_categories: false

# Pages Menu
pages:
    About:
        link: "/about"
        icon: person

# Qrcode for redirect at other device
qrcode: true

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value of "use":
#     duoshuo | disqus
comment:
    use: "duoshuo"
    shortname: "jafir"
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key:
    path: search.xml
    fiels: post

# Leancloud Views
leancloud:
    enable: false
    app_id: heyyFcCvpdcSOMYIbLXuzolQ-gzGzoHsz
    app_key: yHzjqXMIjiXRLuFbXzB0Uy17
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
```

Your theme `_config.yml`
```
# Hexo Configuration
...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.1.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.1.1
├── hexo-renderer-marked@0.2.10
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.1.3
```

## For question
我发布一篇新文章的时候出错了，前两个月都好好的，也一直在用。现在不行了，我看了一下官网，是不是更新了一些东西，导致没有兼容？错误日志如下

![](http://upload-images.jianshu.io/upload_images/1311457-b6b11c2b2542bf66.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
