### ISSUE TITLE
after_post_render filter don't always run ?

### ISSUE THREAD

**Issue by tea3** [hexojs/hexo#2475]
> before you submit your issue, please delete all the example code in template

## Environment Info

Node version(`node -v`)
```
v6.9.4
```

Your site `_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

```

Your theme `_config.yml`
```
# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 /Users/username/Desktop/web/hexo694
├── hexo@3.2.2
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0
```

## For question

[after_post_render filter](https://hexo.io/api/filter.html#after-post-render)  don't always run ?  I want to save temporary data when after_post_render is executed.  However, although it succeeds in hexo@3.1, it does not go well in hexo@3.2. 

Is there a good way to do it in hexo@3.2 ?

`themes/landscape/scripts/fancybox.js`
```
// This is a sample script that saves temporary data with after_post_render.

hexo.extend.filter.register('after_post_render', function (post) {

  console.log("[after_post_render] Do this function run always ?");
  this.config.tmpData = "sample temporary data";
  
  return new Promise(function(resolve , reject){
    resolve(post);
  });
} , {async: true});


hexo.extend.filter.register('after_generate', function () {
  console.log("[after_generate] this.config.tmpData = " + this.config.tmpData);
});
```

Running with hexo@3.2 will not work.

```
$ hexo clean
$ hexo s
INFO  Start processing
[after_post_render] Do this function run always ?
[after_generate] this.config.tmpData = sample temporary data
^CINFO  Bye!
$ hexo s
[after_generate] this.config.tmpData = undefined
```

hexo@3.1 works well.

```
$ hexo clean
$ hexo s
INFO  Start processing
[after_post_render] Do this function run always ?
[after_generate] this.config.tmpData = sample temporary data
^CINFO  Bye!
$ hexo s
[after_post_render] Do this function run always ?
[after_generate] this.config.tmpData = sample temporary data
```

I'm publishing the following plugin.

- [hexo-generator-amp](https://github.com/tea3/hexo-generator-amp)
- [hexo-related-popular-posts](https://github.com/tea3/hexo-related-popular-posts)

I'd like to use these plugins to store temporary data in hexo@3.2 , please advise.
