### ISSUE TITLE
Hexo doesn't generate picture in public folder

### ISSUE THREAD

**Issue by chewenkai** [hexojs/hexo#2476]
# Environment Info

Node version(`node -v`)
```
v7.6.0
```

Your site `_config.yml`
```
# Hexo Configuration
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
## http://yoursite.com
url: https://chewenkai.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: /home/kevin/Dropbox/source/
public_dir: public 
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
encrypt:
    enable: trues

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia

# Yilia theme setting
jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: true
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:chewenkai/chewenkai.github.io.git
  branch: master
...
```

Your theme `_config.yml`
```
# Hexo Configuration
# Header
title: 文凯的小屋                           #网站标题
subtitle: Let's blog the world            #副标题
description: 车文凯的博客 文凯的小屋 车文凯 Kevin         #网站描述，给搜索引擎看的
author: Kevin               #网站拥有者，同样给搜索引擎看的
#language:             #网站语言
email: chewenkaich@gmail.com                #你的个人联系邮箱
#timezone:             #时区

menu:
  主页: /                 #需要添加的话
  所有文章: /archives     #格式就是
#  F2E: /categories/F2E    #名字: 目录

# SubNav
subnav:
  github: "https://github.com/chewenkai"
  # weibo: "http://weibo.com/litten225"
  rss: /atom.xml
  # zhihu: "https://www.zhihu.com/people/che-wen-kai-19/"
  #douban: "#"
  #segmentfault: "#"
  mail: "mailto:chewenkaich@gmail.com"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: 'more'
show_all_link: '展开全文'
fancybox: true
mathjax: true

# 打赏
reward_type: 1
reward_wording: '不敢当'
alipay: /assets/img/alipay.jpg
weixin: /assets/img/weixin.jpg

# 是否在新窗口打开链接
open_in_new: true

# Miscellaneous
baidu_analytics: 'a30844fa2bcbce0a9e001fe06cefeddf'
google_analytics: false
favicon: /assets/img/favicon.ico

#你的头像url
avatar: "https://dn-coding-net-production-static.qbox.me/9ae6d768-d8dd-442e-bbaa-0599aebbe0a8.jpg"

#是否开启分享
share_jia: true

mobile:
  social: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: "litten-hexo"

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false

smart_menu:
  innerArchive: '所有文章'
  friends: false
  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

...
```

Plugin version(`npm ls --depth 0`)
```
hexo-vanilla-site@0.0.0 ~/hexo-vanilla-site
├── hexo@3.2.2
├── hexo-asset-image@0.0.3 (git+https://github.com/CodeFalling/hexo-asset-image.git#9322771081f5789f1694e038d158957cf3261110)
├── hexo-blog-encrypt@1.1.12
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.0
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-inject@1.0.0
├── hexo-math@3.0.2
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
└── hexo-server@0.2.0

```

## For BUG

- BUG description
Hello there, I very appreciate the Hexo project, it's very cool and useful. But I am encountering a problem after I set the source_dir out of the blog root path. Hexo doesn't generate picture anymore. This problem has been proposed in #1988. I really need to move the source dir to dropbox dir then I can edit md file in my phone.
- the way to reproduce
set the source_dir out of the blog root path
- log with hexo <command> --debug
None
