### ISSUE TITLE
generate wrong file when  filename contain '?'

### ISSUE THREAD

**Issue by broven** [hexojs/hexo#2481]
## Environment Info

Node version(`node -v`)
```
v7.4.0
```

Your site `_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: meta
subtitle: mysubtitle
description:
author: meta
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: apollo

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: myrepo
  branch: master

...
```

Your theme `_config.yml`
```
menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/u/5446428128
    GitHub: https://github.com/broven
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:

# Analytics
# google-analytics:
ga:

# Copyright Infomation
startyear: 2017

```

Plugin version(`npm ls --depth 0`)
```
hexo-site@0.0.0 /Users/zhangyao/Documents/git/blog
├── dateformat@2.0.0
├── espower-loader@1.2.0
├── file-exists@3.0.2
├── hexo@3.2.2
├── hexo-browsersync@0.2.0
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-jade@0.3.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.1
├── hexo-server@0.2.0
├── intelli-espower-loader@1.0.1
├── issue2essay@0.0.6
├── mocha@3.2.0
└── power-assert@1.4.2
```

## For BUG

- BUG description
- the way to reproduce
- log with hexo <command> --debug

## For BUG

- BUG description

- the way to reproduce
   
   create a new post file, and name it with 'xx?.md'. for example `hello?.md`  and title it 'hello'
   then run `hexo clean&& hexo g`
  and you will get a wrong generated file 
![screen shot 2017-04-02 at 10 43 47 pm](https://cloud.githubusercontent.com/assets/12854613/24588185/ee677fb6-17f5-11e7-89de-30970e085278.png)
I think this can reproduce this bug, my English is limited, if can't I can make a demo for it
