### ISSUE TITLE
index.ejs is not used for homepage

### ISSUE THREAD

**Issue by thom4parisot** [hexojs/hexo#252]
Hello,

I have both `archive.ejs` and `index.ejs` for my theme.  
Problem is on `/` path, the `archive.ejs` is loaded, not the `index.ejs` one (the doc lets thinking `index.ejs` is the _home page_).

I have this config:

``` yml
# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 0
```
