### ISSUE TITLE
Is there a way to not ignore _ prefixed files?

### ISSUE THREAD

**Issue by jennifer-mann** [hexojs/hexo#2536]
## Environment Info

Node version: 6.5.0
Hexo version: 3.3.1

## Question

In the documentation it states:

> Hexo ignores hidden files and files or folders whose names are prefixed with `_` (underscore) - except the `_posts` folder. 

Is there anyway to override this ignore behavior? I have an `_.md` file that I literally want to be generated as `_.html` in my public folder (to document an `_` API command in our documentation). Thanks!

**Comment by NoahDragon** [comment]
In the config file, you could add include/exclude file/folder:
```yaml
# Include/Exclude Files/Folders
include:
  - .nojekyll
exclude:
  - .DS_Store
```

It works when generating files, however, I'm not if the include file could be rendered. Could you please help me to confirm?
