### ISSUE TITLE
[Question] net::ERR_FILE_NOT_FOUND for all assets (CSS, Images, ...)

### ISSUE THREAD

**Issue by mnlbox** [hexojs/hexo#2567]
## Environment Info

Node version(`node -v`):
v6.10.2
Your site `_config.yml` (Optional):
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```
Your theme `_config.yml` (Optional): 
I used default theme (landscape)

Hexo and Plugin version(`npm ls --depth 0`): 
├── hexo@3.3.5
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@3.0.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0

## Question description

I try create simple helloword with Hexo with following commands:
```
sudo npm install -g hexo-cli
hexo init code-blog
cd code-blog
sudo npm install
hexo server
```
And anything works well. But when I generate site with `hexo generate` and run `/public/index.html` it's assets (CSS, Image, ...) not loaded like below:
![hexo error](https://cloud.githubusercontent.com/assets/25859075/26114583/e1c34246-3a72-11e7-95be-a7e905f290cc.png)

I also try `hexo clean` and run `hexo generate` again but it's not working. Can you help me to fix this?
