### ISSUE TITLE
the content deployed to github repo is different with that in public

### ISSUE THREAD

**Issue by thomasyimgit** [hexojs/hexo#2585]
## Environment Info

Node version(`node -v`): v7.7.1

Your site `_config.yml` (Optional):
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Collecting Dots
subtitle: Chang's Blog
description:
author: Chang Yan
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://thomasyimgit.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: anatole

archive_generator:
  per_page: 0  
  yearly: false
  monthly: false
  daily: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:thomasyimgit/thomasyimgit.github.io.git
  branch: master
  name: thomasyimgit  
  email: thomasyim94@gmail.com

```

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For question

Hi there, after all the preparing stuff and typed `hexo deploy -g`, I found that in my github repo, I can only find the following folders, without an `index.html` obviously. I wonder where all the rest files went? Is there anything wrong with my config.yml file?
![image](https://cloud.githubusercontent.com/assets/13282699/26529144/66613ca0-43ed-11e7-9253-0b62e733d610.png)
