### ISSUE TITLE
最新版hexo在deploy之后会收到一封GitHub pages不支持jekyll主题的邮件

### ISSUE THREAD

**Issue by lxh56b** [hexojs/hexo#2588]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/lxh56b/lxh56b.github.io.git
  brunch: master
```
Your theme `_config.yml` (Optional): 
```
# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
```
Hexo and Plugin version(`npm ls --depth 0`): 
```
├── hexo@3.3.7
├── hexo-deployer-git@0.3.0
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-pug@0.0.5
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0
```
## For BUG

deploy之后显示404，并且收到邮件说GitHub pages 不支持Jekyll theme，邮件原文：
you are attempting to use a jekyll theme, "landscape", which is not supported by github pages. Please visit https://pages.github.com/themes for a list of supported themes.
## For question

是不是我少安装了插件？
之前在PC上用3.3.1版本，并没有出现这个问题，换到mac上安装3.3.7就出现了这个问题
