### ISSUE TITLE
Cannot find second page of posts in my website

### ISSUE THREAD

**Issue by SSQ** [hexojs/hexo#2618]
### Node version(`node -v`): 
v6.10.3

### Your site `_config.yml` (Optional):
```
# Site
title: SSQ
subtitle:
description:
author: SSQ
language: en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ssq.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
#per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/SSQ/SSQ.github.io.git
  #branch: master

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10`
```

### `Your` theme `_config.yml` (Optional): 
theme: next 
`version: 5.1.1`
### Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 G:\hexo
+-- hexo@3.3.7
+-- hexo-deployer-git@0.3.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.7
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.1
```

## For question

"404 File not found" occurs when I click second page of posts in my website, but posts normally display in local server.

## For feature request

I set
```
per_page: 5 
```
I have more than 5 posts, so I need more than 1 page to show. 

When I run `hexo s`, everything is ok. Posts display normally at every pages in my local server (http://localhost:4000/). 

But after I deploy it, run `hexo d -g`, I cannot find my posts listed in page 2 and page 3 on my website(https://NAME.github.io/). `404 file not found` occurs.

How to solve this problem?
