### ISSUE TITLE
hexo was killed because Out of memory

### ISSUE THREAD

**Issue by xiaochao** [hexojs/hexo#2621]
docs num: 1600

the last ten line debug logs:

03:54:58.554 DEBUG Rendering index: tags/从衣服上去除口香糖/index.html
03:54:58.569 DEBUG Rendering index: tags/自然地拉直头发/index.html
03:54:58.589 DEBUG Rendering index: tags/计算梯形的周长/index.html
03:54:58.608 DEBUG Rendering index: tags/保存罗勒叶/index.html
03:54:58.628 DEBUG Rendering index: tags/不用开瓶器开瓶子/index.html
03:54:58.647 DEBUG Rendering index: tags/制作人造血/index.html
03:54:58.666 DEBUG Rendering index: tags/自然地加深头发颜色/index.html
03:54:58.677 DEBUG Rendering index: tags/打开难以拧开的瓶盖/index.html
03:54:58.679 DEBUG Rendering index: tags/用家庭秘方去痘印/index.html
03:54:58.717 DEBUG Rendering index: tags/使用VPN/index.html

hexo not debug log output for long time, about 1 hour.After then, it was killed by out of memory. 

Node version  v8.1.2

site `_config.yml` (Optional):

```yaml
title: 知识空间
subtitle: 行万里路读万卷书
description: 知识的集合，生活的小窍门
author: Simon
language: zh-CN
timezone: Asia/Shanghai

url: http://www.mobfan.cn
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 10
pagination_dir: page

theme: material

deploy:
  type:

theme `_config.yml` (Optional): 

head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    keywords:
    site_verification:
        google:
        baidu:

    structured_data: true

url:
    rss:
    daily_pic: "#"
    logo: "#"

scheme: Paradox

uiux:
    slogan: "Hi, nice to meet you"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

js_effect:
    fade: true
    smoothscroll: false

reading:
    entry_excerpt: 80
thumbnail:
    purecolor:
    random_amount: 19

background:
    purecolor: "#F5F5F5"
    bing:
        enable: false
        parameter:

img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    random_thumbnail: "/img/random/material-"
    footer_image:

fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: google
    custom_font_host:

card_elevation: 2

copyright_since:

qrcode:
    enable: false
    use: plugin


toc:
    linenumber: true

sns:
    email: youremail@email.com
    facebook: "https://www.facebook.com/facebook"
    twitter: "https://twitter.com/twitter"
    googleplus: "https://www.google.com/"
    weibo:
    instagram:
    tumblr:
    github:
    linkedin:
    zhihu:
    bilibili:
    telegram:

sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: false
    qq: false
    telegram: false

sidebar:
    dropdown:
        Email Me:
            link: "#"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: false
        icon: chrome_reader_mode
        divider: false
    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
        feedback: false
        material: false

materialcdn:
    use:
    base:
comment:
    use:
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey:

search:
    use: google
    swiftype_key:

analytics:
    use:
    site_id:

leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
```

Hexo and Plugin version(`npm ls --depth 0`): 

├── hexo@3.3.7
├── hexo-deployer-git@0.3.0
├── hexo-deployer-heroku@0.1.1
├── hexo-deployer-openshift@0.1.1
├── hexo-deployer-rsync@0.1.3
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.1
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.1
