### ISSUE TITLE
Hexo problem with Travis CI 

### ISSUE THREAD

**Issue by trung674** [hexojs/hexo#2627]
## Environment Info

Node version(`node -v`): 6.0.0

 `_config.yml`:
```
deploy:
  type: git
  skip_cleanup: true
  repo: https://__GITHUB_TOKEN__@github.com/trung674/vault.git
  branch: gh-pages
```
`.travis.yml`:
```
language: node_js
node_js:
- 6.0.0
branches:
  only:
  - master

install:
- npm install -g hexo
- npm install

before_script:
- git config --global user.name "johndoe"
- git config --global user.email "johndoe@email.com"
- sed -i "s/__GITHUB_TOKEN__/${__GITHUB_TOKEN__}/" _config.yml

script: hexo deploy
```

## For question
Hi, 

I want to use Travis CI to automate the build and deploy process for my site. However, the `body` content of my custom `index.html` page is always empty after the build process (which should be generated from  `source/index.ejs` that uses the `themes/bulma/layout/index.ejs` layout)

I removed `hexo-generator-index` package in order to create the custom `index` page.

Manual deploy is working just fine.

Source code : https://github.com/trung674/vault

Can anyone help me with this please ?
