### ISSUE TITLE
Hexo generate the generated file missing part of the DOM structure

### ISSUE THREAD

**Issue by HcySunYang** [hexojs/hexo#2701]
## Environment Info

Node: 8.0.0

My site `_config.yml` (Optional):

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: HcySunYang
subtitle: Blogs and life
description:
author: HcySunYang
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: hcysun.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year/:month/:day/:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 15
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 15
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: hcysun

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/HcySunYang/hcysunyang.github.io.git
  branch: master
```

My theme `_config.yml` (Optional): 

```yml
menu:
  Home: /
  About: /about
  Donate: /donate
```

Hexo and Plugin version(`npm ls --depth 0`): 

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.8"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-less": "^0.2.0",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```
## For question

Use the hexo server command to start the service after all normal, but the file generated after the hexo generate command is incorrect.
My template is as follows(sidebar.ejs)：
```ejs
<% if (is_home() || is_archive()) { %>
    <h2>Archives</h2>
    <%- list_archives({
      format: 'YYYY-MM'
    }) %>
  <% } %>
  <% if (is_post()) { %>
    <h2 class="toc-h2">目录</h2>
    <div class="toc-wrap">
      <%- toc(page.content) %>
    </div>
  <% } %>
```
But the generated file does not contain this DOM structure.

My project address：[https://github.com/HcySunYang/hexo-theme-sun](https://github.com/HcySunYang/hexo-theme-sun)
