### ISSUE TITLE
Template render error: (unknown path)

### ISSUE THREAD

**Issue by KarelWintersky** [hexojs/hexo#2716]
```
blacktower hexoblog # hexo server
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path) [Line 8, Column 13]
  unknown block tag: source
    at Object.exports.prettifyError (/srv/shared/archives/.Hexo/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/srv/shared/archives/.Hexo/node_modules/nunjucks/src/environment.js:469:27)
    at new_cls.renderString (/srv/shared/archives/.Hexo/node_modules/nunjucks/src/environment.js:327:21)
    at /srv/shared/archives/.Hexo/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/srv/shared/archives/.Hexo/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/srv/shared/archives/.Hexo/node_modules/hexo/lib/hexo/post.js:266:16)
    at /srv/shared/archives/.Hexo/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/srv/shared/archives/.Hexo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

## Environment Info

Node version(`node -v`):
v6.9.4

Hexo and Plugin version(`npm ls --depth 0`): 
```
blacktower hexoblog # npm ls --depth 0
hexo-site@0.0.0 /srv/shared/archives/.Hexo
├── hexo@3.3.8
├── hexo-admin@2.2.1
├── hexo-deployer-ftpsync@0.1.1
├── hexo-deployer-git@0.3.1
├── hexo-deployer-rsync@0.1.3
├── hexo-deployer-sftp@0.1.0
├── hexo-filter-sub@1.0.0
├── hexo-filter-sup@1.0.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-image-caption@0.1.1
├── hexo-lazyload-image@1.0.2
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-jade@0.4.1
├── hexo-renderer-less@0.2.0
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-scss@1.0.3
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
├── hexo-sliding-spoiler@1.1.6
└── hexo-tag-video@0.0.2

```

**Comment by KarelWintersky** [comment]
My _config.yml

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Сапиенсы учатся, играя
subtitle: Я кавайная няка. А тех, кто в этом сомневается...
description: 
author: Karel Wintersky
language: ru
timezone: Europe/Moscow

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: 'somewhere'
root: '/blog/'
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD/MM/YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: crisp

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ftpsync
  host: 77.222.42.180
  user: opuru
  pass: wupeereidiew
  remote: /wintersky.karel/public_html/blog/
  port: 22
  verbose: true
  delete: true

# Plugins
# hexo-lazyload-image ( https://github.com/Troy-Yang/hexo-lazyload-image )
lazyload:
  enable: true 
  onlypost: false
  loadingImg: # eg. ./images/loading.png
```
