### ISSUE TITLE
Hexo Built-in Highlight can not disabled

### ISSUE THREAD

**Issue by cubesky** [hexojs/hexo#2722]
## Environment Info

Node version(`node -v`): v6.9.2

Your site `_config.yml` (Optional):

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "天空之边"
subtitle: "异动之地"
description: "天空的边界到底在哪里？"
author: "天空之间"
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://xxxxx.xxxx
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: 
  - myfiles/attachment/*
  - myfiles/css/*.css
  - myfiles/javascriptbookmark/*.js
  - myfiles/js/*.js
  - myfiles/js/**/*.js
  - myfiles/js/**/**/*.js
  - myfiles/userjs/*.js

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false

# Category & Tag
default_category: uncategorized
category_map: 
tag_map: 

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-material

# Local Search
search:
  path: search.xml
  field: post

feed:
  type: rss2
  path: rss2.xml
  limit: 10
  hub:
  content:

# prism_plugin:
#   mode: 'preprocess'    # realtime/preprocess
#   theme: 'default'
#   line_number: true    # default false

sitemap:
    path: sitemap.xml
    template: ./node_modules/hexo-generator-sitemap/sitemap.xml

```

Your theme `_config.yml` (Optional): 

```yaml
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/myfiles/images/favicon.png"
    high_res_favicon: "/myfiles/images/favicon.png"
    apple_touch_icon: "/myfiles/images/favicon.png"
    keywords: 
    site_verification:
        google:
        baidu:
    structured_data: true
# Jump Links Settings
url:
    rss: "/rss2.xml"
    daily_pic: "/slogan"
    logo: "/skyedge"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
# scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: 
      - "相传胜利者肯定手持正义"
      - "那仅是因为正义可以被胜利者定义"
      - "测试版"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"
    
# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: false

# Reading experience
# markdown available value:
#     Material | Github | Plain
reading:
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor: 
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    #bgimg: "/img/bg.png"
    bing: 
        enable: false
        parameter: 

# Images Settings
img:
    logo: "/myfiles/images/logo.png"
    avatar: "/myfiles/images/avatar.png"
    daily_pic: "/myfiles/images/daily_pic.jpg"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    random_thumbnail: "/img/random/material-"
    footer_image:

# Custom Fonts
fonts: 
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: google
    custom_font_host:
# Card Elevation Level
card_elevation: 2


# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since: 

footer_text: 

# Qrcode for redirect at other device
qrcode:
    enable: false
    use: online

prettify:
    enable: true
    theme: "vibrant-ink"

license: 

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: false

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: xxxx@xxxx.com
    facebook: 
    twitter: 
    googleplus: 
    weibo: 
    instagram: 
    tumblr: 
    github: 
    linkedin: 
    zhihu: 
    bilibili: 
    telegram: 

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: true
    weibo: true
    linkedin: false
    qq: true
    telegram: true

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "mailto:xxxx@xxxx.com"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
        标签: 
            link: "/tags"
            icon: 
        永远的好伙伴: 
            link: "/links"
            icon: 
        关于我: 
            link: "/about"
            icon:
    article_num:
        use: false
        divider: false
    footer:
        divider: true
        theme: true
        support: false
        feedback: false
        material: false



# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------


# Comment Systems
# Available value:
#     duoshuo | disqus
comment:
    use:
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey:
    gentie_thread_key_type: path # path | id
    livere_data_uid:

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key: 
        
# Analytics Systems
analytics:
    use:
    site_id:

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的app_id
    app_key: #你的app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"
    
# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

# Files Vendors
# Set a CDN for the files src you want to customize. The url should with protocol.
# Default(empty) will load the files from the origin server.
vendors:
# MaterialCDN
#   You can load theme unique files from your private cdn or oss.
#   The new src will have the base domain you configured below.
#   For example
#       materialcdn: https://cdn.example.com
    materialcdn:

# Third party library
#   You can load these files from public cdn.
#   For example
#       jquery: https://cdn.bootcss.com/jquery/2.2.1/jquery.js
    # jQuery 2.2.0
    jquery:
    # nprogress 0.2.0
    nprogress:
    # FontAwesome 4.5.0
    fontawesome:
    # MathJax 2.7.0-2.7.1
    mathjax:
    # Prettify r298 (only prettify.js)
    prettify:
    # Material Icons 3.0.1
    material_icons:

```

Hexo and Plugin version(`npm ls --depth 0`): 

```
 hexo@3.3.8
 hexo-generator-archive@0.1.4
 hexo-generator-category@0.1.3
 hexo-generator-index@0.2.1
 hexo-generator-search@2.1.1
 hexo-generator-sitemap@1.2.0
 hexo-generator-tag@0.2.0
 hexo-helper-post-top@0.0.1
 hexo-helper-qrcode@1.0.2
 hexo-renderer-ejs@0.2.0
 hexo-renderer-marked@0.2.11
 hexo-renderer-stylus@0.3.3
 hexo-server@0.2.2
 hexo-tag-aplayer@2.0.2
 hexo-tag-bootstrap@0.0.8
```

## For question

I truned `highlight.enable` to `false`, and I haven't install any other highlight plugin. But it still has code highlight.

![image](https://user-images.githubusercontent.com/8038511/29497286-26134e5a-8618-11e7-9254-8c8ae8af1faa.png)

This will also happened when I use `landscape` theme.

![image](https://user-images.githubusercontent.com/8038511/29497327-95186f4c-8618-11e7-95da-7f36b24c84e0.png)
