### ISSUE TITLE
网站存放在子目录的问题

### ISSUE THREAD

**Issue by Lt-grint** [hexojs/hexo#2735]
## Environment Info

Node version(`node -v`):
v6.11.2

Your site `_config.yml` (Optional):
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://litao.work/blog
root: /blog/
##永久链接
permalink: :year/:month/:day/:title/
permalink_defaults:
```
Your theme `_config.yml` (Optional): 
```
menu:
  home: / || home
  categories: /categories/ || th
  archives: /archives/ || archive
  tags: /tags/ || tags
  about: /about/ || user
  #schedule: /schedule/ || calendar
  #sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat

# Enable/Disable menu icons.
menu_icons:
  enable: true

```
Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 /media/danerlt/资料/litao.work
├── hexo@3.2.2
├── hexo-deployer-git@0.2.0
├── hexo-deployer-heroku@0.1.1
├── hexo-deployer-openshift@0.1.1
├── hexo-deployer-rsync@0.1.2
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.0
├── hexo-generator-index@0.2.0
├── hexo-generator-sitemap@1.1.2
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.2.3
├── hexo-server@0.2.0
└── hexo-wordcount@3.0.2


```

## For question

设置子目录为/blog后，在本地打开正常，用域名打开不正常。
![image](http://static.zybuluo.com/danerlt/zqc708o5td26hkgc82jwq7xx/%E6%B7%B1%E5%BA%A6%E6%88%AA%E5%9B%BE_%E9%80%89%E6%8B%A9%E5%8C%BA%E5%9F%9F_20170830183824.png)

![image](http://static.zybuluo.com/danerlt/nauqqshlbcmhtcjdmemso1zy/image_1bopd6lrj1ov23gs1tlp1ouccvm1f.png)

![image](https://user-images.githubusercontent.com/14197717/29869182-8779aec0-8db4-11e7-977c-721037f51ab1.png)
