### ISSUE TITLE
external_link doesn't works as expected

### ISSUE THREAD

**Issue by shiywang** [hexojs/hexo#2744]
## Environment Info
Fedora 24
Node version(`node -v`):
v6.11.2
Your site `_config.yml` (Optional):
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Shiyang Wang
subtitle:
description:
author: Shiyang Wang
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://shiyang.wang
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: false # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yinwang

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:shiywang/shiywang.github.io.git
  branch: master

```
Your theme `_config.yml` (Optional): 
```
# when running hexo in a subdirectory (e.g. domain.tld/blog), remove leading slashes ( "/archives" -> "archives" )

version: 2.0
# Place your favicon.ico to /source directory.
favicon: /favicon.ico

# Set default keywords (Use a comma to separate)
keywords: "My Blog Kubernetes"

# Code Highlight theme
# Available value: normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: normal


menu:
  Blog: /
  #categories: /categories
  #archives: /archives
  #tags: /tags
  GitHub: https:github.com/shiywang
  #About: /about



# Static files
#vendors: vendors
css: css
js: js
images: images
```
Hexo and Plugin version(`npm ls --depth 0`): 
```
npm ls --depth 0
hexo-site@0.0.0 /home/shiywang/shiywang.github.io
├── hexo@3.3.8
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.0
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```
## For question
I check the _config file there's a filed named `external_link` which set to false I expect the new article link when click won't be in a new tab, but actually no matter true or false I set, it still open in a new tab when I click a link of my articles.

the command I use:
hexo g
hexo s
