### ISSUE TITLE
ERROR Deployer not found: git

### ISSUE THREAD

**Issue by killrookit** [hexojs/hexo#2757]
``` 
D:\hexo-bckup>hexo clean
D:\hexo-bckup>hexo g 
D:\hexo-bckup>hexo d
ERROR Deployer not found: git
======================Auto Backup Begin===========================
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working tree clean
Error: Git commit failed

_config.yml deploy配置如下:

deploy:
    - type: git
      repo:
         github: xxx,master
         coding: xxxx,master
     - type: baidu_url_submitter
       message: "{{ now('YYYY-MM-DD HH:mm:ss') }} "

 #plugins
plugins:
  - hexo-generator-sitemap
  - hexo-generator-baidu-sitemap
  - hexo-baidu-url-submit
```
hexo目录删除过，从服务器重新拉取过并且npm install了,git重装过,npm升级过，一律不行，主要出现原因是我添加了hexo-baidu-url-submit，然后出现错误通过搜索引擎也无法解决，我就删除了hexo-baidu-url-submit配置，git就报错了,昨晚也是同样出现过,我用本地备份的_config.yml改了一下就行了，现在却不行

在plugins添加推送百度搜索链接的就成功了，但是git依旧报错。求解决办法

**Comment by tea3** [comment]
@killrookit 

Your settings (`_config.yml`) seems to have a lot of space.
```
deploy:
    - type: git
      repo:
         github: xxx,master
         coding: xxxx,master
     - type: baidu_url_submitter
       message: "{{ now('YYYY-MM-DD HH:mm:ss') }} "
```

Is this correct ?

```
deploy:
  - type: git
    repo:
      github: xxx,master
      coding: xxxx,master
  - type: baidu_url_submitter
    message: "{{ now('YYYY-MM-DD HH:mm:ss') }} "
```
