### ISSUE TITLE
fail to parse the complete article and parse hyperlinks in a wrong way

### ISSUE THREAD

**Issue by fhfuih** [hexojs/hexo#2783]
## Environment Info

Node version(`node -v`):
v6.11.3

Your site `_config.yml` (Optional):
```
title: Glitchsome
subtitle: Random thoughts
description:
author: fhfuih
language: zh-cn
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://glitchso.me
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/fhfuih/fhfuih.github.io.git
  branch: master

# hexo-hey Admin

admin:
  name: ====
  password: ====
  secret: ====
  expire: 60*1

# hexo-qiniu-sync
qiniu:
  offline: false
  sync: true
  bucket: blog
  access_key: =====
  secret_key: =====
  dirPrefix:
  urlPrefix: =====
  local_dir: cdn
  update_exist: true
  image:
    folder: images
    extend:
#   js:
#     folder: js
#   css:
#     folder: css
```

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 C:\Users\huang\Documents\GitHub\fhfuih.github.io
+-- hexo@3.3.9
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-hey@0.4.1
+-- hexo-migrator-wordpress@0.1.2
+-- hexo-qiniu-sync@1.4.7
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.0
+-- hexo-renderer-stylus@0.3.3
`-- hexo-server@0.2.2
```

## For BUG

1. I wrote a new article, no errors on generation, but the html has such errors:
Only a small part of the article is parsed,
hyperlinks are parsed wrongly, with ':' replaced by '=' and disordered double-quotation marks.

The article and html source have been uploaded to Gist:
https://gist.github.com/fhfuih/2e25cbc7ef3c07024d3e71affa94f947
