### ISSUE TITLE
Want to extend code block method and add new highlight style !

### ISSUE THREAD

**Issue by zhuzhuyule** [hexojs/hexo#2915]
# Plan
#### Change
````
/**
 * Code block tag
 *
 * Syntax:
 *  ```[lang:language] [url] [link text] 
 *   code snippet
 *  ```
 */
````
   ↓  (extend, like Tag `code.js`)
```
/**
 * Code block
 *
 * Syntax:
 *   ```language [:title] [lang:language] [line_number:(true|false)] [first_line:number] [mark:#,#-#] [url:url download|下载]%}
 *   code snippet
 *   ```
 */
```
#### Features
- easy to setting **Code Block** better **Tag ** `code`

### 2.Modify  code block  structure (when `config.highlightEx: true` )
```html
<figure>
    <figcaption></figcaption>
    <table>
        </tr>
            <td class="gutter"><pre></pre></td>
            <td class="code"><pre></pre></td>
        </tr>
    </table>
</figure>
```
   ↓  (extend, like Tag `code.js`)
```html
<figure>
    <figcaption></figcaption>
    <div class="figcode">
            <div class="gutter"><pre></pre></div>
            <div class="code"> <pre></pre></div>
    </div>
</figure>
```
```css
pre {
  .attr {
    color: $highlight-purple;
  }
}

.figcode {
    margin: 0;
    width: 100%;
    border: none;
    font-size: 14px;

    display: flex;
    overflow: hidden;
}

.figcode>.gutter{
    flex: none;
    border-right: 2px solid $highlight-gutter.right-border-color;
    text-align: right;
    background-color: $highlight-gutter.bg-color;
    padding-left: 10px;
    padding-right: 10px;
}

.figcode>.code{
    flex: 1;
    border: none;
    margin: 0;
    overflow-x:auto;
    display:flex;
    padding-left: 10px;
    padding-right: 10px;
    .line:hover {
      background-color: $highlight-selection!important;
      // margin: 0 -5px 0 -10px;
      // padding: 0 5px 0 10px;
    }
}

.highlight .gutter pre
.highlight .code pre{
  padding-left: 0;
  padding-right: 0;
  overflow: visible;
}

.figcode .code pre{
    flex: 0 0 100%;
    padding-right: 10px;
    width: auto;
}

.highlight .line{
  display:block;
  margin: 0 0 0 -10px;
  padding: 0 0 0 10px;
}
```
#### Features
- easy to control scrollbar postion
- easy setting custom style
- brevity code

# Detail expression look [Example](https://zhuzhuyule.com/blog/HEXO/HEXO%E4%B8%8B%E7%9A%84%E8%AF%AD%E6%B3%95%E9%AB%98%E4%BA%AE%E6%8B%93%E5%B1%95%E4%BF%AE%E6%94%B9.html)
