### ISSUE TITLE
请教问题 hexo d时候出现问题

### ISSUE THREAD

**Issue by chencong-plan** [hexojs/hexo#2923]
```
Administrator@wh15323-PC MINGW64 /e/blog/Hexo
$ hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
TypeError: ejs:13
    11|         <title><%-: post.title %></title>
    12|         <pubTime><%= post.date.toDate().toISOString() %></pubTime>
 >> 13|         <%if(post.tags){ post.tags.toArray().forEach(function(tag){ %>
    14|         <tag><%= tag.name %></tag>
    15|          <% })}/*%>
    16|          <content><%-: post.content%></content>

post.tags.toArray is not a function
    at eval (eval at exports.compile (E:\blog\Hexo\node_modules\hexo-generator-baidu-sitemap\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:767)
    at Array.forEach (<anonymous>)
    at eval (eval at exports.compile (E:\blog\Hexo\node_modules\hexo-generator-baidu-sitemap\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:211)
    at eval (eval at exports.compile (E:\blog\Hexo\node_modules\hexo-generator-baidu-sitemap\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:1600)
    at E:\blog\Hexo\node_modules\hexo-generator-baidu-sitemap\node_modules\ejs\lib\ejs.js:255:15
    at Hexo.module.exports (E:\blog\Hexo\node_modules\hexo-generator-baidu-sitemap\lib\generator.js:19:13)
    at Hexo.tryCatcher (E:\blog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (E:\blog\Hexo\node_modules\bluebird\js\release\method.js:15:34)
    at E:\blog\Hexo\node_modules\hexo\lib\hexo\index.js:340:24
    at tryCatcher (E:\blog\Hexo\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (E:\blog\Hexo\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (E:\blog\Hexo\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (E:\blog\Hexo\node_modules\bluebird\js\release\promise_array.js:78:10)
    at MappingPromiseArray._asyncInit (E:\blog\Hexo\node_modules\bluebird\js\release\map.js:30:10)
    at Async._drainQueue (E:\blog\Hexo\node_modules\bluebird\js\release\async.js:138:12)
    at Async._drainQueues (E:\blog\Hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (E:\blog\Hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Comment by chencong-plan** [comment]
这是我的`_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site 网站
title: 聪聪的独立博客
subtitle:  挥舞这本子，做个ccoder
description: hello，every body!~
author: 聪聪不匆匆
language: zh-Hans
timezone: Asia/Shanghai

# URL 网址
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://chencong-plan.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory  目录配置
source_dir: source  # 源文件夹，这个文件夹用来存放md内容
public_dir: public  # 公共文件夹
tag_dir: tags  # 标签文件夹
archive_dir: archives  # 归档文件夹
category_dir: categories  # 分类文件夹
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # 新建文章默认文件名
default_layout: post  #默认布局
titlecase: false # Transform title into titlecase
external_link: true # 在新标签当中打开一个外部链接 默认为true
filename_case: 0  # 转换文件名 1小写 2 大写 0 默认
render_drafts: false # 将连接改为与根目录 相对位置
post_asset_folder: false  # 启动asset文件夹
relative_link: false   # 显示未来的文章 默认false
future: true  # 显示未来的文章 默认为false
highlight:     # 代码块位置
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag  分类和标签位的设置
default_category: uncategorized  # 默认分类
category_map: categories    # 分类别名
tag_map: tags       # 标签别名

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 
    github: git@github.com:chencong-plan/ccoder.github.io.git,master
    coding: git@git.coding.net:chencong3139/chencong3139.git,master
  branch: master
  message: Blog
# feed
# Dependencies: https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:

```
