### ISSUE TITLE
Hexo generate command results in html files with incorrect directory references

### ISSUE THREAD

**Issue by atoaster** [hexojs/hexo#2990]
## Environment Info
Mac OS 10.13.2 High Sierra

Node version(`node -v`): 7.7.4

Your site `_config.yml` (Optional):
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Toast
subtitle:
description: A blog that contains useless info about computer vision
author: Toast
language:
timezone: Australia/Melbourne

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://toast.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: landscape
theme: cactus-dark

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:atoaster/toast.github.io.git
  branch: master
```

Hexo and Plugin version(`npm ls --depth 0`): 
`├── hexo@3.4.4
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-pagination@0.1.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2`

When I run the `hexo generate` command it generates the static website files. When I open `public/index.html` it appears bare and broken. Looking in the developer console in Chrome, I can see there are many `Failed to load resource: net::ERR_FILE_NOT_FOUND` errors. The links to all the resources are broken.

Do i have to manually go through and change all the links in the html file to be correct, or is there a setting a can change in `config.yml` that will fix all these issues?
