### ISSUE TITLE
Is "hexo deploy" delete old files on remote host first? then push? why do this?

### ISSUE THREAD

**Issue by xu-song** [hexojs/hexo#3002]
## Environment Info

Node version(`node -v`):
v8.9.4
Your site `_config.yml` (Optional):
```
deploy:
  type: git
  repo: git@github.com:xu-song/xu-song.github.io.git
  branch: master
```
Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── hexo@3.5.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-search@2.1.1
├── hexo-generator-searchdb@1.0.8
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.2
```

## For question

`hexo deploy` will delete old files on remote host. right?
why do this?  more convenient to push?

[doc reference](https://hexo.io/docs/deployment.html)
