### ISSUE TITLE
'Cannot GET' Error for Internationalization

### ISSUE THREAD

**Issue by HarshaVardhanPVK** [hexojs/hexo#3012]
I am trying to add Internationalization to my hexo project to switch between languages by changing selection in drop-down.

For that I added 
```

language: [en, zh]

i18n:
  type: [page, post]
  generator: [index, archive, category, tag, page]

i18n_dir: :lang

```

in `_config.yml` file which is in root folder.

And created 2 files in languages folder under my theme folder respectively `en.yml, zh.yml`

When I am opening `http://localhost:4000/` it is showing English translation properly but when I try to open `http://localhost:4000/zh/` I am getting error as `Cannot GET /zh/`.

How to resolve this issue and also how to change routing of page programmatically when language selection changed?
