### ISSUE TITLE
Code in {% xxx %} ... {% endxxx %} can not use markdown

### ISSUE THREAD

**Issue by swwind** [hexojs/hexo#3033]
Hexo version:
```yaml
hexo: 3.5.0
hexo-cli: 1.0.4
os: Windows_NT 10.0.16299 win32 x64
http_parser: 2.7.0
node: 9.5.0
v8: 6.2.414.46-node.18
uv: 1.19.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.29.0
napi: 2
openssl: 1.0.2n
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
```

Code in theme/scripts/index.js:

```js
hexo.extend.tag.register('remark', function (args, content) {
  return `<div class="remark"><p>${content}</p></div>`
}, {ends: true})
```

Markdown:

```markdown
{% remark %}
Code in there can **not** use ~~markdown~~!!!
{% endremark %}
```

Result:

```html
<div class="remark"><p>Code in there can **not** use ~~markdown~~!!!</p></div>
```

I wonder if there is a function can solve it.
