### ISSUE TITLE
VPS上部署hexo无法加载css，js等依赖，本地正常

### ISSUE THREAD

**Issue by Dedsic** [hexojs/hexo#3034]
## Environment Info

Node version(`node -v`):8.9.4  
_config.yml` :  
```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://vectordigi.tk
root: /var/www/vectordigi/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: root@144.202.7.94:/root/vectordigi.git
  branch: master
  massage:
```
 
通过hexo -d上传了以后，配置了nginx反向代理了4000端口
```
server{
listen 4000;
root /var/www/vectordigi;
.........下略
```

chrome报错如下
```
GET http://ip:4000/var/www/vectordigi/css/style.css net::ERR_ABORTED
GET http://ip:4000/var/www/vectordigi/fancybox/jquery.fancybox.css net::ERR_ABORTED
GET http://ip:4000/var/www/vectordigi/fancybox/jquery.fancybox.pack.js net::ERR_ABORTED
GET http://ip:4000/var/www/vectordigi/js/script.js net::ERR_ABORTED
```
## For question
请问该如何解决此问题？感谢您查看此issue！
