### ISSUE TITLE
Warning: a promise was created in handler at  .../node_modules/hexo/lib/hexo/index.js

### ISSUE THREAD

**Issue by alanosman** [hexojs/hexo#3072]
Hi - I am receiving an warning when running the command `hexo generate -d -w` and I am wondering if it is something you know about.

This is what I am seeing on my console. 
```
INFO  Start processing
INFO  Files loaded in 402 ms
INFO  Generated: lunr.json
INFO  1 files generated in 71 ms
INFO  Hexo is watching for file changes. Press Ctrl+C to exit.
(node:3237) Warning: a promise was created in a handler at /mnt/d/elastc-help/node_modules/hexo/lib/hexo/index.js:
375:17 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/home/aosman/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/node
_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:3237) Warning: a promise was created in a handler at /mnt/d/elastc-help/node_modules/hexo/lib/hexo/index.js:
375:17 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/home/aosman/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/node
_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:3237) Warning: a promise was created in a handler at /mnt/d/elastc-help/node_modules/hexo/lib/hexo/index.js:
375:17 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/home/aosman/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/node
_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:3237) Warning: a promise was created in a handler at /mnt/d/elastc-help/node_modules/hexo/lib/hexo/index.js:
375:17 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/home/aosman/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/node
_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
(node:3237) Warning: a promise was created in a handler at /mnt/d/elastc-help/node_modules/hexo/lib/hexo/index.js:
375:17 but was not returned from it, see http://goo.gl/rRqMUw
    at ret (eval at makeNodePromisifiedEval (/home/aosman/.nvm/versions/node/v9.6.1/lib/node_modules/hexo-cli/node
_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:8:21)
INFO  Deleted: lunr.json
^CINFO  Catch you later
```

## Environment Info

Node version: 9.6.1

`_config.yml`
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Elastc Documentation
author: Elastc
timezone: UTC

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
# root: /

root: /help/

# Writing
relative_link: false
post_asset_folder: true

# Extensions
## Plugins: https://hexo.io/plugins/
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true

## Themes: https://hexo.io/themes/
theme: doc

theme_config:
  favicon: images/favicon.ico

ignore:
  - '**/themes/**/*(target|node_modules|packages|lib)'
  - '**/.+(*)' # ignoring all dirs and files starting with dot (.git, .idea, ...)
```

Hexo and Plugin version(`npm ls --depth 0`): 
elastc-help@0.1.0 /mnt/d/elastc-help
├── dress-code@2.4.0
├── eslint@4.18.2
├── hexo@3.6.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-less@0.2.0
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-sass@0.3.2
├── hexo-server@0.3.1
└── hexo-theme-doc@0.1.2

## For BUG
I run `hexo generate -w -d`
I edit my .md file
I save it and I see the warning in the console
