### ISSUE TITLE
[Feature Request]  keywords optimization for SEO

### ISSUE THREAD

**Issue by xu-song** [hexojs/hexo#3106]
## Background

default keywords in hexo 

https://github.com/hexojs/hexo/blob/master/lib/plugins/helper/open_graph.js#L41
```js
const keywords = page.keywords || (page.tags && page.tags.length ? page.tags : undefined) || config.keywords;
```

## Example

```yml
# For SEO, not for visualization
keywords:
  - permalink
  - hexo
  - plugin
  - hexo-plugin
  - 插件
  - 永久链接

# For visualization in site
tags:
  - permalink
  - hexo
  - plugin
```

If we want to optimize for SEO, we may define more keywords. In the above example, there are many overlap between `keywords` and `tags`.

In SEO aspect, `keywords` should contains `tags` by default, `keywords > tags`.

## Suggestion

1.  `keywords` contains `page.tags`
```js
const keywords = page.keywords.concate(page.tags) || config.keywords;
```
2.  `keywords` contains `page.categories`
