### ISSUE TITLE
Create new site.variable that works like `tags`

### ISSUE THREAD

**Issue by rabas007** [hexojs/hexo#3127]
How do I go about creating a new `site variable` that works the same way like `site.tags`?

So for example... `site.group` and then all features etc that `site.tags` has?

**Comment by tcrowe** [comment]
What happens if you add `group` in your [Front-matter](https://hexo.io/docs/front-matter.html)?

Example:

```yml
---
title: Hello World
date: 2013/7/13 20:46:25
groups:
  - travel
  - photos
---
```

Then try:

+ `post.groups`
+ `page.groups`
+ `site.groups`

Something might show up. Can you let me know?
