### ISSUE TITLE
ERROR Deployer not found: git

### ISSUE THREAD

**Issue by MandyJin** [hexojs/hexo#3188]
```
//package.json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-markdown-it": "^3.4.1",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "markdown-it-container": "^2.0.0",
    "markdown-it-deflist": "^2.0.3",
    "markdown-it-emoji": "^1.4.0",
    "markdown-it-mark": "^2.0.0"
  }
}
```
```
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:MandyJin/MandyJin.github.io.git
  branch: master
```
感觉自己的配置没有问题，但是报标题错误，重新初始化的文件夹，除了主题，什么也没修改 这是为什么呢，而且我的hexo下没有server命令？？？
