### ISSUE TITLE
Clear Broswer History

### ISSUE THREAD

**Issue by EricGao888** [hexojs/hexo#3261]
Every time I update my blog, I have to clear the history of my browser to view the update on the website. Is there any way that can make user's browsers clear their cache automatically when they visit my blog? Thank you.

**Comment by tcrowe** [comment]
Hey @EricGao888 :wave: That is something that comes up pretty often.

Here's one way I addressed it:

```yml
# hexo-server plugin
server:
  port: 4000
  log: false
  ip: 127.0.0.1
  compress: false
  serveStatic:
    cacheControl: true
    etag: false
    lastModified: false
```

Notice the `serveStatic` options. We should probably fix it in the `hexo-server` plugin.
