### ISSUE TITLE
👋 @dijia478

### ISSUE THREAD

**Issue by Ranchosm335** [hexojs/hexo#3312]
At first, please change your `package.json` hexo version. 
Example is below.

```yaml
  },
  "dependencies": {
    "hexo": "3.8.0",
```

Second. update hexo using by below command.

```sh
$ npm install
```

At the last. Please check update is success or not `hexo version`.
update is succeeded, if your hexo version is `3.8.0`.

_Originally posted by @YoshinoriN in https://github.com/hexojs/hexo/issues/3307#issuecomment-433088030_
