### ISSUE TITLE
localhost works, but didn't work on github pages.

### ISSUE THREAD

**Issue by desword** [hexojs/hexo#3322]
## Environment Info

Node version(`node -v`): v11.0.0

Your site `_config.yml` (Optional):

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Gonglong Chen
subtitle:
description:
keywords:
author: Gonglong Chen
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yelee
#theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:desword/blog.git
  branch: master
```

Hexo and Plugin version(`npm ls --depth 0`): 

```
├── hexo@3.8.0
├── hexo-deployer-git@0.3.1
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@0.3.2
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.3.3
```
There are many npm errors, like `npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0`

I used the Yelee theme to setup the blog, however, it works on localhost, but not on the github pages. 
I found that there are approaches to modify the source/vendor to the source/lib.
However, for the version I used now, I can not find the source/vendor. in Hexo.

The following the version infomation of hexo

```
hexo -version
hexo-cli: 1.1.0
os: Linux 3.19.0-25-generic linux x64
http_parser: 2.8.0
node: 11.0.0
v8: 7.0.276.28-node.5
uv: 1.23.2
zlib: 1.2.11
ares: 1.14.0
modules: 67
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0i

icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```
