### ISSUE TITLE
无法解析数学公式

### ISSUE THREAD

**Issue by stdoo** [hexojs/hexo#3425]
我安装了hexo-math，网站配置文件中也进行了配置，material theme的配置文件中也配置了mathjax，但还是不能解析数学公式，所有公式都无法解析，以markdown源码形式呈现在网站中。
## Environment Info
System: macOS 10.13.6
Node version(`node -v`):
v10.15.0
Your site `_config.yml` (Optional):
```
math:
  engine: 'mathjax' # or 'katex'
  mathjax:
    src: custom_mathjax_source
    config:
      # MathJax config
  katex:
    css: custom_css_source
    js: custom_js_source # not used
    config:
      # KaTeX config
```
Your theme `_config.yml` (Optional): 
```
# Files Vendors
# Set a CDN for the files src you want to customize. The url should with protocol.
# Default(empty) will load the files from the origin server.
vendors:
# MaterialCDN
#   You can load theme unique files from your private cdn or oss.
#   The new src will have the base domain you configured below.
#   For example
#       materialcdn: https://cdn.jsdelivr.net/npm/hexo-material@1.4.0/source
    materialcdn: 

# Third party library
#   You can load these files from public cdn.
#   For example
#       jquery: https://cdn.bootcss.com/jquery/2.2.1/jquery.js
    # jQuery 2.2.0
    jquery:
    # nprogress 0.2.0
    nprogress:
    # FontAwesome 4.5.0
    fontawesome:
    # MathJax 2.7.0-2.7.1
    mathjax: "/js/MathJax.js"
    # Prettify r298 (only prettify.js)
    prettify:
    # Material Icons 3.0.1
    material_icons:
```

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 /Users/*/blogs
├── ajv@6.7.0
├── eslint@4.12.1
├── hexo@3.8.0
├── hexo-deployer-git@1.0.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-math@3.0.4
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-markdown-it@3.4.1
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.3.3
```

`hero g --debug`没有报错。所以如何才能在hexo中加载MathJax？
