### ISSUE TITLE
GET 404 error messages when loading asset files

### ISSUE THREAD

**Issue by pnhuyduy** [hexojs/hexo#3452]
## Environment Info

Node version(`node -v`): node v10.15.1

Your site `_config.yml` (Optional):
```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://pnhuyduy.github.io/blog/
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
```

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):
- hexo 3.8.0
- hexo-generator-search 2.2.1

## For question
Hi, I stored the blog on https://github.com/pnhuyduy/blog, published at https://pnhuyduy.github.io/blog/. But I got some 404 error messages, image below.

![image](https://user-images.githubusercontent.com/46210597/52759821-e8e67100-303f-11e9-9a9e-09612951478d.png)

I confused that why the file's url is `https://pnhuyduy.github.io/search.xml`, it's supposed to be `https://pnhuyduy.github.io/blog/search.xml`. How can I fix this?
