### ISSUE TITLE
The front-matter's permalink can not override config.permalink

### ISSUE THREAD

**Issue by YoshinoriN** [hexojs/hexo#3464]
from #3442 

## Environment Info

Your site `_config.yml` (Optional):

```yaml
new_post_name: :year-:month-:day-:title.md
```

and frontmatter is 

```md
---
title: "This is a test"
date: 2019-01-31 20:44:31
permalink: first-blog
---
```

## Expected behavior

URL is `http://localhost:3000/first-blog`

## Actual behaviot

URL is `http://localhost:3000/2019/01/first-blog`

**Comment by gautamz07** [comment]
@YoshinoriN curious , so if you exclude `permalink` from the front matter the expected behavior is ::-

```http://localhost:3000/2019/01/first-blog``` ?

**Comment by YoshinoriN** [comment]
Thanks @gautamz07  :)

I think maybe ...

```
// _config.yml
new_post_name: :year-:month-:day-:title.md

// Front-matter
---
title: "This is a test"
date: 2019-01-31 20:44:31
---

// Result
http://localhost:3000/2019/01/31/This-is-a-test
```

But it is just my personal opinion...

**Comment by gautamz07** [comment]
Oh got it :) i ran into this same issue a while back .. i did't want that YY/MM/DD

**Comment by stevenjoezhang** [comment]
Relevant issue https://github.com/hexojs/hexo/issues/1813

**Comment by SukkaW** [comment]
It seems that only post is affected. The dedicated pages won't be affected.

**Comment by SukkaW** [comment]
Since only the post is affected, I wonder if the issue is about `new_post_path` filter:

https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/new_post_path.js

**Comment by SukkaW** [comment]
@YoshinoriN @stevenjoezhang 

Let me make the issue a little more clear:

**When config.permalink is set and no permalink in the front-matter**

```yaml
# _config.yml
new_post_name: :title.md # File name of new posts
permalink: post/:name/
permalink_defaults: :title/
```

`source/_posts/2020/hello-world.md`:

```markdown
---
title: "This is a test"
date: 2021-01-31 20:44:31
---
```

Then I get: `/post/hello-world/`. LGTM, it fits `config.permalink` just as I want it to be.

And if I change it to this:

```yaml
# _config.yml
new_post_name: :title.md # File name of new posts
permalink: post/:title/ # Use :title instead of :name
permalink_defaults: :title/
```

```markdown
---
title: "This is a test"
date: 2021-01-31 20:44:31
---
```

I will get `http://localhost:5000/post/2020/hello-world/`. Still, it fits `config.permalink`.

**Try to use front-matter to override config.permalink**

Here you go!

```yaml
# _config.yml
new_post_name: :title.md # File name of new posts
permalink: post/:title/ # Use :title instead of :name
permalink_defaults: :title/
```

```markdown
---
title: "This is a test"
date: 2021-01-31 20:44:31
permalink: hexo-hexo-hexo/i-love-hexo
---
```

Guess what! I get `/post/hexo-hexo-hexo/i-love-hexo/` instead of `/hexo-hexo-hexo/i-love-hexo/`!

So I changed my config again, this time I will `:name` instead of `:title`

```yaml
# _config.yml
new_post_name: :title.md # File name of new posts
permalink: post/:title/ # Use :title instead of :name
permalink_defaults: :title/
```

```markdown
---
title: "This is a test"
date: 2021-01-31 20:44:31
permalink: hexo-hexo-hexo/i-love-hexo
---
```

Then what? I get `/post/i-love-hexo/`! Even the `hexo-hexo-hexo` is now gone! WTF!

----

So it appears that not only `page.permalink` can't override anything, it is even being affected by `config.permalink`!
