### ISSUE TITLE
 use ftpsync failed to update file

### ISSUE THREAD

**Issue by zhaoky** [hexojs/hexo#3585]
Node version(`node -v`): `v10.15.0`

Your site `_config.yml` (Optional):
```
deploy:
  - type: ftpsync
    host: korey.gotoftp2.com
    user: name
    pass: 123
    remote: /wwwroot/blog/
    verbose: true
```

Hexo and Plugin version(`npm ls --depth 0`): 
```
"hexo": "^3.8.0",
"hexo-deployer-ftpsync": "^0.1.1"
```

The address and password are correct, and no error is reported.
Runtime information:
```
INFO  Deploying: ftpsync
Setup
-------------------------------------------------------------
Settings:
{ local: '/nice/github/hexo/public/',
  host: 'korey.gotoftp2.com',
  port: 21,
  remote: '/wwwroot/blog/',
  user: 'name',
  pass: '123',
  connections: 1,
  ignore: [] }

Setup complete.

Collecting
-------------------------------------------------------------
```
Then exit and Failed to update file.

I need your help, thank you!
