### ISSUE TITLE
"body is not defined" on most simple example site

### ISSUE THREAD

**Issue by jessegavin** [hexojs/hexo#3589]
## Environment Info

Node version:
```
v12.4.0
```

Your site `_config.yml` (Optional):
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: My Hexo Demo
subtitle: 
description:
keywords:
language: en
timezone: America/Chicago

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://demosite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: page
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```

Your theme `_config.yml` (Optional): 
None

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 /Users/me/code/rtc-hexo
├── hexo@3.9.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.3.1
├── hexo-renderer-marked@1.0.1
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.3.3
```

Your package.json `package.json`: 
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-server": "^0.3.3"
  }
}
```

## For question

I believe I have the simplest possible HEXO website, but when I attempt to run `hexo server` I get the following error

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
ReferenceError: /Users/me/code/rtc-hexo/source/layout/layout.ejs:3
    1| <html>
    2| <body>
 >> 3|   <%- body %>
    4| </body>
    5| </html>

body is not defined
    at eval (eval at compile (/Users/me/code/rtc-hexo/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:11:17)
    at returnedFn (/Users/me/code/rtc-hexo/node_modules/ejs/lib/ejs.js:668:17)
    at Object.exports.render (/Users/me/code/rtc-hexo/node_modules/ejs/lib/ejs.js:419:37)
    at Hexo.ejsRenderer (/Users/me/code/rtc-hexo/node_modules/hexo-renderer-ejs/lib/renderer.js:7:14)
    at Hexo.tryCatcher (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /Users/me/code/rtc-hexo/node_modules/hexo/lib/hexo/render.js:60:20
    at tryCatcher (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/me/code/rtc-hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (internal/timers.js:439:21)
```

My source folder has two files:

*/source/index.md*

```
---
title: About Us
date: 2019-06-20 21:51:38
---

This is my home page
```

*/source/layout/layout.ejs*

```
<html>
<body>
  <%- body %>
</body>
</html>
```
What am I doing wrong?

Source code is here: https://github.com/jessegavin/hexo-demo
