### ISSUE TITLE
How to render fetched data in Hexo using custom tag plugin ?

### ISSUE THREAD

**Issue by Geoffrey42** [hexojs/hexo#3635]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Node.js is higher than 6.9

## Question

I am building a markdown based online documentation using Hexo but I want to extend its capabilities by rendering network devices output commands.

To be more clear, instead of copy-pasting a command and its result in a codeblock I want to fetch the result using http before rendering the page.

I already coded the soft in charge of running the desired command and exposing its result in a web server.

All it does is sending a string containing the result. It's just text.

**All I want is render this result in the page using a Hexo tag plugin**.

I really am in a dev stage right now so I only use the default theme ("landscape"). Since I'm working on an old Arch Linux version (```4.19.8-arch1-1-ARCH```) I'm using Docker.

## The file structure inside the container:
```bash
.
|-- _config.yml
|-- package.json
|-- scaffolds
|   |-- draft.md
|   |-- page.md
|   `-- post.md
|-- scripts
|   `-- index.js
|-- source
|   `-- _posts
|       `-- hello-world.md
`-- themes
```

## The Dockerfile

```docker
FROM node:8.11.2

WORKDIR /gtd

ADD . .

RUN npm install hexo-cli -g
RUN npm install hexo-server --save
RUN npm install node-fetch --save
RUN npm install

CMD ["hexo", "server"]
```

## The hello-world.md

```markdown
{% cli_exporter "output" "show_version" "some_router" %}
```

## The custom plugin (scripts/index.js)

```javascript
const fetch = require("node-fetch");

hexo.extend.tag.register("cli_exporter", (args) => {
        const hostname = "XX.YYY.ZZZ.WW:XXXX"
        let endpoint, module, target
        [endpoint, module, target] = args 
        
        const url = "http://" + hostname + '/' + endpoint
                + "?module=" + module + "&target=" + target
        
        fetch(url)
        .then(response => {
                if (response.ok) {
                        return response.text()
                        .then(data => "<div>" + data + "</div>")
                        .catch(error => console.error(error))
                }
                return Promise.reject(new Error("response failed"))
        })
        .catch(error => Promise.reject(new Error(error.message)))
}, {async: true});
```

I really can't give you the real hostname since it's private software but it's really just plain text.

Let's say I want to render a ```show version``` result from a Cisco router. If I ```console.log(data)``` in the plugin I get the expected result. But it is not render in the generated website.

## Environment & Settings

**Node.js & npm version**

```
# node -v
v8.11.2
# npm -v
5.6.0
```

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle:
description:
author: John Doe
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: "http://some_private_gitlab/gtd/hexo"
root: "/hexo/"
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: landscape

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:
```

**Your theme `_config.yml`** (Optional)

```
landscape
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
# npm ls --depth 0
hexo-site@0.0.0 /gtd
+-- hexo@3.9.0
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
`-- node-fetch@2.6.0

npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.12.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.3
npm ERR! missing: inherits@2.0.3, required by glob@7.1.3
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.3
npm ERR! missing: once@1.4.0, required by glob@7.1.3
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.3.5, required by tar@4.4.8
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.8
npm ERR! missing: safe-buffer@5.1.2, required by tar@4.4.8
npm ERR! missing: yallist@3.0.3, required by tar@4.4.8
npm ERR! missing: minipass@2.3.5, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.3.5
npm ERR! missing: yallist@3.0.3, required by minipass@2.3.5
npm ERR! missing: minipass@2.3.5, required by minizlib@1.2.1
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.2",
    "node-fetch": "^2.6.0"
  }
}
```
