### ISSUE TITLE
pagination parsing error(分页编译错误)

### ISSUE THREAD

**Issue by chenshiforever** [hexojs/hexo#3729]
Yesterday I updated the latest version of hexo-cli. My current version is `hexo=3.9.0, hexo-cli=2.0.0` and dependencies are changed to `"hexo": "hexojs/hexo"`, but I have an error in paging now,paging parsing error.my paging configuration file is as follows
昨天我更新了最新的hexo-cli，我目前的版本是hexo=3.9.0，hexo-cli=2.0.0以及dependencies改为"hexo": "hexojs/hexo"，但是我现在的分页就出现了一个错误。分页解析错误,我的分页配置文件如下
```
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

archive_generator:
  per_page: 100
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page


# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next
```
Now it was this picture
![image](https://user-images.githubusercontent.com/5248630/65397259-351d3f00-dde1-11e9-872c-3bed7a47ae43.png)
I was found this code and discoverd the html code was like this
我在html文件里面发现了这些代码，应该是在gen阶段的parse错误。把不应该转义的实体集给转义了
```
<nav class="pagination">
    <span class="page-number current">1</span><a class="page-number" href="/page/2/">2</a><a class="extend next" rel="next" href="/page/2/">&lt;i class=&quot;fa fa-angle-right&quot; aria-label=&quot;下一页&quot;&gt;&lt;&#x2F;i&gt;</a>
  </nav>
```
the '<' was parsed to `&lt;`
the '...' was parsed to `&quot;`
the '>' was parsed to `&gt;`
the '...' was parsed to `&hellip;`
it seems something wrong at the gen step，so what I can solve it
