### ISSUE TITLE
Unable to properly include custom index.html

### ISSUE THREAD

**Issue by justinemar** [hexojs/hexo#3748]
I want to have a path like this
/ - custom index page
/blog - where the posts renders

I included the custom HTML file in the source and added
`skip_render: '*.html'` since `skip_render: index.html` wasn't working.

When i `hexo generate`, the index gets copied in the public and not altered, but in the browser it is mixed with the hexo generated html. How can i properly set this up?
```
root: /
permalink: blog/:year/:month/:day/:title/
permalink_defaults:


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: 
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: '*.html'

index_generator:
  path: '/blog'
  per_page: 10
  order_by: -date
```
