### ISSUE TITLE
Posts with code blocks no longer importing via medium or dev.to

### ISSUE THREAD

**Issue by Kritner** [hexojs/hexo#3766]
## Check List

Please check followings before submitting a new issue.

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [X] I have already searched existing issues and they are not help  to me
- [X] I examined error or warning messages and it's difficult to solve
- [X] Node.js is higher than 6.9

## Expected behavior

HTML generated for code blocks does not match what is expected for tools such as markedjs.  I saw the note above, but I don't know if it applies to me or not, the markdown is not being produced as expected, but that is expected since the HTML being produced does not match the pattern of a code block.  I was not sure if that touched on this repo, or something else.

## Actual behavior

The HTML produced for a code block deviates from what is expected for markedjs and other tools such as [turndown](https://domchristie.github.io/turndown/)

## How to reproduce?

Any code block post seems to be doing it at this point, I updated dependencies recently so i'm not sure if that's what it was or not.  This impacts both dev.to imports via RSS feed, as well as direct post imports on medium. Here's my dev.to github issue if that helps clear up anything: https://github.com/thepracticaldev/dev.to/issues/3995

A sample post that is not importing via medium or RSS is https://blog.kritner.com/2019/09/20/test-post-with-code/, RSS feed at https://blog.kritner.com/atom.xml

Here is the HTML produced:

```
<p>I’m having issues with an import into dev.to, just testing out a post with code snippets.</p><a id="more"></a><p>Having an issue under <a href="https://github.com/thepracticaldev/dev.to/issues/3995" target="_blank" rel="noopener">https://github.com/thepracticaldev/dev.to/issues/3995</a>, just attempting to make sure I can get posts with code to show up under drafts.</p><figure class="highlight cs hljs"><table><tr><td class="code"><pre><span class="line"><span class="hljs-function"><span class="hljs-keyword">public</span> <span class="hljs-keyword">void</span> <span class="hljs-title">DoStuff</span>(<span class="hljs-params"></span>)</span></span><br><span class="line"><span class="hljs-function"></span>&#123;</span><br><span class="line"> <span class="hljs-keyword">var</span> x = <span class="hljs-number">5</span>;</span><br><span class="line"> <span class="hljs-keyword">var</span> y = <span class="hljs-number">10</span>;</span><br><span class="line"></span><br><span class="line"> x ^= y;</span><br><span class="line"> x ^= y;</span><br><span class="line"> x ^= y;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
```

## Environment & Settings

**Node.js & npm version**

```
node --version 
v10.15.3

npm --version
6.4.1
```

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kritner's Blog
subtitle: Just tryin to learn some stuff and teach some stuff
description: Join me in coding, cooking, and controlled rotting of food.  I'm a developer who's always trying to learn more; I hope that this blog helps reinforce my own knowledge, and help others in theirs!
keywords: programming, how-to, developing, cooking, fermenting
author: Russ Hammett
language: en
timezone: America/New_York

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.kritner.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: true
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 25
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 25
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

# rss
feed:
  type: atom
  path: atom.xml
  limit: 0
  hub:
  content: true
  content_limit: 140
  content_limit_delim: '...'
  order_by: -date
  icon: icon.png
```

**Your theme `_config.yml`** (Optional)

```
# Version of the Icarus theme that is currently used
version: 2.3.0
# Path or URL to the website's icon
favicon: /images/favicon.ico
# Path or URL to RSS atom.xml
rss: 
# Path or URL to the website's logo to be shown on the left of the navigation bar or footer
logo: /images/logo.svg
# Open Graph metadata
# https://hexo.io/docs/helpers.html#open-graph
open_graph:
    # Facebook App ID
    fb_app_id: 
    # Facebook Admin ID
    fb_admins: 
    # Twitter ID
    twitter_id: rlhammett
    # Twitter site
    twitter_site: twitter.com/rlhammett
    # Google+ profile link
    google_plus: 
# Navigation bar link settings
navbar:
    # Navigation bar menu links
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    # Navigation bar links to be shown on the right
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'http://github.com/ppoffice/hexo-theme-icarus'
# Footer section link settings
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'http://github.com/ppoffice/hexo-theme-icarus'
# Article display settings
article:
    # Code highlight theme
    # https://github.com/highlightjs/highlight.js/tree/master/src/styles
    highlight: atom-one-light
    # Whether to show article thumbnail images
    thumbnail: true
    # Whether to show estimate article reading time
    readtime: true
# Search plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Search-Plugins
search:
    # Name of the search plugin
    type: insight
# Comment plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Comment-Plugins
comment:
    # Name of the comment plugin
    type: disqus
    shortname: kritnerblog # (required)
# Donation entries
# http://ppoffice.github.io/hexo-theme-icarus/categories/Donation/
donate:
    # -
    #     # Donation entry name
    #     type: alipay
    #     # Qrcode image URL
    #     qrcode: ''
    # -
    #     # Donation entry name
    #     type: wechat
    #     # Qrcode image URL
    #     qrcode: ''
    -
        # Donation entry name
        type: paypal
        # Paypal business ID or email address
        business: 'kritner@gmail.com'
        # Currency code
        currency_code: USD
    # -
    #     # Donation entry name
    #     type: patreon
    #     # URL to the Patreon page
    #     url: ''
# Share plugin settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Configuration/Share-Plugins
share:
    # Share plugin name
    type: 
# Sidebar settings.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # left sidebar settings
    left:
        # Whether the left sidebar is sticky when page scrolls
        # http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
    # right sidebar settings
    right:
        # Whether the right sidebar is sticky when page scrolls
        # http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/make-a-sidebar-sticky-when-page-scrolls/
        sticky: false
# Sidebar widget settings
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        # Widget name
        type: profile
        # Where should the widget be placed, left or right
        position: left
        # Author name to be shown in the profile widget
        author: Russ Hammett
        # Title of the author to be shown in the profile widget
        author_title: Software Engineer
        # Author's current location to be shown in the profile widget
        location: Westminster, MD
        # Path or URL to the avatar to be shown in the profile widget
        avatar: 
        # Email address for the Gravatar to be shown in the profile widget
        gravatar: kritner@gmail.com
        # Whether to show avatar image rounded or square
        avatar_rounded: true
        # Path or URL for the follow button
        follow_link: 'http://twitter.com/rlhammett'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-github
                url: 'http://github.com/kritner'
            Facebook:
                icon: fab fa-facebook
                url: 'http://facebook.com/kritner'
            Twitter:
                icon: fab fa-twitter
                url: 'http://twitter.com/rlhammett'
            # Dribbble:
            #     icon: fab fa-dribbble
            #     url: 'http://dribbble.com'
            RSS:
                icon: fas fa-rss
                url: /atom.xml
    -
        # Widget name
        type: toc
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: links
        # Where should the widget be placed, left or right
        position: left
        # Links to be shown in the links widget
        links:
            Website: 'https://kritner.com/'
            GitHub: 'https://github.com/kritner'
            StackOverflow: 'https://stackoverflow.com/users/2312877/kritner'
            Twitter: 'https://twitter.com/rlhammett'
            Twitch (Gaming): 'https://www.twitch.tv/kritner'
            Sourcerer: 'https://sourcerer.io/kritner'
            dev-to: 'https://dev.to/kritner'
            medium: 'https://medium.com/@kritner'
    -
        # Widget name
        type: category
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: tagcloud
        # Where should the widget be placed, left or right
        position: left
    -
        # Widget name
        type: recent_posts
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: archive
        # Where should the widget be placed, left or right
        position: right
    -
        # Widget name
        type: tag
        # Where should the widget be placed, left or right
        position: right
# Other plugin settings
plugins:
    # Enable page animations
    animejs: true
    # Enable the lightGallery and Justified Gallery plugins
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/gallery-plugin/
    gallery: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated-browser: true
    # Enable the MathJax plugin
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/mathjax-plugin/
    mathjax: true
    # Show the back to top button on mobile devices
    back-to-top: true
    # Google Analytics plugin settings
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Google-Analytics
    # google-analytics:
        # Google Analytics tracking id
    # Baidu Analytics plugin settings
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Baidu-Analytics
    baidu-analytics:
        # Baidu Analytics tracking id
        tracking_id: 
    # Hotjar user feedback plugin
    # http://ppoffice.github.io/hexo-theme-icarus/Plugins/General/site-analytics-plugin/#Hotjar
    hotjar:
        # Hotjar site id
        site_id: 
    # Show a loading progress bar at top of the page
    progressbar: true
    # Show the copy button in the highlighted code area
    clipboard: true
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
# CDN provider settings
# http://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL of the webfont CDN provider
    fontcdn: google
    # Name or URL of the webfont Icon CDN provider
    iconcdn: fontawesome

```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 E:\gitWorkspace\KritnerBlog
+-- hexo@3.9.0
+-- hexo-featured-image@0.3.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-feed@2.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@2.0.0
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-tag-twitter@1.0.1
`-- hexo-unsplash-credit@1.0.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "hexo": "^3.9.0",
    "hexo-featured-image": "^0.3.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-twitter": "^1.0.1",
    "hexo-unsplash-credit": "^1.0.0"
  }
}
```

## Others

I really don't know if this is an appropriate place to open the issue, seems that it could be one of many things, the HTML actually being generated for a code block, highlightjs, markedjs, etc.

I did recently update versions of pretty much everything from the `package.json`, I have not yet tried rolling back to versions that had vulnerabilities.

**Comment by seaoak** [comment]
From a comment in the issue on dev.to, dev.to might fail if a code block is in TABLE element.
https://github.com/thepracticaldev/dev.to/issues/3995#issuecomment-532911749

I found a setting of Hexo to prevent Hexo from converting a code block into a TABLE element.
(Instead, convert into a simple PRE element)

In `_config.yml`, insert a line `hljs: true` as follows:

```yaml
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: true
  hljs: true
```

NOTE:
  It may look like that syntax highlighting is disabled.
  If this setting works well, I will make a right workaround with highlighting.

@Kritner Could you please test this setting?
