### ISSUE TITLE
highlight.js不支持渲染yml和json类型的代码块，导致了TypeError

### ISSUE THREAD

**Issue by vpakati** [hexojs/hexo#3773]
在markdown的几个代码块已经声明使用的语言为yml了，但还是出现了这种错误——TypeError: Cannot set property 'lastIndex' of undefined
个人感觉是highlight.js不支持渲染语言类型为yml和json的代码块，因为front-matter就是遵循json和yml语法的。
后来把该代码块的语言类型设置为空，就不报错了。
这是我的_config.yml
```yml
highlight: # Code block syntax highlight settings, powered by highlight.js
  enable: true
  line_number: true
  auto_detect: true # Enable auto-detection if no language is specified
  tab_replace: # Replace tabs by n space(s); if the value is empty, tabs won’t be replaced
```
