### ISSUE TITLE
[Bug] Unable to render the title element inside the details tag properly

### ISSUE THREAD

**Issue by ddzy** [hexojs/hexo#3844]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Expected 

- ource code

![hexo_issue_1](https://user-images.githubusercontent.com/33921398/68446126-d0923400-0216-11ea-9ca3-627489fd4d43.png)

- preview with vscode

![hexo_issue_2](https://user-images.githubusercontent.com/33921398/68446135-d7b94200-0216-11ea-96c2-c680f9786dd3.png)
![hexo_issue_3](https://user-images.githubusercontent.com/33921398/68446136-d851d880-0216-11ea-9df3-91473e9a483d.png)

## Actual behavior

- using hexo([Jump to my website](https://blog.yyge.top/blog/2019/11/08/%E6%BB%B4%E6%BB%B4%E4%B8%89%E9%9D%A2%E6%80%BB%E7%BB%93/#3-url-替换))

![hexo_issue_4](https://user-images.githubusercontent.com/33921398/68446219-14853900-0217-11ea-9cd8-762814dae10d.png)

## How to reproduce?

* Write with markdown 
* Run `hexo g -d`
* View my website

## Environment & Settings

**Node.js & npm version**

```
node@10.3.0
npm@6.1.0
```

**Your site `_config.yml`** (Optional)

```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: DZY
subtitle: 大三老猫-frontender
description: 个人博客 - 多做, 多思考, 多记录
keywords: 博客 blog 个人博客
author: zhaoyang Duan
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ddzy.github.io/blog
root: /blog/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
# theme: Nlvi
# theme: landscape
theme: Nlvi

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: https://github.com/ddzy/blog.git
  branch: master
```

**Your theme `_config.yml`** (Optional)

```yml
# ===========================================
# Information Settings
# ===========================================

#navigation
menu:
  article: /
  archives: /archives
  tags: /tags
  # about: /about
  # RSS: /atom.xml
  # essay: /categories/essay
  # frontend: /categories/frontend

# favicon
favicon: /favicon.ico


# ===========================================
# Color&Schemes Setting
# ===========================================

## Common

# Mobile-Header
# light | dark
mobile-header: light

# Scheme
# banderole | balance
scheme: balance

## Banderole
# Header Style
# line | block
header-style: block

# Article Header Sign
header_sign: ＄

# theme-style
# miku | sakura | dark | green | blue | purple
theme-style: blue

# ===========================================
# Article Setting
# ===========================================

# Navigator in post
toc: true

# Use copyright infomation
copyright:
  enable: true
  # license: MIT

#Reword button or message(fill your QRCode of any Pay.)
reward:
  enable: false
  # message:
  qrcode:
    # alipay:
    # wechat:
    # paypal:

# ===========================================
# Social Contact
# ===========================================

# Comments // Please only switch one on.
comments:
  enable: true

  # disqus:
  # livere_datauid:

  # changyan:
  #   appid: cyu3LUqFV
  #   appkey: 2fab6348aaa253b461e5d6e4c1b1b26b

  # gitment:
  #   owner: ddzy
  #   repo: ddzy.github.io
  #   client_id: 'da227abbfeb5b4d39457'
  #   client_secret: 'd861af429b9fd372e91933c6c20d2daeb872dc4e'

  gitalk:
    owner: ddzy
    repo: blog
    client_id: 45d303490a6b33b33a74
    client_secret: cf3b8d0a0721a1fec9c38847c76d998fd0f72d07
    admin: [ddzy]

# sub //Please just fill out ID.
sub:
  # facebook: 1
  # twitter: 2
  # instagram: 3
  # weibo: 4
  # zhihu: 5
  # github: 6
  # linkedin: 7
  # douban: 8
  zhihu: bu-jing-tong-jsbu-zhao-dui-xiang-81/activities
  github: ddzy

#Friend link
# friendLink:

# ===========================================
# Analytics
# ===========================================

analytics:
  google:
  baidu:

#visit_count(Powered by busuanzi on http://busuanzi.ibruce.info/)
visit_count: true

# ===========================================
# Theme Settings
# ===========================================

# mathjax
mathjax: true

# lightbox
lightbox: true

# lazyload
lazyload: true

# animate (Powered by Syuanpi on https://colmugx.github.io/Syuanpi.css)
animate: true

# Created Time
since: 2018

# plugin
# plugins:

# about
# self:
self: FE

# ===========================================
# Search Settings
# ===========================================

# Search
search:
  enable: true
  label: 搜索一下？
  baseUrl: /blog

# ===========================================
# Documents Styles
# ===========================================

# article-fonts
# default | Simsun | YaHei | Hel | Custom
fonts-style: default

# code-fonts
# default | Custom
code-style: default

# ===========================================
# WebApp Settings (iOS)
# ===========================================


# ===========================================
# Version
# ===========================================
version: 2.4

#theme_author: Co1MugX
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```plain
+-- hexo@3.8.0
+-- hexo-deployer-git@1.0.0      
+-- hexo-generator-archive@0.1.5 
+-- hexo-generator-category@0.1.3+-- hexo-generator-index@0.2.1   
+-- hexo-generator-search@2.4.0  
+-- hexo-generator-tag@0.2.0     
+-- hexo-renderer-ejs@0.3.1      
+-- hexo-renderer-marked@0.3.2   
+-- hexo-renderer-stylus@0.3.3   
`-- hexo-server@0.3.3
```

**Your package.json `package.json`**

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  },
  "devDependencies": {}
}
```

## Others
