### ISSUE TITLE
Install release-drafter GitHub app

### ISSUE THREAD

**Issue by YoshinoriN** [hexojs/hexo#3858]
@hexojs/core 

I found the application for the GitHub release note.

> https://github.com/apps/release-drafter

This application create a release note automatically.
Current hexo has many time releases and I think it's hard to us. (Sorry @curbengh ...)

I'm concerned about `installation permissions`, but perhaps useful for us.
How do you think?

We can find [some examples](https://github.com/search?l=YAML&q=%23+Config+for+https%3A%2F%2Fgithub.com%2Fapps%2Frelease-drafter&type=Code).

**Comment by curbengh** [comment]
+1

Can use the following config to be consistent with existing style:

``` yml
name-template: '$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
categories:
  - title: '### Features'
    labels: 'feat'
  - title: '### Fixes'
    labels: 'fix'
  - title: '### Dependencies'
    label: 'chore'
change-template: '- $TITLE [#$NUMBER]'
template: |
  $CHANGES
```
