### ISSUE TITLE
Theme config is not deeply updated

### ISSUE THREAD

**Issue by cmpute** [hexojs/hexo#3964]
## Check List

Please check followings before submitting a new feature request.

- [x] I have already read [Docs page](https://hexo.io/docs/)
- [x] I have already searched existing issues

## Feature Request

Theme configuration override is available in hexo as [stated in the docs](https://hexo.io/zh-cn/docs/configuration), however, this override is limited in depth.

For example if the config in theme is
```yaml
# themes/xxx/_config.yaml
a:
  b: 1
  c: 2
```
and I set global config as
```yaml
# _config.yaml
theme_config:
  a:
    b: 3
```
The final config will be only `a: {b: 3}` rather than `a: {b: 3, c: 2}`. Could you please support deep update of the config setting? Since it's quite annoying to store a lot of default configs if the config file for a theme is too long (for example 1k+ lines for `next` theme)
