### ISSUE TITLE
怎么改变归档网页标题栏的'归档'两个字？

### ISSUE THREAD

**Issue by ZYLHL** [hexojs/hexo#4065]
## Check List

Please check followings before submitting a new issue.

- [ ] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ ] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [ ] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ ] Node.js is higher than 8.6.0

## Question

我应用了个性化主题，把几个网页标题栏的原名'tag''category''about'自己改成了中英混合式'标签集/Tags''分类/Category''关于/About'，是通过站点文件夹/source/<对应分页名>/index.md 中的title进行的修改，但是/source/_posts文件夹（也就是归档那个文件夹）没有index.md文件供修改标题title。

具体情况见这几张截图：
![image](https://user-images.githubusercontent.com/47456685/71977620-38cfb700-3254-11ea-8553-714697a03dc2.png)
![image](https://user-images.githubusercontent.com/47456685/71977636-41c08880-3254-11ea-9b43-8348cbfa9f21.png)
![image](https://user-images.githubusercontent.com/47456685/71977641-471dd300-3254-11ea-990b-ac54cd13ca52.png)

## Environment & Settings

**Node.js & npm version**

```
lihanlin@chromebook-with-debian:~/桌面/ZYLHL$ node --version
v13.6.0
lihanlin@chromebook-with-debian:~/桌面/ZYLHL$ npm --version
6.13.4
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo: 4.2.0
hexo-cli: 3.1.0
os: Linux 5.0.0-23-generic linux x64
node: 13.6.0
v8: 7.9.317.25-node.26
uv: 1.34.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.15.0
modules: 79
nghttp2: 1.40.0
napi: 5
llhttp: 2.0.1
openssl: 1.1.1d
cldr: 36.0
icu: 65.1
tz: 2019c
unicode: 12.1
```

**Your package.json `package.json`**

```
None
```

**Comment by tiexo** [comment]
https://github.com/Siricee/hexo-theme-Chic/blob/master/languages/zh-CN.yml
categories: 分类/Category

**Comment by zombie110year** [comment]
可能需要到主题的翻译配置中去改：比如我用的 NexT 主题里面就有 `languages/zh-CN.yml` 文件，在主题的 `_config.yml` 中配置的条目就是里面翻译所用到的键。

```yml
# 主题 _config.yml
menu:
# 对于 NexT 来说，分别是：<key>: <path> || <icon name (font-awesome)>
  home: / || home
  #about: /about/ || user
  tags: /tags/ || tags
  categories: /categories/ || th
  archives: /archives/ || archive
  #schedule: /schedule/ || calendar
  sitemap: /sitemap.xml || sitemap
  #commonweal: /404/ || heartbeat
```

加入希望将 tags 的显示名改成 「标签云」，则到

```diff
# languages/zh-CN.yml
menu:
# 其他条目
-  tags: 标签
+  tags: 标签云
```
