### ISSUE TITLE
使用NEXT模板 没有渲染出main.css

### ISSUE THREAD

**Issue by xingshu1990** [hexojs/hexo#4132]
---
name: Bug report
url: https://xingshu1990.github.io/pycoding/ 
about: https://xingshu1990.github.io/pycoding/  main.css没有渲染出来
title: ''
labels: ''
assignees: ''

---

## Check List
*hexo: 4.2.0
*hexo-cli: 3.1.0
*os: Windows_NT 6.1.7601 win32 x64
*http_parser: 2.8.0
*node: 9.11.1
*v8: 6.2.414.46-node.23
*uv: 1.19.2
*zlib: 1.2.11
*ares: 1.13.0
*modules: 59
*nghttp2: 1.29.0
*napi: 3
*openssl: 1.0.2o
*icu: 61.1
*unicode: 10.0
*cldr: 33.0
*tz: 2018c

##日常编译操作
*hexo clean
*hexo g
*hexo d

## Environment & Settings

**Node.js & npm version**
在Check List中

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: pycoding
subtitle: ''
description:  'coding，即编译程序。本人主职传统行业的销售，业余时间喜欢捣鼓Python，目前方向是爬虫。本网站为学习Python记事本。'
keywords: 'Python,mysql,爬虫'
author: xingshu1990
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
#url: https://xingshu1990.github.io
#root: https://xingshu1990.github.io/pycoding/
url: http://xingshu1990.github.io
root: /pycoding/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: 已经部署上去
  branch: master

```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.14.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.3
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.4, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0

npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.3
npm ERR! missing: inherits@2.0.4, required by glob@7.1.6
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.6
npm ERR! missing: once@1.4.0, required by glob@7.1.6
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.9.0, required by tar@4.4.13
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.13
npm ERR! missing: safe-buffer@5.1.2, required by tar@4.4.13
npm ERR! missing: yallist@3.1.1, required by tar@4.4.13
npm ERR! missing: minipass@2.9.0, required by fs-minipass@1.2.7
npm ERR! missing: safe-buffer@5.1.2, required by minipass@2.9.0
npm ERR! missing: yallist@3.1.1, required by minipass@2.9.0
npm ERR! missing: minipass@2.9.0, required by minizlib@1.3.3
```

**Your package.json `package.json`**

```
```

## 总结
下载了模板文件 放置到themes文件夹下，把模板文件名字改成next，
修改了网站_config配置，模板_config没动。
但是不能渲染出main.css文件。
请问如何解决。
谢谢。
