### ISSUE TITLE
<!-- more --> tag does not work in next 7.7.2

### ISSUE THREAD

**Issue by AdoreJc** [hexojs/hexo#4177]
I put the more tag at the front of my post, but I find that does not work. Then I tried the [Automatic excerpt generator for Hexo](https://github.com/chekun/hexo-excerpt), but that was also not working.
```
#_config.yml

excerpt_description: true

read_more_btn: true

excerpt:
  depth: 10
  excerpt_excludes: []
  more_excludes: []
  hideWholePostExcerpts: true
```
