### ISSUE TITLE
Browser download html files converted from markdown, instead of showing it

### ISSUE THREAD

**Issue by StefanoBichicchi** [hexojs/hexo#4191]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Environment & Settings

**Node.js & npm version**

```
node v12.16.1
npm v6.13.4
```

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Code the World!
subtitle: ''
description: ''
keywords:
author: Stefano Bichicchi
language: it
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: blog/:title
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD/MM/YYYY
time_format: HH:mm
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: material

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- hexo@4.2.0
| +-- abbrev@1.1.1
| +-- archy@1.0.0
| +-- bluebird@3.7.2
| +-- chalk@3.0.0
| +-- hexo-cli@3.1.0
| +-- hexo-front-matter@1.0.0
| +-- hexo-fs@2.0.0
| +-- hexo-i18n@1.0.0
| +-- hexo-log@1.0.0
| +-- hexo-util@1.9.0
| +-- js-yaml@3.13.1
| +-- lodash@4.17.15
| +-- micromatch@4.0.2
| +-- moment@2.24.0
| +-- moment-timezone@0.5.28
| +-- nunjucks@3.2.1
| +-- pretty-hrtime@1.0.3
| +-- resolve@1.15.1
| +-- strip-ansi@6.0.0
| +-- strip-indent@3.0.0
| +-- swig-extras@0.0.1
| +-- swig-templates@2.0.3
| +-- text-table@0.2.0
| +-- tildify@2.0.0
| +-- titlecase@1.1.3
| `-- warehouse@3.0.2
+-- hexo-deployer-git@2.1.0
| +-- bluebird@3.7.2 deduped
| +-- chalk@3.0.0 deduped
| +-- hexo-fs@2.0.0 deduped
| +-- hexo-util@1.9.0 deduped
| +-- moment@2.24.0 deduped
| `-- swig-templates@2.0.3 deduped
+-- hexo-generator-archive@1.0.0
| `-- hexo-pagination@1.0.0
+-- hexo-generator-category@1.0.0
| `-- hexo-pagination@1.0.0 deduped
+-- hexo-generator-index@1.0.0
| `-- hexo-pagination@1.0.0 deduped
+-- hexo-generator-tag@1.0.0
| `-- hexo-pagination@1.0.0 deduped
+-- hexo-render-pug@2.1.4
| `-- pug@2.0.4
+-- hexo-renderer-less@1.0.0
| `-- less@3.11.1
+-- hexo-renderer-marked@2.0.0
| +-- hexo-util@1.0.0
| +-- marked@0.7.0
| `-- strip-indent@3.0.0 deduped
+-- hexo-server@1.0.0
| +-- bluebird@3.7.2 deduped
| +-- chalk@2.4.2
| +-- compression@1.7.4
| +-- connect@3.7.0
| +-- mime@2.4.4
| +-- morgan@1.9.1
| +-- open@6.4.0
| `-- serve-static@1.14.1
`-- jstransformer-markdown-it@2.1.0
  `-- markdown-it@8.4.2
```

**Your package.json `package.json`**

```
{
  "name": "codetheworld",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-render-pug": "^2.1.4",
    "hexo-renderer-less": "^1.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-server": "^1.0.0",
    "jstransformer-markdown-it": "^2.1.0"
  }
}
```

## Others

I write post in markdown, but when i try to visualize it (click on post link), browser download file instead of showing it. Post's file is without extension and contains correct rendered html
