### ISSUE TITLE
`hexo new ` does not work

### ISSUE THREAD

**Issue by nicewaytodoit** [hexojs/hexo#4196]
When I type:

```hexo new aaa``` or 
```hexo new post aaa``` or 
```hexo new post aaa ``` or 
```hexo new post "aaa" ``` or

even copying simple:
```hexo new page --path about/me```
from your tutorial does not work

## Expected behavior
Create page.
## Actual behavior
Nothing happens, page does not get created. Only help gets invoked.
When trying to invoke help for that command that does not work as well.

## How to reproduce?

just follow above steps:

## Environment & Settings

**Node.js & npm version**
```
hexo-cli: 3.1.0
os: Windows_NT 10.0.18362 win32 x64
http_parser: 2.8.0
node: 10.15.0
v8: 6.8.275.32-node.45
uv: 1.23.2
zlib: 1.2.11
ares: 1.15.0
modules: 64
nghttp2: 1.34.0
napi: 3
openssl: 1.1.0j
icu: 62.1
unicode: 11.0
cldr: 33.1
tz: 2018e
```

**Your site `_config.yml`** (Optional)

```
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
```

**Your theme `_config.yml`** (Optional)
default one landscape
