### ISSUE TITLE
如何引用根目录_config.yml自定义变量？

### ISSUE THREAD

**Issue by xfqwdsj** [hexojs/hexo#4198]
我在根目录的config中定义了一个自定义的变量
现在想在md文件中引用它 我是这样做的：
```html
<script type="text/javascript">
AV.init({
	appId: "{{ config.mwordLC.appId }}",
	appKey: "{{ config.mwordLC.appKey }}",
	serverURLs: "{{ config.mwordLC.sURL }}"
})
</script>
```
但三个地方都没有数据：
```html
<script type="text/javascript">
AV.init({
    appId: "",
    appKey: "",
    serverURLs: ""
})
</script>
```
配置：
```yml
mwordLC: 
  appId:（ 我的id）
  appKey: （我的key）
  sURL: （一个url）
```
