### ISSUE TITLE
hexo cannot be properly installed

### ISSUE THREAD

**Issue by userqin** [hexojs/hexo#4272]
## Environment & Settings
git --version 
git version 2.26.0
node -v
v14.0.0
npm --v
6.14.4
hexo --v
(node:15394) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15394) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:15394) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:15394) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:15394) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:15394) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
hexo: 4.2.0
hexo-cli: 3.1.0
os: Darwin 17.7.0 darwin x64
node: 14.0.0
v8: 8.1.307.30-node.30
uv: 1.37.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 83
nghttp2: 1.40.0
napi: 6
llhttp: 2.0.4
openssl: 1.1.1f
cldr: 36.1
icu: 66.1
tz: 2019c
unicode: 13.0

## Information
 hexo g
(node:15397) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15397) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:15397) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:15397) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:15397) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:15397) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
INFO  Start processing
INFO  Files loaded in 94 ms
INFO  0 files generated in 21 ms

**Node.js & npm version**

```
git --version 
git version 2.26.0
node -v
v14.0.0
npm --v
6.14.4
```

**site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: xxx
subtitle: ''
description: ''
keywords:
author: xxx
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: july

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/user/user.github.io.git
  branch: master

```

** theme `_config.yml`** (Optional)

```
# html lang
language: en

# main menu navigation
menu:
  Home: /index.html
  Archives: /archives/index.html
  About: /about/index.html

site:
  # banner: /img/banner.jpg # banner map of website. (please annotation this line if you don't need it)
  avatar: https://www.gravatar.com/avatar/7a585313ed855e8d652cbb3154a6056e?s=300&d=mm&r=g # head portrait.
  #icp: 皖ICP备16011445号 # E-ICP prepared No.

# stylesheets loaded in the <head>
stylesheets:
  - /css/markdown.css
  - /css/july.css

# scripts loaded in the end of the body
scripts:
  - /js/jquery-3.4.1.min.js
  - /js/highlight-9.13.1.min.js
  - /js/transition.js
  - /js/smooth-scroll.min.js

hljs:
  enable: true # true to enable the plugin
  line_number: false # add line_number in frontend or backend (not recommend, have bugs in special hexo version)
  trim_indent: backend # trim the indent of code block to prettify output. backend or front-end (recommend)
  copy_code: true # show copy code in caption.
  label:
    left: Code
    right: ':'
    copy: Copy Code

# atom: atom.xml # website feed.

```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
npm ls --depth 0
hexo-site@0.0.0 /Users/user/GitHub/user.github.io
├── hexo@4.2.0
├── hexo-asset-image@0.0.5 (git+https://github.com/CodeFalling/hexo-asset-image.git#3c114cf0c0343ab28469635085b225fcae7fb9d3)
├── hexo-browsersync@0.3.0
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@2.2.0
├── hexo-generator-index@1.0.0
├── hexo-generator-sitemap@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-jade@0.5.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-stylus@1.1.0
└── hexo-server@1.0.0

```

**package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-asset-image": "git+https://github.com/CodeFalling/hexo-asset-image.git",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^2.2.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

### What should I do in order to deploy markdown files to git pages
How to resolve the following problems ?

- (node:15335) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
- (Use node --trace-warnings ... to show where the warning was created)
- (node:15335) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
- (node:15335) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
- (node:15335) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
- (node:15335) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
- (node:15335) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
-
