### ISSUE TITLE
User pages must be built from the master branch.

### ISSUE THREAD

**Issue by nxlsBoy** [hexojs/hexo#4298]
## Others

How to change master branch to gh-page branch.
Thanks.

**Comment by stevenjoezhang** [comment]
Docs here: https://github.com/hexojs/hexo-deployer-git#options

**Comment by leostudiooo** [comment]
You can change your `_config.yml` like this:
``` yaml
# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://gh_token@github.com/leostudiooo/leostudiooo.github.io.git
  # example, https://github.com/hexojs/hexojs.github.io
  branch: master
```
