### ISSUE TITLE
How can I deploy my site on a subdirectory

### ISSUE THREAD

**Issue by schtonn** [hexojs/hexo#4310]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [ ] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question
#1775 did not solve this

is this configuration just changes the meta things and links

It's actually working well in server mode but did not deploy well

so after deploying what I see is a site lost its css and js files and still in its original directory

## Environment & Settings

**Node.js & npm version**

```
npm -v
6.13.4
node -v
v12.16.1
```

**Your site `_config.yml`** (Optional)

```
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://schtonn.github.io/blog
root: /blog/
permalink: posts/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- @upupming/hexo-renderer-markdown-it-plus@2.0.2
+-- babel-core@6.26.3
+-- babel-preset-es2015@6.24.1
+-- gulp@4.0.2
+-- gulp-babel@7.0.1
+-- gulp-htmlclean@2.7.22
+-- gulp-htmlmin@5.0.1
+-- gulp-imagemin@7.1.0
+-- gulp-minify-css@1.2.4
+-- gulp-remove-use-strict@1.0.0
+-- gulp-rename@2.0.0
+-- gulp-uglify@3.0.2
+-- hexo@4.2.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index-pin-top@0.2.2
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- imagemin-gifsicle@7.0.0
+-- imagemin-jpegtran@6.0.0
+-- imagemin-mozjpeg@8.0.0
+-- imagemin-svgo@7.1.0
`-- picomatch@2.2.2
```

**Your package.json `package.json`**

```
```
