### ISSUE TITLE
Unable to run in GitLab CI [workaround available]

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#4314]
Since a week ago, my gitlab CI [jobs](https://gitlab.com/curben/blog/-/jobs) keep failing.

```
$ hexo generate
ERROR Local hexo not found in /builds/curben/blog
```

Unlike the [example](https://gitlab.com/pages/hexo) given by GitLab, I skip global installation of "hexo-cli" and run hexo using npm script `npm run hexo`:

``` json
package.json
{
  "scripts": {
    "hexo": "hexo generate"
  }
}
```

In addition to that approach, I also tried

1. `npm install -g hexo-cli && hexo generate` just like the example
2. Downgrade to Node 12

But none of them works. The only way is to switch "npm" to "[pnpm](https://pnpm.js.org/en)"

``` yml
before_script:
  - npm install -g pnpm
  - pnpm install

pages:
  script:
    - pnpm run hexo
  artifacts:
    paths:
      - public
  only:
    - master
```

It's probably related this [workaround](https://gitlab.com/curben/blog/-/commit/c6d0b9d8b851071ec5a5537ba23de76119e289ef) I use for compatibility with Node 14, but I had no issue at that time.

I don't think this is Hexo issue; I'm posting this for anyone having similar issue.
