### ISSUE TITLE
hexo generate do not build markdown files to html

### ISSUE THREAD

**Issue by SongHayoung** [hexojs/hexo#4382]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question
```
hello i have questions for my hexo generator
after i install algoliasearch my hexo do not generate .htmls from markdown files
is there something i miss? 
```
## Environment & Settings

**Node.js & npm version**
```
node : v14.4.0
hexo : 4.2.1
```
**Your site `_config.yml`** (Optional)
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: SUMFIのBlog
subtitle: Do it for FUN # be faituful to the BASICS
description: ''
keywords: ''
author: Song Hayoung
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://songhayoung.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: posts
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
plugins:
  - hexo-algoliasearch
  - hexo-server
  - hexo-deployer-git
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/SongHayoung/SongHayoung.github.io
  branch: master

algolia:
  applicationID: 7LZ6OJ4D6C
  apiKey: f3acbdf6cb6f5026e01dac578836d30c
  indexName: git blog
  chunkSize: 5000
  fields:
    - content:strip:turncat,0,500
    - excerpt:strip
    - gallery
    - permalink
    - photos
    - slug
    - tags
    - title
```
**Your theme `_config.yml`** (Optional)
```
# ---------------
# Theme color for customize
# Notice: color value must in double quotes like "#000" or may cause error!
# ---------------
theme_color:
  enable: true
  main: "#f7e650"
  paginator: "#00C4B6"
  button_hover: "#FF7242"
  text_selection: "#00C4B6"
  link_color: "#858585"
  hr_color: "#A4D8FA"
  tag_start_color: "#6ee100"
  tag_end_color: "#3a7402"
  header_text_color: "#5b3d04"
  footer_text_color: "#5b3d04"

# Main menu navigation
menu:
  Home: /
  History: /archives
  Tags: /tags
  Categories: /categories
  #XXX: /xxx

# Favicon
# ---------------
favicon: /song-favicon.ico

# PWA
# See https://github.com/JLHwung/hexo-offline
# ---------------
pwa:
  enable: false
  manifest: /manifest.json
  # If you don't want to trouble, just ignore the following things
  # See https://realfavicongenerator.net/
  # theme_color: "#49B1F5"
  # apple_touch_icon: /apple-touch-icon.png
  # favicon_32_32: /favicon-32x32.png
  # favicon_16_16: /favicon-16x16.png
  # mask_icon: /safari-pinned-tab.svg

# Highlight theme
# ---------------
highlight_theme: default

# code_word_wrap: true or false

# Nav settings
# see the icon_name in fontawesome website.
# And you need to add the `fa` or `fab` prefix by your self.
# ---------------
#social:
#icon_name fa: url
#icon_name fab: url

# Algolia search
# ---------------
algolia_search:
  enable: true
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "There's no article on ${query}. I'll fill it out quickly.  Σ(´△｀Ⅲ)"
    hits_stats: "${hits} results found in ${times} ms ٩(ˊᗜˋ*)و"

# Local search
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#local-search
# ---------------
local_search:
  enable: false

# MathJax
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#mathjax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.jsdelivr.net/npm/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# KaTeX
# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#katex
# ---------------
katex:
  enable: false
  cdn:
    css: https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
  hide_scrollbar: true

# Toggle fireworks (IE >= 10)
# ---------------
fireworks: false

# Analysis
# ---------------
baidu_analytics:

google_analytics: "UA-169368422-1"

# Tencent_analytics ID
tencent_analytics:

# stylesheets loaded in the <head>
# ---------------
stylesheets:
  - /css/index.css
# scripts loaded in the end of the body
# ---------------
scripts:
  - /js/utils.js
  - /js/fancybox.js
  - /js/sidebar.js
  - /js/copy.js
  - /js/fireworks.js
  - /js/transition.js
  - /js/scroll.js
  - /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
    # fontawesomeV5: https://use.fontawesome.com/releases/v5.3.1/css/all.css
  js:
    anime: https://cdn.jsdelivr.net/npm/animejs@latest/anime.min.js
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@latest/dist/jquery.fancybox.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js
    velocity-ui: https://cdn.jsdelivr.net/npm/velocity-ui-pack@latest/velocity.ui.min.js

# Post info settings
# ---------------
avatar:

top_img: https://Noting.jpg # false or url of img

top_img_height: 60 # best range: 60 - 100

post_meta:
  date_type: created # created or updated
  categories: true
  tags: true

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/additional-package-support.html#word-counting
wordcount:
  enable: true

toc:
  enable: true
  # number: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Please see doc for more details: https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#auto-excerpt
auto_excerpt:
  enable: false
  length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ""
  parallaxBackgroundSize: ""
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
# - itemlist:
#     img:
#     text:

# adv:
# enable: false
# info:

# Share System
# ---------------
addThis:
  enable: false
  #pubid:

# sharejs:
# enable: false
# disabled_sites:

# Comments System
# ---------------
disqus:
  enable: false
  #shortname:
  #count:

# laibili:
# enable: false
# uid:

gitment:
 enable: true
 owner: SongHayoung
 repo: SongHayoung/SongHayoung.github.io
 client_id: 3604b61642355579f55e
 client_secret: f552120f18ac5aee3f6297e05e97d94c0a25cd4b

# gitalk:
#   enable: false
#   client_id:
#   client_secret:
#   repo:
#   owner:
#   admin:

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is true
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/x/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2020

footer_custom_text: be faituful to the BASICS # put custom text directly or put hitokoto to fetch random texts

ICP:
  enable: false
  #text:

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file"></i>
  page_pv_footer:

# canvas_ribbon
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: false

# Sidebar Settings
# ---------------
# links_title: Links
# links:
# Name: url

# Follow Me Button
# follow:
#   enable: true
#   url: ''
#   text: ''

# controls the sidebar showing or hidden in different pages
sidebar_display: post # all/index/post/index-none/post-none/hidden

# Ads
# ---------------
# Google Adsense
google_adsense:
  enable: false
  js: //pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  client: ca-pub-...........
  enable_page_level_ads: true

# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
google_site_verification:

# Bing Webmaster tools verification setting
# See: https://www.bing.com/webmaster/
bing_site_verification:

# Yandex Webmaster tools verification setting
# See: https://webmaster.yandex.ru/
#yandex_site_verification:

# Baidu Webmaster tools verification setting
# See: https://ziyuan.baidu.com/site/
baidu_site_verification:

# 360 Webmaster tools verification setting
# see http://zhanzhang.so.com/
qihu_site_verification:

# avoid baidu transformation
disable_baidu_transformation: true

# 404 Page SubTitle
404Text:
```
**Hexo and Plugin version(`npm ls --depth 0`)**
```
├── @slate-editor/image-plugin@5.1.1
├── hexo@4.2.1
├── hexo-algolia@1.3.1
├── hexo-algoliasearch@0.4.2
├── hexo-deployer-git@2.1.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-basic-set@0.1.1
├── hexo-generator-category@1.0.0
├── hexo-generator-index@1.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-jade@0.5.0
├── hexo-renderer-marked@3.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-server@1.0.0
├── hexo-tag-asciinema@0.0.3
├── hexo-wordcount@6.0.1
└── highcharts-grouped-categories@1.1.5
```
**Your package.json `package.json`**
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "@slate-editor/image-plugin": "^5.1.1",
    "hexo": "^4.2.1",
    "hexo-algolia": "^1.3.1",
    "hexo-algoliasearch": "^0.4.2",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-basic-set": "^0.1.1",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.5.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-asciinema": "0.0.3",
    "hexo-wordcount": "^6.0.1",
    "highcharts-grouped-categories": "^1.1.5"
  }
}

```
