### ISSUE TITLE
{ } in code blocks convert to &#123; and &#125;

### ISSUE THREAD

**Issue by dumindu** [hexojs/hexo#4385]
## Question
- https://github.com/learning-rust/site was created from a fork of [hexojs/site](https://github.com/hexojs/site) with few modifications of  the navy theme.
- About a month ago **after the breaking changes of Node versions**, `{`  `}` in the code blocks, convert to `&#123;` and `&#125;`

![Screenshot 2020-06-28 at 12 17 23 PM](https://user-images.githubusercontent.com/1280428/85939459-54d12d00-b948-11ea-895b-15739099f777.png)

## Environment & Settings

**Node.js & npm version**

```
v14.4.0
6.14.4
```

**Your site `_config.yml`** (Optional)

```
title: Learning Rust
subtitle: "Rust Programming Language Tutorials"
description: "Rust Programming Language Tutorials"
author: Dumindu Madunuwan
language: en
timezone: UTC

url: https://learning-rust.github.io
root: /

theme: navy

deploy:
  type: git
  repo: git@github.com:learning-rust/learning-rust.github.io.git

highlight:
  enable: false

hljs:
  enable: true
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── cheerio@0.22.0
├── eslint@7.3.1
├── eslint-config-hexo@4.1.0
├── hexo@4.2.0 (github:hexojs/hexo#65961d328192e948586dd3c2a2b856173c628ef0)
├── hexo-clean-css@1.0.0
├── hexo-deployer-git@2.1.0
├── hexo-filter-nofollow@2.0.2
├── hexo-fs@3.1.0
├── hexo-generator-sitemap@2.0.0
├── hexo-renderer-marked@2.0.0
├── hexo-renderer-pug@1.0.0
├── hexo-renderer-stylus@1.1.0
├── hexo-renderer-swig@1.1.0
├── hexo-server@1.0.0
├── hexo-uglify@1.1.0
├── husky@4.2.5
├── imagemin-lint-staged@0.4.0
├── lint-staged@10.2.11
├── lunr@2.3.8
└── sharp@0.25.4
```

**Your package.json `package.json`**

```
{
  "name": "learning-rust.github.io",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "4.2.0"
  },
  "scripts": {
    "build": "hexo generate",
    "eslint": "eslint .",
    "deploy": "hexo deploy"
  },
  "dependencies": {
    "cheerio": "^0.22.0",
    "hexo": "hexojs/hexo",
    "hexo-clean-css": "^1.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-filter-nofollow": "^2.0.2",
    "hexo-fs": "^3.1.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.0.0",
    "hexo-renderer-swig": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-uglify": "^1.0.0",
    "lunr": "2.3.8",
    "sharp": "^0.25.2"
  },
  "devDependencies": {
    "eslint": "^7.0.0",
    "eslint-config-hexo": "^4.0.0",
    "husky": "^4.0.7",
    "imagemin-lint-staged": "^0.4.0",
    "lint-staged": "^10.2.2"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{png,jpeg,jpg,gif,svg}": [
      "imagemin-lint-staged",
      "git add"
    ]
  },
  "engines": {
    "node": ">=8.10.0"
  }
}
```

Thanks
