### ISSUE TITLE
Path to images unchanged

### ISSUE THREAD

**Issue by JasonPhone** [hexojs/hexo#4394]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than 8.6.0

## Question

I turned the `post_asset_folder` to true trying to post images in my blog, and it works as expected when executing `hexo new test`. A folder `yyyy-mm-dd-test/` is created under `_posts/` along with yyyy-mm-dd-test.md. I refer the image using `![](yyyy-mm-dd-test/img.png)` and get correct preview in my markdown editor. 

When the pages are generated, image files are moved to `public/yyyy/mm/dd/test` with the index.html, but img is like

```html
<img src="yyyy-mm-dd-test/img.png" alt="">
```

and it points to

```url
mydomain/yyyy/mm/dd/test/yyyy-mm-dd-test/img.png
```

but actually I can see my picture is pushed into

```url
mydomain/yyyy/mm/dd/test/img.png
```

It seems unchanged but my browser cannot load the it baceuse the path in `public/` is different from `_posts/`. When I refer the image as `![](img.png)` it works in browser but not in local markdown editor.

I did noting but `post_asset_folder: true`, and I wonder

1. If this behaviour is correct
2. Do I need to install any module to make it works both in browser and editor
3. Is there a better way to refer pictures in my blog

## Environment & Settings

**Node.js & npm version**

```
Node.js v12.16.1.
npm@6.13.4
```

**Your site `_config.yml`** (Optional)

```yml
# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- hexo@4.2.1
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it@4.1.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0
```

**Your package.json `package.json`**

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.1"
  },
  "dependencies": {
    "hexo": "^4.2.1",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it": "^4.1.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}
```
