### ISSUE TITLE
当把的highlight和prismjs的enable置为false的时候 使用主题自带的hightlight.js 大括号渲染失败

### ISSUE THREAD

**Issue by FuShaoLei** [hexojs/hexo#4452]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## Expected behavior
代码渲染健全，无缺失

## Actual behavior
代码内 大括号 渲染失败
## How to reproduce?

* Step1
将根目录里的highlight和prismjs的enable置为false
* Step2
随便使用一个自带高亮的主题（如white主题）
* Step3
随便输入一个带大括号的代码

## Is the problem still there under "Safe mode"?
ye

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
$ node -v
v12.16.2

$ npm -v
6.14.4
```

**Your site `_config.yml`** (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: white

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:FuShaoLei/FuShaoLei.github.io.git
  branch: master

```

**Your theme `_config.yml`** (Optional)

```

```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
$ npm ls --depth 0
hexo-site@0.0.0 E:\blog\Hexo
+-- hexo@5.0.0
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-search@2.4.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@3.0.0
+-- hexo-renderer-stylus@1.1.0
`-- hexo-server@1.0.0

```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-deployer-git": "^2.1.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0"
  }
}

```

**Comment by FuShaoLei** [comment]
再补充一点，当我把prismjs的enable设为true而 highlight设为false的时候，大括号是可以渲染出来的，可是呢，这时候小段的代码块，比如下面的例子，它是不会渲染出来的，也是无语，第一次提issue，有做不好的地方见谅
```java
System.out.println("WTF");
```

**Comment by gazf** [comment]
I also found the same problem.
There may be a problem with the code below.

https://github.com/hexojs/hexo/blob/0fb1866d5c7af690ff3c4aa23050937ddcf360e3/lib/plugins/filter/before_post_render/backtick_code_block.js#L9

https://github.com/hexojs/hexo/blob/0fb1866d5c7af690ff3c4aa23050937ddcf360e3/lib/plugins/filter/before_post_render/backtick_code_block.js#L94-L98

Unnecessary escape processing has been performed.

**Comment by SukkaW** [comment]
@gazf Would you mind giving us a demo? It will be appreciated if you could provide:

- The source code of the post
- The generated HTML file
- The screenshot of the page

**Comment by gazf** [comment]
@SukkaW Thank you for your reply
The environments tested are:

### _config.yml
``` yml
# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
```

### hello-world.md
```` md
---
title: Hello World
---
Welcome to [Hexo](https://hexo.io/)! This is your very first post. Check [documentation](https://hexo.io/docs/) for more info. If you get any problems when using Hexo, you can find the answer in [troubleshooting](https://hexo.io/docs/troubleshooting.html) or you can ask me on [GitHub](https://github.com/hexojs/hexo/issues).

## Quick Start

### Create a new post

``` bash
$ hexo new "My New Post"
```

More info: [Writing](https://hexo.io/docs/writing.html)

### Run server

``` bash
$ hexo server
```

More info: [Server](https://hexo.io/docs/server.html)

### Generate static files

``` bash
$ hexo generate
```

More info: [Generating](https://hexo.io/docs/generating.html)

### Deploy to remote sites

``` bash
$ hexo deploy
```

More info: [Deployment](https://hexo.io/docs/one-command-deployment.html)

```
{ 
    hexo: "5.0.0",
    test: {
        run: "hexo generate"
    }
}
```
````

### Screen Shot
![ss](https://user-images.githubusercontent.com/17435273/89284854-5948de00-d68a-11ea-8995-ee235fa093e3.png)
