### ISSUE TITLE
使用prism渲染 多出了一段文字 :hexoPostRenderEscape–>

### ISSUE THREAD

**Issue by jerryc127** [hexojs/hexo#4460]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Compatibility)

## How to reproduce?

* Step1
* Step2
* etc...

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
```

**Your site `_config.yml`** (Optional)

```yaml
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others

使用prism渲染代码，发现页面多了一段文字 :hexoPostRenderEscape–>
试过用highlightjs渲染，并没有这段文字
![image](https://user-images.githubusercontent.com/16351105/89123633-55d71a80-d503-11ea-9022-525c3ad1095f.png)

我用的是hexo-theme-unit-test的这篇文章[code-highlight](https://github.com/hexojs/hexo-theme-unit-test/blob/master/source/_posts/code-highlight.md)测试
还有这段文字上面的html代码没有line number生成。。
![image](https://user-images.githubusercontent.com/16351105/89123702-ec0b4080-d503-11ea-8337-e9b011f43616.png)

我在适配prismjs有点疑问，希望能解答
1. 按照hexo官网的教程，我引入了line-number.js(https://cdn.jsdelivr.net/npm/prismjs/plugins/line-numbers/prism-line-numbers.min.js),但是发现有些代码框并没有生成line-number,
以上面那篇文字为例
![image](https://user-images.githubusercontent.com/16351105/89123803-c29ee480-d504-11ea-8102-c743033237b8.png)
![image](https://user-images.githubusercontent.com/16351105/89123809-c92d5c00-d504-11ea-9bc1-c2a5a5b9d7c4.png)
好几个代码块是没有插入line-number html

2. 在pug中进行判断 `config.prismjs && config.prismjs.enable`  当配置文件中没有prisim这段配置（考虑到升级5.0的人没有去补全这段配置），运行会出现报错
![image](https://user-images.githubusercontent.com/16351105/89123871-2d502000-d505-11ea-97b8-015fb6753744.png)

这个要怎么解决？

**Comment by SukkaW** [comment]
> 1. 使用prism渲染 多出了一段文字 :hexoPostRenderEscape–>
>    使用prism渲染代码，发现页面多了一段文字 :hexoPostRenderEscape–>
>    试过用highlightjs渲染，并没有这段文字

@stevenjoezhang @curbengh 

`hexoPostRenderEscape` tags are added by backtick code block filter and should be removed by `PostRenrCache#loadContent`:

https://github.com/hexojs/hexo/blob/b7d15b95cb7e48b855f9d4c72bc24078b7b7a505/lib/hexo/post.js#L26-L29

https://github.com/hexojs/hexo/blob/b7d15b95cb7e48b855f9d4c72bc24078b7b7a505/lib/hexo/post.js#L267

I am not sure but I wonder if `disableNunjucks` or `marked.js` built-in escape is the culprit. I will bring up the test cases then.

**Comment by SukkaW** [comment]
> 1. 使用prism渲染 多出了一段文字 :hexoPostRenderEscape–>
>    使用prism渲染代码，发现页面多了一段文字 :hexoPostRenderEscape–>
>    试过用highlightjs渲染，并没有这段文字

The issue might be related with https://github.com/PrismJS/prism/issues/2516.

**Comment by curbengh** [comment]
> prism没有适配hexo自带的标签外挂？

https://github.com/hexojs/hexo-util/pull/227

**Comment by curbengh** [comment]
> https://user-images.githubusercontent.com/16351105/90124339-cf3bfc00-dd92-11ea-8fb8-542e65fab0c0.png

renders fine for me, even without #4472 

![test](https://user-images.githubusercontent.com/43627182/90221162-d32a5580-de48-11ea-9788-1026ce0f2411.png)

Can you attach your `_config.yml` (remove any sensitive values if preferred) and `package.json`?

**Comment by jerryc127** [comment]
I don't why,
i try in 'butterfly','next' and 'landscape', it have a same problem

Do you test this two case, it work ?

1. In markdown, use the Tag Plugins, such as 'pullquote', there is no blank line in the list and code block, it will rendering errors
2. In markdown, use the Tag Plugins, such as 'pullquote', the list and code block have blank lines, but there are spaces in front of the code block, it will rendering errors

I just only change the theme in _config
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: John Doe
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''
```

package.json

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.0.0"
  },
  "dependencies": {
    "hexo": "github:SukkaW/hexo#fix-4460",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^3.0.0",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-theme-butterfly": "^3.0.0",
    "hexo-theme-next": "^8.0.0-rc.5"
  }
}

```


![image](https://user-images.githubusercontent.com/16351105/90222119-fbf91d80-de3d-11ea-8b07-ac0989f02798.png)
