### ISSUE TITLE
YAML Front Matter拼接字符串有引号

### ISSUE THREAD

**Issue by Chameleons18** [hexojs/hexo#4511]
为了在Typora上编辑博客文章，然后将文章移动到/images/post/目录，为了方便管理而需要引入文章名称，就在模板scaffolds/post.md文件中编辑
```yaml
title: {{ title }}
typora-root-url: ..
typora-copy-images-to: ../images/post/{{ title }}/
```
执行命令`hexo new 新文章标题`结果多了引号
```yaml
title: 新文章标题
typora-root-url: ..
typora-copy-images-to: ../images/post/"新文章标题"/
```
注：如果使用{{‘../images/post/‘ + title + ‘/’}}（英文引号）则出现`"'新文章标题'"`的嵌套问题，而中文引号则同上

**Comment by curbengh** [comment]
Looks like value of front-matter is already wrapped with double-quote. Maybe it shouldn't wrap.

For example I have "scaffolds/post.md":

``` yml
---
title: {{ title }}
date: {{ date }}
typora: /{{ title }}/
---
```

When executing `hexo new 新文章标题`, `{{ title }}` is rendered through:

https://github.com/hexojs/hexo/blob/681486fe35f23764f0e03b83a251c4c912bcf12a/lib/hexo/post.js#L145

It outputs:

```
title: "新文章标"
date: 2020-01-02 03:04:05
typora: /"新文章标"/
```

Then it will be parsed by js-yaml:

https://github.com/hexojs/hexo/blob/681486fe35f23764f0e03b83a251c4c912bcf12a/lib/hexo/post.js#L151

``` js
const { load } = require('js-yaml')
const input = 'title: "新文章标"\ndate: 2020-01-02 03:04:05\ntypora: /"新文章标"/'
console.log(load(input))

/*
{
  title: '新文章标',
  date: 2020-09-08T01:31:43.000Z,
  tags: null,
  typora: '/"新文章标"/'
}
*/
```
