### ISSUE TITLE
Creating Custom Archive Page

### ISSUE THREAD

**Issue by hillswidth** [hexojs/hexo#4529]
## Question

So, I believe this is a simple and old question but since I was a newbie of Hexo I am asking for help.
I did my FanPage using Hexo and template [Artiface](https://artifact.me/) 
It doesn't really have an archive page
so I have tried to created one like Timeline looking without any extra visuals. 
My way is using the Hexo Turtoiral 
`hexo.extend.generator.register('archive', function(locals){
  return {
    path: 'archives/index.html',
    data: locals,
    layout: ['archive', 'index']
  }
});`
However, I am just simply created an index.md under folder _Posts and it archives just fine. 
Also, I followed the below steps still not solved. 
> > I modified in `_config.yml` the path for `index_generator`
> > I didn't uninstall `hexo-generator-index` (version 1.0.0)

## Environment & Settings

**Node.js & npm version**
 hexo: 5.1.1
 hexo-cli: 4.2.0
Node.js latest

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: I see Mii2
subtitle: ''
description: ''
keywords: Mii2, Jimmy Karn, Tommy Sittichok, DomundiTV
author: _sand
language: en
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://iseemii2.github.io/tl/
root: /tl/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map: Mii2
	      DMD
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'


# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: element

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/iseemii2/tl.git
  branch: gh-pages


```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
```

**Your package.json `package.json`**

```
```

## Others
about the bottom Search engine, I am simply using Google right now, but!!!!
Unable to search my local site, global search working fine.
How to make it just search my local posts? or local posts come first, then outside of the website?

I appreciate ur time and kindly helps!
