### ISSUE TITLE
what is the “type: tags”‘ role in  ”Front-matter” ?

### ISSUE THREAD

**Issue by likemby** [hexojs/hexo#4532]
what is the “type: tags”‘ role in  ”Front-matter” ?

**Comment by curbengh** [comment]
you mean this?

``` yml
---
title: example title
date: 2020-01-02 03:04:05
tags:
  - lorem
  - ipsum
---

a post content
```
