### ISSUE TITLE
[Bug] Issue with site put in a subdirectory

### ISSUE THREAD

**Issue by LocTran016** [hexojs/hexo#4553]
Hi there, I'm using [hexo-theme-melody](https://github.com/Molunerfinn/hexo-theme-melody) and receive a bug with my site. I have asked him here https://github.com/Molunerfinn/hexo-theme-melody/issues/303 but didn't help. He point me to the hexo's issue

## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

* [My site](https://loctran016.github.io/bio/)
* [My repo](https://github.com/LocTran016/bio)

## Expected behavior

Everything work just fine

## Actual behavior

Well, look like the `root` doesn't working. I'm deploying to `https://loctran016.github.io/bio/` but the site keep pointing to `https://loctran016.github.io/things` (for ex: `https://loctran016.github.io/tags` instead of `https://loctran016.github.io/bio/tags`) which lead to a ton of broken link

## How to reproduce?

Put the site in a subdirectory will make this

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
node v14.8.0
npm 6.14.7
```

**Your site `_config.yml`** (Optional)

```yaml
title: Presentation
subtitle: "All of LocTran016's presentation at the school"
description: ''
keywords: ''
author: LocTran016
language: en
timezone: 'Asia/Ho_Chi_Minh'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
url: https://loctran016.github.io/bio/
root: /bio/
permalink: :day/:month/:year/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

date_format: ddd DD MM YYYY
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

theme: melody

deploy:
  type: git
  repo: <repository url>
  branch: [branch]
  message: [message]

youtuber:
  allowfullscreen: yes
  autoplay: 1
  privacy_mode: yes

offline:
  maximumFileSizeToCacheInBytes: 10485760 # The maximum file size cached, in bytes
  staticFileGlobs:
    - public/**/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2,ico}
    - public/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2,ico}
    - public/**/**/*.{js,html,css,png,jpg,gif,svg,webp,eot,ttf,woff,woff2,ico}
  # Static file collection, if your site uses files such as webp format, please add the file type.
  stripPrefix: public
  verbose: true
  runtimeCaching:
    # CDNs - should be cacheFirst, since they should be used specific versions so should not change
    - urlPattern: /* # If you need to load CDN resources, please configure this option. If not, you can configure it.
      handler: cacheFirst
      options:
        origin: https://loctran016.gitlab.io # can be replaced with your url

feed:
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml

search:
  path: search.xml
  field: post
  content: true

lazyload:
  enable: true
  onlypost: true
  loadingImg: # optional eg ./images/loading.gif
  isSPA: false # optional

algolia:
  applicationID: CHGGDNC8BP
  apiKey: 814b9688ee0e7b51bb3472ceee26f7c5
  indexName: LocTran016

markdown_it_plus:
  plugins:
    - plugin:
      name: "@neilsustc/markdown-it-katex"
      enable: true
      options:
        strict: false
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@5.2.0
├── @picgo/bump-version@1.1.0
├── @upupming/hexo-renderer-markdown-it-plus@2.0.2
├── hexo@5.2.0
├── hexo-algolia@1.3.1
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-feed@3.0.0
├── hexo-generator-index-pin-top@0.2.2
├── hexo-generator-search@2.4.1
├── hexo-generator-tag@1.0.0
├── hexo-lazyload-image@1.0.9
├── hexo-offline@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-pug@1.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-tag-youtube-responsive@0.4.2
├── hexo-theme-melody@1.8.2
├── hexo-wordcount@6.0.1
├── markdownlint-cli@0.23.2
├── run-script-os@1.1.1
└── spellchecker-cli@4.4.0
```

**Your package.json `package.json`**

```json
{
  "name": "hexo-site",
  "version": "5.2.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "dev": "hexo server",
    "einfo": "npx envinfo",
    "cz": "git add . && git-cz && git push origin master",
    "release": "bump-version",
    "index": "./node_modules/.bin/hexo algolia",
    "fix-lint": "run-script-os",
    "fix-lint:default": "(echo Attempting to fix lint... && markdownlint '/source/_posts/*.md' -f && echo Fixed successfully, please commit.) || (echo Fix failed! && exit 1)",
    "fix-lint:win32": "(echo Attempting to fix lint... && markdownlint /source/_posts/*.md -f && echo Fixed successfully, please commit.) || (echo Fix failed! && exit 1)",
    "lint": "run-script-os",
    "lint:default": "(echo Linting... && markdownlint '/source/_posts/*.md' && echo Lint passed.) || (echo Lint failed! The lint will be automatically. Please review and fix errors later. && yarn run fix-lint)",
    "lint:win32": "(echo Linting... && markdownlint /source/_posts/*.md && echo Lint passed.) || (echo Lint failed! The lint will be automatically. Please review and fix errors later. && yarn run fix-lint)",
    "lint-ci": "run-script-os",
    "lint-ci:default": "(echo Linting... && markdownlint '/source/_posts/*.md' && echo Lint passed.) || ((echo Lint failed, attempting fix... && markdownlint 'source/_posts/*.md' -f && echo Fix generated successfully. Please apply the following diff using git apply && git diff) || echo Fix failed! && exit 1)",
    "lint-ci:win32": "(echo Linting... && markdownlint /source/_posts/*.md && echo Lint passed.) || ((echo Lint failed, attempting fix... && markdownlint source/_posts/*.md -f && echo Fix generated successfully. Please apply the following diff using git apply && git diff) || echo Fix failed! && exit 1)",
    "spellcheck": "run-script-os",
    "spellcheck:default": "(spellchecker --plugins spell repeated-words syntax-urls --dictionaries dictionary/misc.txt dictionary/capitalized.txt dictionary/dictionary.txt dictionary/science.txt dictionary/upper.txt --files 'source/_posts/*.md'  && echo Spellcheck passed.) || (echo Spellcheck failed! Please review and fix errors/add words to dictionary as needed. && exit 1)",
    "spellcheck:win32": "(spellchecker --plugins spell repeated-words syntax-urls --dictionaries dictionary/misc.txt dictionary/capitalized.txt dictionary/dictionary.txt dictionary/science.txt dictionary/upper.txt --files source/_posts/*.md  && echo Spellcheck passed.) || (echo Spellcheck failed! Please review and fix errors/add words to dictionary as needed. && exit 1)",
    "test": "run-script-os",
    "test:default": "yarn run lint --silent; yarn run spellcheck --silent",
    "test:win32": "yarn run lint --silent & yarn run spellcheck --silent"
  },
  "hexo": {
    "version": "5.2.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-algolia": "^1.3.1",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-search": "^2.4.1",
    "hexo-generator-tag": "^1.0.0",
    "hexo-lazyload-image": "^1.0.9",
    "hexo-offline": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-server": "^2.0.0",
    "hexo-tag-youtube-responsive": "^0.4.2"
  },
  "devDependencies": {
    "@picgo/bump-version": "^1.1.0",
    "@upupming/hexo-renderer-markdown-it-plus": "^2.0.2",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-renderer-pug": "^1.0.0",
    "hexo-theme-melody": "^1.8.2",
    "hexo-wordcount": "^6.0.1",
    "markdownlint-cli": "^0.23.2",
    "run-script-os": "^1.1.1",
    "spellchecker-cli": "^4.4.0"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-customizable"
    },
    "cz-customizable": {
      "config": "./node_modules/@picgo/bump-version/.cz-config.js"
    }
  },
  "commitlint": {
    "extends": [
      "./node_modules/@picgo/bump-version/commitlint-picgo"
    ]
  }
}
```

## Others
