### ISSUE TITLE
Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency

### ISSUE THREAD

**Issue by YLX621** [hexojs/hexo#4664]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question
I had no problems deploying locally, but when I did git push, my page went blank and I realized I was having a Node version problem.

When I run `hexo server`,it happen this.
```
(node:16680) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16680) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:16680) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
(node:16680) Warning: Accessing non-existent property 'lineno' of module exports inside circular dependency
(node:16680) Warning: Accessing non-existent property 'column' of module exports inside circular dependency
(node:16680) Warning: Accessing non-existent property 'filename' of module exports inside circular dependency
```

## Environment & Settings

**Node.js & npm version**

```
- Version: Node.js 14.0 
- Subsystem:Window 10
```

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 罹心的博客
subtitle: 'Rebirth'
description: 'Golang学习、全栈开发、成长过程'
keywords:
author: '杨李鑫'
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://ylx621.github.io/myblog
root: /myblog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: true


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: git@github.com:YLX621/YLX621.github.io.git
  branch: gh-pages
symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  awl: 4
  wpm: 80
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
+-- hexo@5.4.0
+-- hexo-deployer-git@3.0.0 (github:hexojs/hexo-deployer-git#70e2c8f0d154324db57d2fb2c1f65846e8c3f688)  
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@4.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-theme-keep@3.4.1
+-- hexo-theme-landscape@0.0.3
+-- hexo-word-counter@0.0.3
+-- mongodb@3.6.3
`-- node@12.21.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-deployer-git": "github:hexojs/hexo-deployer-git",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-keep": "^3.4.1",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-word-counter": "0.0.3",
    "mongodb": "^3.6.3",
    "node": "^12.21.0"
  }
}

```

## Others

I find I need to decrease node version.But I have no idea for this.And my home page is blank after `git push`.
