### ISSUE TITLE
Each Category & Tag aren't generating their respective pages.

### ISSUE THREAD

**Issue by kthecoder** [hexojs/hexo#4671]
## Check List

Please check followings before submitting a new issue.

- [ X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [ X] I have already searched existing issues and they are not help to me
- [ X] I examined error or warning messages and it's difficult to solve
- [ X] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [ X] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

I have created Category and Tag pages and the categories and tags are created but when I click on a Category or Tag the page does not exist. It does not exist in the source directory. Is it suppose to be manually created or auto generated? (Installed Theme, listed below)

If I have a 'Hello World' page with Category 'Intro'. When I go to the Categories page and click on 'Intro' the page doesn't exist. Yet the theme preview has it working.

How can I get this page created? I tried manually creating it but I couldn't figure out how the mappings work; how to correctly name folders and files and such to get it to work.

## Environment & Settings

**Node.js & npm version**

```
14.15.4
```

**Your site `_config.yml`** (Optional)

```

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''


# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: obsidian

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# Hexo Search
search:
  path: search.xml
  field: all
  content: true

```

**Your theme `_config.yml`** (Optional)

```
# Menu setting | format = title_name: link_url
menu:
  ABOUT: /whoami
  TOPICS: /categories
  TAGS: /tags
  TIME LINE: /archives

# Page custom titles
page_titles:
  categories: 'Topics'
  tags: 'Tags'
  archives: 'Archives'

# Social media links
socials:
  github: 'https://github.com/'
  twitter: 'https://twitter.com/'
  stackoverflow: 'https://stackoverflow.com/'

# Enable table of content
TOC: true


```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-search@2.4.1
├── hexo-generator-tag@1.0.0
├── hexo-renderer-ejs@1.0.0
├── hexo-renderer-marked@4.0.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
├── hexo-theme-landscape@0.0.3
└── hexo@5.4.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-search": "^2.4.1",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}

```

## Others

**Your theme**

```
Hexo Theme Obsidian
```
[Theme Repo](https://github.com/TriDiamond/hexo-theme-obsidian)
