### ISSUE TITLE
 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by lojunX** [hexojs/hexo#4693]
## Check List

Please check followings before submitting a new issue.

- [x] I have already confirmed other issue template and they are not different my want

## Environment & Settings

**Node.js & npm version**

```
exo: 5.4.0
hexo-cli: 4.2.0
os: Darwin 20.3.0 darwin x64
node: 14.16.1
v8: 8.4.371.19-node.18
uv: 1.40.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.16.1
modules: 83
nghttp2: 1.41.0
napi: 7
llhttp: 2.1.3
openssl: 1.1.1k
cldr: 37.0
icu: 67.1
tz: 2020a
unicode: 13.0
aaadeMBP:hexo-src qssq$ 
```

**Your site `_config.yml`** (Optional)

```


# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
# Site
title: 情迁美好时光追忆
subtitle: 情迁美好时光追忆 执拗如我 执着如我,纠结如我,虽然无法活出最好的自己,但是总算活出一个不一样的自己!
description: 人生在世 生活怎么选择 怎么快乐 每个人有不同的看法,而我 对人生的看法就是,我不奢望金钱和权力,奢望时间,奢望和谐的社会,奢望不忘的记忆,我有无比绝大的求知欲望,缺又不不得不面对记忆因为当下没有去应用而被遗忘,而人和电脑核心一样，多线程也只能叫切换,不能同时工作! 所以这是我奢望的也是求之不来的东西.
author: 情随事迁
language: zh-CN
timezone: Asia/Shanghai
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://lojunX.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
# Directory
source_dir: source
public_dir: public_web
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: codes
#nclude code 文件夹
i18n_dir: :lang
#国际化（i18n）文件夹
skip_render: ['*.html', qssq666/**, '*.js','jquery/**']
##忽略渲染的source里面的文件夹
###   - 'demo/**'
# Writing
new_post_name: :title.md
default_layout: post
titlecase: false
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
#把链接改为与根目录的相对位址，默认false
future: true
#显示未来的文章，默认false
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Category & Tag  uncategorized
default_category: 我的目录
category_map:
tag_map:
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ssp
# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
#每页显示的文章量 (0 = 关闭分页功能)
##0 显示全部
pagination_dir: page
#分页目录
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## default theme  theme: landscape   https://github.com/bulandent/hexo-theme-bubuzou
theme: bubuzou
#theme: jacman
##压缩css
##stylus:
##compress: false
#主题文件夹 更多参见主题文件夹_config.yml配置 false禁用主题
# Deployment
## Docs: https://hexo.io/docs/deployment.html  npm install hexo-generator-sitemap --save
# 下面开启rss  	npm install hexo-generator-feed --save
#plugins:
#- hexo-generator-feed
#- hexo-generator-sitemap
deploy:
  type: git
repo: https://lojunX:xxx@github.com/lojunX/lojunX.github.io.git

  branch: master
  message:  updatemsg
  #now('YYYY-MM-DD HH:mm:ss')

deploy_ftp:
  type: ftpsync #上传方式，固定ftpsync
  host: xcn #ftp地址x
  user: blog	#帐号
  pass: xxx	#密码
  remote: / #上传至哪个目录
  port: 21	#端口

baidusitemap:
 path: baidusitemap.xml

 generatorRecent:
  file: recent.json
  number: 100
  sort: -date
  fields: # set to true for all fields (default)
    - title
  #  - slug
    - date
    - tags

jsonContent:
  meta: true
  keywords: false # (english, spanish, polish, german, french, italian, dutch, russian, portuguese, swedish)
  pages:
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    link: true
    permalink: true
    excerpt: true
    keywords: true # but only if root keywords option language was set
    text: true
    raw: false
    content: false
  posts:
    title: true
    slug: true
    date: true
    updated: true
    comments: true
    path: true
    link: true
    permalink: true
    excerpt: true
    keywords: true # but only if root keywords option language was set
    text: true
    raw: false
    content: false
    categories: true
    tags: true
#七牛云存储设置
##offline       是否离线. 离线状态将使用本地地址渲染
##sync          是否同步
##bucket        空间名称.
##access_key    上传密钥AccessKey
##secret_key    上传密钥SecretKey
##secret_file   秘钥文件路径，可以将上述两个属性配置到文件内，防止泄露，json格式。绝对路径相对路径均可
##dirPrefix     上传的资源子目录前缀.如设置，需与urlPrefix同步
##urlPrefix     外链前缀.
##up_host      上传服务器路径,如选择华北区域的话配置为http://up-z1.qiniu.com
##local_dir     本地目录.
##update_exist  是否更新已经上传过的文件(仅文件大小不同或在上次上传后进行更新的才会重新上传)
##image/js/css  子参数folder为不同静态资源种类的目录名称，一般不需要改动
##image.extend  这是个特殊参数，用于生成缩略图或加水印等操作。具体请参考http://developer.qiniu.com/docs/v6/api/reference/fop/image/
##              可使用基本图片处理、高级图片处理、图片水印处理这3个接口。例如 ?imageView2/2/w/500 即生成宽度最多500px的缩略图 hexo s

  image:
    folder: images
    extend:
  js:
    folder: js
  css:
    folder: css
```

**Your theme `_config.yml`** (Optional)

```

menu:
    博文: /
    归档: /archives/
 #   生活: /categories/live/
    下载: /update/
    关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
changyan: bubuzou
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2015

menu:
    博文: /
    归档: /archives/
 #   生活: /categories/live/
    下载: /update/
    关于: /about/

widgets:
- category
- tag
- tagcloud
- archive

# count
show_count: true
favicon: /images/favicon.ico
logo: /images/logo.png

# Comment
changyan: bubuzou
yungentie: 
disqus:
duoshuo: 


# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2015


```

**Hexo and Plugin version(`npm ls --depth 0`)**

```

hexo-site@0.0.0 /Users/aaa/Documents/dev/hexo-src
├── hexo@5.4.0
├── hexo-browsersync@0.3.0
├── hexo-deployer-ftpsync@0.1.1
├── hexo-deployer-git@0.2.0
├── hexo-generator-archive@0.1.5
├── hexo-generator-baidu-sitemap@0.1.6
├── hexo-generator-category@0.1.3
├── hexo-generator-feed@1.2.2
├── hexo-generator-index@0.2.1
├── hexo-generator-json-content@2.2.0 extraneous
├── UNMET DEPENDENCY hexo-generator-json-econtent@^2.2.0
├── hexo-generator-recent@0.1.3
├── hexo-generator-search@2.3.0
├── hexo-generator-sitemap@1.2.0
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-jade@0.4.1
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
├── hexo-server@0.2.2
└── hexo-tag-tencent@0.1.3

npm ERR! missing: hexo-generator-json-econtent@^2.2.0, required by hexo-site@0.0.0
npm ERR! extraneous: hexo-generator-json-content@2.2.0 /Users/aaa/Documents/dev/hexo-src/node_modules/hexo-generator-json-content
aaadeMBP:hexo-src qssq$ 
```

**Your package.json `package.json`**

```

{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-ftpsync": "^0.1.1",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.1",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-json-econtent": "^2.2.0",
    "hexo-generator-recent": "^0.1.2",
    "hexo-generator-search": "^2.3.0",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-tag-tencent": "^0.1.3"
  }
}
```

## Others

```
2:48:44.974 FATAL {
  err: RangeError: Maximum call stack size exceeded
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:46:18)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:40:34)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at clone (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:58:17)
      at cloneArray (/Users/aaa/Documents/dev/hexo-src/node_modules/rfdc/index.js:31:17)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```
