### ISSUE TITLE
ERROR ReferenceError: qrcode is not defined

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [hexojs/hexo#4694]
## Check List

Please check followings before submitting a new issue.

- [√] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [√] I have already searched existing issues and they are not help to me
- [√] I examined error or warning messages and it's difficult to solve
- [√] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [√] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Environment & Settings

**Node.js & npm version**

```
6.14.12
```

**Your site `_config.yml`** (Optional)
```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: New！XiaMoHuaHuo_CN's Blog
subtitle: ''
description: ''
keywords:
author: XiaMoHuaHuo_CN
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://huahuo-cn.tk
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: materialized

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repository: https://github.com/XiaMoHuaHuo-CN/XiaMoHuaHuo-CN-Blog.git
  branch: master
```

**Your theme `_config.yml`** (Optional)
```
theme_color: # Theme color. Please go to [Colors](https://www.mdui.org/docs/color)
  primary: indigo
  accent: pink

notice: # Notice or announcement. Support `<a>` tag

favicon: https://z3.ax1x.com/2021/04/24/cj1hgf.jpg # Favicon path
banner: https://z3.ax1x.com/2021/05/01/gVj9Rf.jpg # Sidebar background image path
avatar: https://q2.qlogo.cn/headimg_dl?dst_uin=2549619802&spec=640 # Avatar image path
rss: /atom.xml # RSS link. `hexo-generator-feed` plugin is needed

email: # Email address
sns: # SNS links
  twitter: https://twitter.com/xiamohuahuo
  weibo: https://weibo.com/u/7534665253
  github: https://github.com/XiaMoHuaHuo-CN
  zhihu: https://www.zhihu.com/people/xiamohuahuo-cn/
  qq: http://wpa.qq.com/msgrd?v=3&uin=2549619802&site=qq&menu=yes

open_graph: # OpenGraph settings
  twitter:
  google_plus:
  fb_admins:
  fb_app_id:
site_verification: # Site verification keys
  google:
  baidu:
analytics: # Site analytics IDs
  google_site_id:
  baidu_site_id:
  cnzz_site_id:
pages: # Custom page links. Set with `name` and `link`
- name: Tags
  link: /tags
- name: Gallery
  link: /gallery
links: # Friendship links. Set with `name` and `link`
- name: Github
  link: https://github.com

since: 2019 # Start year, use a 4-digit number. If you don't set the start year, there won't be a "since xxxx" on the bottom of your site
footer_text: # Additional text in footer, such as the record information. Support `<a>` tag
license: # License description of every article. Support `<a>` tag

gallery: # CDN links of `fancybox` plugin used on Gallery page
  fancybox_css: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.css
  fancybox_js: https://cdn.bootcss.com/fancybox/3.5.7/jquery.fancybox.min.js
  jquery_js: https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js
  lazyload_js: https://cdn.bootcss.com/jquery_lazyload/1.9.7/jquery.lazyload.min.js
busuanzi: # Use `busuanzi` plugin to count website visits
  site: false
  page: false
  busuanzi_js: http://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
qrcode: # Qrcode for articles. if use `plugin`, `hexo-helper-qrcode` plugin is needed
  caption: Send to mobile phone
  use: plugin
donate: # Use your payment qrcode or link to receive donations. Set with `name` and `link`
search: # Search settings. if use `plugin`, `hexo-generator-search` plugin is needed and `path` should be set correctly
  placeholder: Enter the key words
  path: /search.xml
  use: plugin
comment: # Comment plugin settings. Set `use` with the plugin name such as `gitalk`
  use: false
  disqus_shortname:
  gitalk_client_id:
  gitalk_client_secret:
  gitalk_repo:
  gitalk_owner:
  livere_data_uid:
  valine_leancloud_app_id:
  valine_leancloud_app_key:
  valine_placeholder:
  valine_page_size:
  valine_avatar:
  valine_lang:
  valine_guest_info:
  valine_notify:
  valine_verify:
  changyan_app_id:
  changyan_app_key:
  changyan_sid_type:
```

**Hexo and Plugin version(`npm ls --depth 0`)**
```
hexo-site@0.0.0 G:\hexo-blog\blog
+-- hexo@5.4.0
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-marked@4.0.0
+-- hexo-renderer-stylus@2.0.1
+-- hexo-server@2.0.0
+-- hexo-theme-landscape@0.0.3
`-- hexo-wordcount@6.0.1
```

## Others
```
INFO  Validating config
INFO  Start processing
INFO  Files loaded in 360 ms
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
ERROR ReferenceError: G:\hexo-blog\blog\themes\materialized\layout\post.ejs:1
 >> 1| <%- partial('_partial/article') %>

G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:45
    43|             <li class="mdui-menu-item" disabled>
    44|               <% if (theme.qrcode.use === 'plugin') { %>
 >> 45|                 <img src="<%- qrcode(page.permalink, {margin: 2}) %>">
    46|               <% } else { %>
    47|                 <img src="<% if (config.language === 'zh-CN') { %>http://qr.liantu.com/api.php?w=246&m=10&text=<%- page.permalink %><% } else { %>https://chart.googleapis.com/chart?cht=qr&chs=246x246&chl=<%- page.permalink %>&chld=M|2<% } %>">
    48|               <% } %>

qrcode is not defined
    at eval (G:\hexo-blog\blog\themes\materialized\layout\_partial\article.ejs:72:7)
    at article (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (G:\hexo-blog\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (G:\hexo-blog\blog\themes\materialized\layout\post.ejs:10:17)
    at post (G:\hexo-blog\blog\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (G:\hexo-blog\blog\node_modules\hexo\lib\theme\view.js:39:17)
    at G:\hexo-blog\blog\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (G:\hexo-blog\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\hexo-blog\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\hexo-blog\blog\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:968:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  path: 'G:\\hexo-blog\\blog\\themes\\materialized\\layout\\post.ejs'
}
INFO  Generated: archives/2021/03/index.html
INFO  Generated: tags/教程/index.html
INFO  Generated: archives/2021/04/index.html
INFO  Generated: tags/MineCraft-nbsp-Server/index.html
INFO  Generated: tags/科普/index.html
INFO  Generated: tags/娱乐/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2021/index.html
INFO  Generated: index.html
INFO  9 files generated in 119 ms
```
