### ISSUE TITLE
hexo generate command not working as expected on Github Action

### ISSUE THREAD

**Issue by boylavua18** [hexojs/hexo#4773]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

`hexo generate` this command only generate `.html` files and lack of `.css` and `.js` files on Github Aciton environment but it works normally on local.
I already followed the guideline on https://hexo.io/docs/github-pages but getting same issue.

The following is build's outputs on Github Action:
```
> hexo generate

INFO  Validating config
INFO  Start processing
INFO  Files loaded in 95 ms
WARN  No layout: categories/index.html
WARN  No layout: tags/index.html
WARN  No layout: 2021/09/08/hello-world/index.html
WARN  No layout: 2021/09/08/we-are-cozde/index.html
WARN  No layout: archives/index.html
WARN  No layout: archives/2021/index.html
WARN  No layout: archives/2021/09/index.html
WARN  No layout: index.html
WARN  No layout: tags/hello-world/index.html
INFO  Generated: categories/index.html
INFO  Generated: tags/index.html
INFO  Generated: archives/index.html
INFO  Generated: archives/2021/index.html
INFO  Generated: archives/2021/09/index.html
INFO  Generated: tags/hello-world/index.html
INFO  Generated: index.html
INFO  Generated: 2021/09/08/hello-world/index.html
INFO  Generated: 2021/09/08/we-are-cozde/index.html
INFO  9 files generated in 78 ms
```

P/s: Im using provided theme on https://hexo.io/themes/ for my hexo site

## Environment & Settings

**Node.js & npm version**

```
v14.9.0
```

**Github Action `.yml`**

```
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        # You may pin to the exact commit or the version.
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.DEPLOY_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          disable_nojekyll: true

      - name: Get the output
        run: |
          echo "${{ steps.deploy.outputs.notify }}"
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.0"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-all-minifier": "^0.5.7",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^2.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}
```
