### ISSUE TITLE
How can i fix curly bracket translate to unicode in pre ?

### ISSUE THREAD

**Issue by zongzi531** [hexojs/hexo#4831]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Question

How can i fix curly bracket translate to unicode in pre ?

Like this: https://github.com/hexojs/hexo/pull/4489#issuecomment-678721143

## Environment & Settings

**Node.js & npm version**

```
node: v12.22.1
npm: 6.14.12
```

**Your site `_config.yml`** (Optional)

```
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude:
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
updated_option: 'date'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: journal

prism_plugin:
  mode: 'preprocess'
  theme: 'material-oceanic'
  line_number: true 

category_generator:
  per_page: 10
  enable_index_page: true

tag_generator:
  per_page: 10
  order_by: -date

emoji:
  enable: true
  className: github-emoji
  styles:
  customEmojis:

mathjax:
  single_dollars: true
  cjk_char_width: 16
  svg: true
```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
├── hexo@5.4.0
├── hexo-deployer-git@3.0.0
├── hexo-filter-emoji@2.2.2
├── hexo-filter-mathjax@0.8.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-category-enhance@0.1.6
├── hexo-generator-feed@3.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-tag@1.0.0
├── hexo-prism-plugin@2.3.0
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@4.1.0
├── hexo-renderer-stylus@2.0.1
├── hexo-server@2.0.0
└── node-pre-gyp@0.12.0 extraneous
```

**Your package.json `package.json`**

```
{
  "name": "zongzi531.github.io",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "5.4.0"
  },
  "scripts": {
    "s": "hexo server",
    "c": "hexo clean",
    "g": "hexo generate",
    "build": "yarn c && yarn g"
  },
  "dependencies": {
    "hexo": "5.4.0",
    "hexo-deployer-git": "3.0.0",
    "hexo-filter-emoji": "2.2.2",
    "hexo-filter-mathjax": "0.8.0",
    "hexo-generator-archive": "1.0.0",
    "hexo-generator-category": "1.0.0",
    "hexo-generator-category-enhance": "0.1.6",
    "hexo-generator-feed": "3.0.0",
    "hexo-generator-index": "2.0.0",
    "hexo-generator-tag": "1.0.0",
    "hexo-prism-plugin": "2.3.0",
    "hexo-renderer-ejs": "2.0.0",
    "hexo-renderer-marked": "4.1.0",
    "hexo-renderer-stylus": "2.0.1",
    "hexo-server": "2.0.0"
  }
}
```
