### ISSUE TITLE
FATAL RangeError: Invalid string length

### ISSUE THREAD

**Issue by dimaslanjaka** [hexojs/hexo#4922]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

I don't know why this error occurs. Even though yesterday was okay.
I don't know why this error occurs. Even though yesterday it was okay.
- I didn't change anything in the code
- I didn't modify the theme, even if I changed the theme many times, the error still persists.
- I didn't modify any plugins
[LOG Workflow](https://github.com/dimaslanjaka/dimaslanjaka.github.io/runs/5710685988?check_suite_focus=true)
```shell
FATAL {
  err: RangeError: Invalid string length
      at JSON.stringify (<anonymous>)
      at _Model._export (/media/dimaslanjaka/DATA/Repositories/gh-pages/node_modules/warehouse/lib/model.js:932:17)
      at exportAsync (/media/dimaslanjaka/DATA/Repositories/gh-pages/node_modules/warehouse/lib/database.js:50:44)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
```
Environtment
```log
hexo: 6.0.0
hexo-cli: 4.3.0
os: linux 5.13.0-37-generic Zorin OS 16.1
node: 14.18.1
v8: 8.4.371.23-node.84
uv: 1.42.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.17.2
modules: 83
nghttp2: 1.42.0
napi: 8
llhttp: 2.1.4
openssl: 1.1.1l
cldr: 39.0
icu: 69.1
tz: 2021a
unicode: 13.0
```

**Comment by dimaslanjaka** [comment]
Hellooooo why still getting errors ?
```log
FATAL {
  err: RangeError: Invalid string length
      at JSON.stringify (<anonymous>)
      at _Model._export (D:\Repositories\gh-pages-old\node_modules\warehouse\lib\model.js:932:17)
      at exportAsync (D:\Repositories\gh-pages-old\node_modules\warehouse\lib\database.js:50:44)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
FATAL RangeError: Invalid string length
    at JSON.stringify (<anonymous>)
    at _Model._export (D:\Repositories\gh-pages-old\node_modules\warehouse\lib\model.js:932:17)
    at exportAsync (D:\Repositories\gh-pages-old\node_modules\warehouse\lib\database.js:50:44)
```

i've tried remove all plugins, change themes.

**Comment by yoshinorin** [comment]
@dimaslanjaka 

It seems Out of memory exception and it is from v8.

> https://github.com/nodejs/node-v0.x-archive/issues/14170
> https://stackoverflow.com/questions/29175877/json-stringify-throws-rangeerror-invalid-string-length-for-huge-objects

**Comment by dimaslanjaka** [comment]
> @dimaslanjaka
> 
> It seems Out of memory exception and it is from v8.
> 
> > [nodejs/node-v0.x-archive#14170](https://github.com/nodejs/node-v0.x-archive/issues/14170)
> > https://stackoverflow.com/questions/29175877/json-stringify-throws-rangeerror-invalid-string-length-for-huge-objects

ive tried with this, same result
```yaml
name: Build

on:
  push:
    branches:
      - compiler # run when this branch pushed

# cancel previous workflows, run only one workflow
concurrency:
  group: build-${{ github.event.push.number || github.event.pull_request.number || github.ref }}
  #cancel-in-progress: true

jobs:
  build:
    if: {{ $false }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      NODE_OPTIONS: "--max_old_space_size=8192" #8192 4096 --expose-gc
      GITFLOW: true
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Setup Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M:%S')"
      - name: Setup GitHub
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Get npm cache directory
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Get Caches
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.npm-cache-dir.outputs.dir }}
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules
            ~/.npm
            ./tmp
            ./build
            ./packages
            ./databases
          key: ${{ runner.os }}-xnodex-${{ hashFiles('**/.guid') }}
          restore-keys: ${{ runner.os }}-xnodex-
      - run: npm i -g npm hexo-cli gulp-cli typescript ts-node
        # run global install when cache not written
        # if: steps.npm-cache.outputs.cache-hit != 'true'
      - run: npm install
      - run: gulp clean
        if: "contains(github.event.head_commit.message, 'clean cache')"
      - run: "gulp copy:assets"
      - run: "gulp copy:posts"
      - run: "gulp generate:assets"
      - run: "gulp generate:template"
      - run: "gulp generate:posts"
      - run: "gulp generate:after"
      #- run: cp -rf docs/sitemap.html docs/index.html
      - run: cd docs/page && npm install
      - run: cp -rf source/robots.txt docs/robots.txt
      #- run: cp -rf .gitignore docs/.gitignore
      - run: cp -rf README.md docs/readme.md
      - run: echo www.webmanajemen.com > docs/CNAME
      - name: Deploy 🚀
        #if: ${{ false }}
        #if: steps.hexo-validate.outcome == 'success' && steps.hexo-validate.conclusion == 'success'
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: master # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          force: false # merge instead push --force, (keep old / non modified) files?
```
