### ISSUE TITLE
Package hexo-asset-image doesn't return correct image path

### ISSUE THREAD

**Issue by Yidi0213** [hexojs/hexo#4930]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
I enablled `post_asset_folder` and  tried [embedding image with markdown](https://hexo.io/docs/asset-folders#Embedding-an-image-using-markdown). After that I should be able to get correct image path with either markdown syntax or tag plugins.
## Actual behavior 
However I got incorrect file path for both markdown syntax and tag plugins. The
[stack overflow page](https://stackoverflow.com/questions/62512085/hexo-wrong-address-for-meta-and-img-tags) describe the problem and gave a solution.
## How to reproduce?

* Enable `post_asset_folder`
* Follow [embedding image with markdown](https://hexo.io/docs/asset-folders#Embedding-an-image-using-markdown)
* Create a post and include a image
* image won't show up and inspect the image path

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v16.13.2
8.1.2
```

**Your site `_config.yml`** (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yidi's Blog
subtitle: ''
description: ''
keywords:
author: Yidi Wang
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://yidi0213.github.io/blog/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
root: /blog/
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
marked:
  prependRoot: True
  postAsset: True
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: purer

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/Yidi0213/blog


```

**Your theme `_config.yml`** (Optional)

```
```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 /Users/yidiwang/Desktop/projects/hexo-practice/blog
├── @iktakahiro/markdown-it-katex@4.0.1
├── hexo-deployer-git@3.0.0
├── hexo-generator-archive@1.0.0
├── hexo-generator-category@1.0.0
├── hexo-generator-index@2.0.0
├── hexo-generator-json-content@4.2.3
├── hexo-generator-tag@1.0.0
├── hexo-image-link@0.0.3
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-markdown-it@6.0.1
├── hexo-renderer-marked@5.0.0
├── hexo-server@3.0.0
├── hexo-theme-landscape@0.0.3
├── hexo-wordcount@6.0.1
├── hexo@6.1.0
└── markdown-it-emoji@2.0.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "theme": "cat ./_config.theme.yml > ./themes/purer/_config.yml ",
    "build": "npm run theme && hexo generate",
    "clean": "hexo clean",
    "deploy": "npm run theme && hexo deploy",
    "server": "npm run theme && hexo server"
  },
  "hexo": {
    "version": "6.1.0"
  },
  "dependencies": {
    "@iktakahiro/markdown-it-katex": "^4.0.1",
    "hexo": "^6.0.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-json-content": "^4.2.3",
    "hexo-generator-tag": "^1.0.0",
    "hexo-image-link": "^0.0.3",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-markdown-it": "^6.0.1",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-wordcount": "^6.0.1",
    "markdown-it-emoji": "^2.0.0"
  }
}

```
