### ISSUE TITLE
Deploying to Openshift

### ISSUE THREAD

**Issue by kilometers** [hexojs/hexo#494]
(Using this page as a reference: https://github.com/tommy351/hexo/pull/226)

My knowledge of Git isn't very deep. It's a barebones, thin veneer that allows me to inch my way through. As such, I'm experiencing some difficulties configuring my Hexo project for deployment to OpenShift, and I'm not sure if it's a bug or if it's just my settings -- I'm hoping it's the settings.

Whenever I run

```
hexo deploy
```

An error is returned: "ReferenceError: async is not defined"

My current deployment settings in the _config.yml are as follows

```
deploy:
  type: openshift
  root: ssh://**********************@blog-milesb.rhcloud.com/~/git/blog.git/
  remote: origin
  branch: master
```

Constructive guidance (or a complete solution ;) ) would be awesome. Thanks!
