### ISSUE TITLE
After push，appear a new branch?how do I do that？

### ISSUE THREAD

**Issue by GC-ZF** [hexojs/hexo#4989]
Uploaded to the main,Is the expected result(这样是正确的)
```
deploy:
    type: git
    repository: https://github.com/xxx/xxxx.github.io.git	
    branch: main
```
But If I switch lines(I want to deploy multiple Git at the same time),for example(但是如果换一行，我想同时上传多个git)
```
deploy:
    type: git
    repository:
      github: https://github.com/xxx/xxxx.github.io.git
      xxxxxx:git@xxx.xxx.xxx.xxx
    branch: main
```
The github will appear a new branch "gh-pages"(仓库出现新的分支)
![image](https://user-images.githubusercontent.com/94956933/171805790-9ab7160b-551b-48f3-bdf4-251c46bb999a.png)

I found that if switch line， the repository appear new branch，Whether "branch: main" or "gh-pages",(我测试发现，无论branch的值是main还是master，只要我换行就会出现这样的错误)
```
deploy:
    type: git
    repository:
      github: https://github.com/xxx/xxxx.github.io.git	
    branch: main
```

```
deploy:
    type: git
    repository:
      github: https://github.com/xxx/xxxx.github.io.git	
    branch: master
```
So how do I do that？These are the test repository
https://github.com/GC-ZF/T_hexo
https://github.com/GC-ZF/Test_hexo
