### ISSUE TITLE
INFO Validating config FATAL appears when deploying hexo 

### ISSUE THREAD

**Issue by FreeDivers** [hexojs/hexo#5039]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior
I tried to deploy hexo to github pages using hexo d, 
## Actual behavior
but the output was
[![b9GBd.png](https://s1.328888.xyz/2022/08/22/b9GBd.png)](https://imgloc.com/i/b9GBd)
## How to reproduce?

* Step1, enter hexo d
* Step2, prees enter

## Is the problem still there under "Safe mode"?
I don't know, I can't enter safe mode because when I try to enter safe mode I still get the same error.

## Environment & Settings

**Node.js & npm version(`node -v && npm -v`)**

```
v18.7.0
8.18.0
```

**Your site `_config.yml`** (Optional)

```
title: Meteorite's Blog
subtitle: ''
description: ''
keywords: null
author: Meteorite
language: zh-CN
timezone: ''
url: https://meteorite.sbs/
permalink: ':year/:month/:day/:title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: CNAME
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''
index_generator:
  path: ''
  per_page: 10
  order_by: '-date'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: mtime
per_page: 10
pagination_dir: page
include: null
exclude: null
ignore: null
theme: icarus
deploy:
  type: git
  repo: https://github.com/FreeDivers/FreeDivers.github.io.git
  branch: main

```

**Hexo and Plugin version(`npm ls --depth 0`)**

```
hexo-site@0.0.0 C:\Users\35091\Meteorite'sBlog
+-- hexo-component-inferno@2.0.1
+-- hexo-deployer-git@3.0.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-inferno@0.1.3
+-- hexo-renderer-marked@5.0.0
+-- hexo-renderer-stylus@2.1.0
+-- hexo-server@3.0.0
+-- hexo-theme-icarus@5.1.0
+-- hexo-theme-keep@3.4.5
+-- hexo-theme-landscape@0.0.3
`-- hexo@6.2.0
```

**Your package.json `package.json`**

```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.2.0"
  },
  "dependencies": {
    "hexo": "^6.2.0",
    "hexo-component-inferno": "^2.0.1",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-inferno": "^0.1.3",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-icarus": "^5.1.0",
    "hexo-theme-keep": "^3.4.5",
    "hexo-theme-landscape": "^0.0.3"
  }
}
```

## Others

entering all hexo commands will get the same error
