### ISSUE TITLE
Github workflows blank white

### ISSUE THREAD

**Issue by allasca** [hexojs/hexo#5058]
when I did hexo server local its work.
when using hexo clean && hexo deploy ([hexo-deployer-git](https://github.com/hexojs/hexo-deployer-git)) its work.
blank white when using workflows. workflows copied from the doc [https://hexo.io/docs/github-pages.html](https://hexo.io/docs/github-pages.html)
my git [https://github.com/allasca/allasca.github.io](https://github.com/allasca/allasca.github.io)

```
name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
```
