### ISSUE TITLE
hexo publish doesn't move draft to _post folder

### ISSUE THREAD

**Issue by matheosu** [hexojs/hexo#5415]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

Move the draft to post folder

### Actual behavior

Doesn't move the draft to post folder,
But add suffix -1 in draft.

### How to reproduce?

* `hexo new draft test`
* `hexo publish test`

### Is the problem still there under `Safe mode`?

Happens when safe mode too

### Your Node.js & npm version

```text
v21.6.1
10.2.4
```

### Your Hexo and Plugin version

```text
├── hexo-all-minifier@0.5.7
├── hexo-easy-tags-plugin@1.1.0
├── hexo-generator-archive@2.0.0
├── hexo-generator-category@2.0.0
├── hexo-generator-index@3.0.0
├── hexo-generator-tag@2.0.0
├── hexo-lazyload-image@1.0.13
├── hexo-renderer-ejs@2.0.0
├── hexo-renderer-marked@6.2.0
├── hexo-renderer-stylus@3.0.1
├── hexo-server@3.0.0
├── hexo-theme-landscape@1.0.0
├── hexo@7.1.1
└── sharp@0.33.2
```

### Your `package.json`

```json
{
  "name": "matheosu.com.br",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.1.1"
  },
  "dependencies": {
    "hexo": "^7.1.1",
    "hexo-all-minifier": "^0.5.7",
    "hexo-easy-tags-plugin": "^1.1.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-lazyload-image": "^1.0.13",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-stylus": "^3.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^1.0.0",
    "sharp": "^0.33.2"
  }
}
```

### Your site's `_config.yml` (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: M
subtitle: MC
description: I try
keywords: 
author: Matheus Castro
language: pt
timezone: 'America/Sao_Paulo'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://matheosu.github.io
permalink: :title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: true
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: DD MMM YYYY
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: standrews

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

easy_tags_plugin:
  enable: true
  tag_name_case: 1
  sort_ignore_case: true

all_minifier: true

image_minifier:
  enable: false


lazyload:
  enable: false
  onlypost: false # optional
  loadingImg: ./images/loading.gif
  isSPA: false # optional
```

### Others

<img width="509" alt="image" src="https://github.com/hexojs/hexo/assets/6794543/dff3a508-19c0-4ae7-adb0-6bfdeef606f1">

<img width="667" alt="image" src="https://github.com/hexojs/hexo/assets/6794543/334d73e4-05d6-41db-999f-04701ef2e868">
