### ISSUE TITLE
markdown文件里的HTML标签不会被正确地渲染 HTML tags in markdown files are not rendered correctly

### ISSUE THREAD

**Issue by Nightingale0504** [hexojs/hexo#5524]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

When I use the "hexo g" command to ensure that all files are generated correctly (only INFO, no ERROR, no WARN, etc.), and then use the "hexo s" command to deploy the blog environment locally, the HTML tags such as <img src="image link" width="200px"> in the markdown file will be correctly rendered on the page by hexo as images, etc.

### Actual behavior

When I use the "hexo s" command to deploy the blog environment locally after ensuring that all files are correctly generated using the "hexo g" command (only INFO, no ERROR, no WARN and other prompts), the HTML tags such as <img src="image link" width="200px"> used in the markdown file will not be correctly rendered on the page by hexo, but the text form of the HTML tags will be directly displayed on the page (to be precise, hexo does not parse these HTML tags and directly displays them on the page as text)

### How to reproduce?

step 1. Use the "hexo new page xxx" command to create a new page
step 2. Put some HTML tags into the new page and save the page file
step 3. Use the "hexo g" command to generate pages and posts
step 4. Use the "hexo s" command to start the hexo server locally
step 5. Visit the page was created on the step 1
step 6. The images' HTML tags will show to me as the text form

### Is the problem still there under `Safe mode`?

Yes, it is.

### Your Node.js & npm version

```text
Node.js version: v20.15.1
npm version: 10.7.0
```

### Your Hexo and Plugin version

```text
hexo-site@0.0.0 E:\myBlog
+-- hexo-algoliasearch@2.0.1
+-- hexo-autoprefixer@2.0.0
+-- hexo-deployer-git@4.0.0
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-category@2.0.0
+-- hexo-generator-feed@3.0.0
+-- hexo-generator-index@4.0.0
+-- hexo-generator-tag@2.0.0
+-- hexo-indexnow@1.2.0
+-- hexo-lightning-minify@0.1.5
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-multi-markdown-it@0.1.5
+-- hexo-renderer-stylus@3.0.1
+-- hexo-server@3.0.0
+-- hexo-shokax-busuanzi@0.1.0
+-- hexo-symbols-count-time@0.7.1
+-- hexo-theme-landscape@1.0.0
+-- hexo-theme-shokax@0.4.11
+-- hexo@7.3.0
+-- markdown-it-emoji@3.0.0
`-- markdown-it-katex@2.0.3
```

### Your `package.json`

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "7.3.0"
  },
  "dependencies": {
    "hexo": "^7.3.0",
    "hexo-algoliasearch": "^2.0.1",
    "hexo-autoprefixer": "^2.0.0",
    "hexo-deployer-git": "^4.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-feed": "^3.0.0",
    "hexo-generator-index": "^4.0.0",
    "hexo-generator-tag": "^2.0.0",
    "hexo-indexnow": "^1.2.0",
    "hexo-lightning-minify": "^0.1.5",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-multi-markdown-it": "^0.1.5",
    "hexo-renderer-stylus": "^3.0.1",
    "hexo-server": "^3.0.0",
    "hexo-shokax-busuanzi": "^0.1.0",
    "hexo-symbols-count-time": "^0.7.1",
    "hexo-theme-landscape": "^1.0.0",
    "hexo-theme-shokax": "^0.4.11",
    "markdown-it-emoji": "^3.0.0",
    "markdown-it-katex": "^2.0.3"
  }
}
```

### Your site's `_config.yml` (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Striker's Blog
subtitle: ''
description: '* A blog with full of determination.'
keywords: Striker, Blog, 
author: Striker
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://hacknetvault.top
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: false
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  计算机科学: computerScience
  C++: cpp
  Linux: Linux
  业余无线电: amateurRadio
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: shokaX

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:Nightingale0504/nightingale0504.github.io.git
    branch: main
  - type: indexnow_url_submitter
markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer:
    quotes: "“”‘’"
  plugins: # markdown-it 插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的 class 名称，shoka 系主题必须设置成这样
          tocClassName: "toc"
          anchorClassName: "anchor"
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"

autoprefixer:
  exclude:
    - "*.min.css"
minify:
  js:
    enable: false # ShokaX 自带 esbuild 优化，不建议开启，其他主题建议开启
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  css:
    enable: true # 开启 CSS 优化
    options:
      targets: ">= 0.5%" # browserslist 格式的 target
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  html:
    minifier: html-minifier
    enable: true # 开启 HTML 优化
    options:
      comments: false # 是否保留注释内容
    exclude: # 排除文件，接受 string[]，需符合 micromatch 格式
  image:
    enable: true # 开启图片预处理和自动 WebP 化
    options:
      avif: false
      webp: true # 预留配置项，现版本无作用
      quality: 80 # 质量，支持1-100的整数、lossless或nearLossless
      effort: 2 # CPU 工作量，0-6之间的整数(越低越快)
      replaceSrc: true # 自动替换生成html中的本地图片链接为webp链接
      # 我们更建议使用 Service Worker 来在用户侧实现 replaceSrc 的功能，这将能够以一种侵入式更小的方式实现链接替换
    exclude:
feed:
  limit: 20
  order_by: "-date"
  tag_dir: false
  category_dir: false
  rss:
    enable: true
    template: "node_modules/hexo-theme-shokax/layout/_alternate/rss.ejs"
    output: "rss.xml"
  atom:
    enable: true
    template: "node_modules/hexo-theme-shokax/layout/_alternate/atom.ejs"
    output: "atom.xml"
  jsonFeed:
    enable: true
    template: "node_modules/hexo-theme-shokax/layout/_alternate/json.ejs"
    output: "feed.json"
algolia:
  appId: "1DXKA8NHXD"
  apiKey: "1c328e848850996c0006d72ec2c8dd0e"
  adminApiKey: "156365afa27cd1946eba2f68c5be15c1"
  chunkSize: 5000
  indexName: "shokaX"
  fields:
    - title #必须配置
    - path #必须配置
    - categories #推荐配置
    - content:strip:truncate,0,2000
    - gallery
    - photos
    - tags
hexo_indexnow:
  count: latest # 数字或者 "latest"(=1)
  txt_name: indexnow.txt # 链接文件名
  apikey: e91948bdb59a4fb89337137fdc452ea0 # 你的 apikey
  server: bing # indexnow 服务器，可选值有:bing、yandex、indexnow
```
