### ISSUE TITLE
Tags and Archives links shoud follow permalink configuration

### ISSUE THREAD

**Issue by majkel89** [hexojs/hexo#5543]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/).
- [X] I have already searched existing issues.

### Feature Request

It is possible to configure permalinks for posts

```yaml
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
```

This way posts links are as follows: `http://localhost:4000/2024/09/08/hello-world/index.html`

The settings does not apply for tags (`http://localhost:4000/tags/tag1/`) nor archives (`http://localhost:4000/archives/2024/09/`).

It leads to problems when blog is hosted behind private S3 bucket.

To make the links consistent my proposition is to add `/index.html` to links generated by `listTagsHelper` and `listArchivesHelper`
