### ISSUE TITLE
hexo不执行 hexo command not executed

### ISSUE THREAD

**Issue by zuanshijia** [hexojs/hexo#5579]
### Check List

- [X] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting).
- [X] I have already searched existing issues and they are not help to me.
- [X] I examined error or warning messages and it's difficult to solve.
- [X] I am using the [latest](https://github.com/hexojs/hexo/releases) version of Hexo. (run `hexo version` to check)
- [X] My Node.js is matched [the required version](https://hexo.io/docs/#Required-Node-js-version).

### Expected behavior

I want to clear my blog files and generate new ones

### Actual behavior

After I entered hexo clean, CMD did not execute the hexo command and got stuck.After waiting for half an hour, the message 'INFO  Validating config' was displayed,and it took many more minutes to complete the execution.

### How to reproduce?

1. Open cmd
2. enter hexo clean or hexo g
3. Long waiting time

### Is the problem still there under `Safe mode`?

Still exists

### Your Node.js & npm version

```text
node -v : v22.11.0
npm -v : 10.9.0
```

### Your Hexo and Plugin version

```text
hexo-site@0.0.0 e:\Websize2\websize2
+-- hexo-abbrlink@2.2.1
+-- hexo-deployer-git@4.0.0
+-- hexo-deployer-heroku@1.0.0
+-- hexo-generator-archive@2.0.0
+-- hexo-generator-baidu-sitemap@0.1.9
+-- hexo-generator-category@2.0.0
+-- hexo-generator-index@3.0.0
+-- hexo-generator-sitemap@3.0.1
+-- hexo-generator-tag@2.0.0
+-- hexo-renderer-ejs@2.0.0
+-- hexo-renderer-marked@6.2.0
+-- hexo-renderer-pug@3.0.0
+-- hexo-renderer-stylus@2.1.0
+-- hexo-server@3.0.0
+-- hexo-tag-aplayer@3.0.4
+-- hexo-theme-landscape@1.0.0
`-- hexo@6.3.0
```

### Your `package.json`

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.3.0"
  },
  "dependencies": {
    "hexo": "^6.3.0",
    "hexo-abbrlink": "^2.2.1",
    "hexo-deployer-git": "^4.0.0",
    "hexo-deployer-heroku": "^1.0.0",
    "hexo-generator-archive": "^2.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.9",
    "hexo-generator-category": "^2.0.0",
    "hexo-generator-index": "^3.0.0",
    "hexo-generator-sitemap": "^3.0.1",
    "hexo-generator-tag": "^2.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^6.0.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^2.1.0",
    "hexo-server": "^3.0.0",
    "hexo-tag-aplayer": "^3.0.4",
    "hexo-theme-landscape": "^1.0.0"
  }
}
```

### Your site's `_config.yml` (Optional)

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 钻石甲的博客网站
subtitle: '人要成仙，必先疯癫'
description: '钻石甲的博客网站'
keywords: '钻石甲的博客网站'
author: zuanshijia
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://chengtext.eu.org
permalink: posts/:abbrlink.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly5.2

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/zuanshijia/zuanshijia.github.io
  # example, https://github.com/hexojs/hexojs.github.io
  branch: main
```

### Others

![1](https://github.com/user-attachments/assets/559440fa-566d-4339-a138-e4f81700faf4)
![2](https://github.com/user-attachments/assets/7db8c5dd-2d1e-406f-98e9-ce30c1ed1452)
