### ISSUE TITLE
Multiple Deployment not working?

### ISSUE THREAD

**Issue by daxiawj** [hexojs/hexo#611]
I am using the most updated version of node.js and hexo, and I'd like to deploy my blog into both github and gitcafe. According to the document, the configuration like the following should be working:

```
deploy:
 - type: github
  repo: https://github.com/daxiawj/daxiawj.github.io.git
 - type: github
  repo: https://gitcafe.com/daxiawj/daxiawj.git, gitcafe-pages
```

while this does not work. Hexo says: 

```
You should configure deployment settings in _config.yml first!

Available Types:
  git, github, heroku, openshift, rsync
```

If I change the config to 

```
deploy:
 type: github
 repo: https://github.com/daxiawj/daxiawj.github.io.git
 type: github
 repo: https://gitcafe.com/daxiawj/daxiawj.git
 branch: gitcafe-pages
```

then it will only deploy to the last one--gitcafe but not github.

Is any thing wrong here in my config or just there is a bug here?

Thanks!
