### ISSUE TITLE
Multiple Deployment not working?

### ISSUE THREAD

**Issue by daxiawj** [hexojs/hexo#613]
@tommy351 

Hello, I saw that hexo can do batch deployment  with one config at http://hexo.io/docs/deployment.html#Batch_Deploy

But with my config:

```
deploy:
-  type: github
   repo: https://github.com/daxiawj/daxiawj.github.io.git
-  type: github
   repo: https://gitcafe.com/daxiawj/daxiawj.git
   branch: gitcafe-pages
```

It tells 

```
You should configure deployment settings in _config.yml first!

Available Types:
  git, github, heroku, openshift, rsync

For more help, you can check the online docs: http://hexo.io/
```

if the config changed to 

```
deploy:
   type: github
   repo: https://github.com/daxiawj/daxiawj.github.io.git
   type: github
   repo: https://gitcafe.com/daxiawj/daxiawj.git
   branch: gitcafe-pages
```

then it will only deploy to gitcafe.

I'm running latest  version of node.js and hexo. 
Thanks!
