### ISSUE TITLE
Multiple deployment not working.

### ISSUE THREAD

**Issue by ptbsare** [hexojs/hexo#681]
When the deploy in the _config.yml is

```
deploy:
- type: github
  repo: https://github.com/xxx/xxx.github.io.git
- type: github
  repo: https://gitcafe.com/xxx/xxx.git
  branch: gitcafe-pages
```

Hexo just deploy the first one twice.And Hexo does not deploy the second one.
But when I change this to

```
deploy:
  type: github
  repo: https://github.com/xxx/xxx.github.io.git
  type: github
  repo: https://gitcafe.com/xxx/xxx.git
  branch: gitcafe-pages
```

Hexo just deploy the second one.
