### ISSUE TITLE
Swig templates: looping over posts does not seem to work

### ISSUE THREAD

**Issue by arty-name** [hexojs/hexo#714]
I want to write a theme using Swig. I have following `index.swig`:

```
{% for post in page.posts %}
    title: {{ post.title }}
    content: {{ post.content }}
{% endfor %}
```

Running `hexo g` produces following output: 

```
    title:
    content:

    title:
    content:

    title:
    content:
```

[Documentation for variables](http://hexo.io/docs/variables.html) says: 

> page.posts    Posts in this page ([Data Model])

[Documentation for models](http://hexo.io/docs/models.html) says:

> title     Post title
> content   The full processed content of the post
