### ISSUE TITLE
hexo d时有一个报错导致不能的deploy到github上

### ISSUE THREAD

**Issue by gejiawen** [hexojs/hexo#789]
``` bash
fatal: Unable to find remote helper for 'https'
[info] Deploy done: github
```

我的_config.yml

``` yml
deploy:
  type: github
  repository: https://github.com/gejiawen/gejiawen.github.io.git
  branch: master
```

这是怎么回事啊？之前都是能用的 @tommy351
