### ISSUE TITLE
Github configuration question / problem

### ISSUE THREAD

**Issue by metasean** [hexojs/hexo#857]
I'm trying to set up a hexo blog for my github pages, but nothing I have done has worked.  As a final test I did the following.
1. on my local machine, I deleted my previous metasean.github.io folder
2. on Github, I deleted my previous metasean.github.io repository
3. on Github, I created a new metasean.github.io repository
4. `hexo init metasean.github.io` (everything looks good)
5. `cd metasean.github.io`
6. `npm install` (everything looks good)
7. in my _config.yml, I replaced

```
   # Deployment
   ## Docs: http://hexo.io/docs/deployment.html
   deploy:
      type:
```

  with

```
   # Deployment
   ## Docs: http://hexo.io/docs/deployment.html
   deploy:
      type: github
      repo: git@github.com:metasean/metasean.github.io.git
      branch: [branch]
      message: [message]
```
1. saved my updated _config.yml file
2. `hexo deploy`

The terminal message returned is:

```
   You should configure deployment settings in _config.yml first!

   Available Types:
     git, github, heroku, openshift, rsync

   For more help, you can check the online docs: http://hexo.io/
```

I've been through the online docs and I'm not seeing any other deployment settings that must be changed in order to deploy to Github.  Please help; what am I missing?
