### ISSUE TITLE
Deploy via git and rsync

### ISSUE THREAD

**Issue by robin-lee** [hexojs/hexo#862]
```
deploy:
  type: github
  message: "Blog updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"
  repo: git@github.com:robin-lee/blog.git
  branch: master
  type: rsync
  host: xxxxx
  user: robin
  root: blog
```

Is it possible to deploy via rsync and git? 
With my above config hexo deploy only deploys to the type lower in the list.
