### ISSUE TITLE
root not present for internal link in markdown

### ISSUE THREAD

**Issue by leesei** [hexojs/hexo#943]
`_config.yml`

``` yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com/child
root: /child/
...
relative_link: true
```

In a post:

``` md
Link to [about](/about).
```

**EDIT**: `relative_link` is set to `true`
Link generated: http://yoursite.com/about
Link expected:  http://yoursite.com/child/about

Should we hack relative link (not starting with `http(s)`) to add `root` to them?
Or there is swig helpers I should use for this?
