### ISSUE TITLE
在站点的_config.yml中增加社交链接属性

### ISSUE THREAD

**Issue by Alex1990** [hexojs/hexo#994]
比如

```yaml
socials:
  facebook:
  twitter:
  github:
```

虽然我们可以自己在站点的`_config.yml`中增加，但是统一下比较好，方便切换主题（虽然很少切换）。
